window.WowDBDict = {
  "Housing Hub": "家宅中心",
  "Horde Housing District": "部落住宅区",
  "Alliance Housing District": "联盟住宅区",
  "Housing Plots": "房屋地块",

  // 当前版本：12.0.0.63854
  // 更新时间：2025/10/17
  "Ornate Stonework Fireplace": "华丽的石制壁炉",
  "Tusked Fireplace": "獠牙壁炉",
  "Rolled Scroll": "卷起来的卷轴",
  "Sturdy Wooden Bookcase": "牢固的木制书柜",
  "Sturdy Wooden Shelf": "牢固的木制架子",
  "Three-Candle Wrought Iron Chandelier": "三烛锻铁吊灯",
  "Sturdy Wooden Interior Door": "Sturdy Wooden Interior Door",
  "Small Fruit Platter": "小型果盘",
  "Wrought Iron Floor Lamp": "锻铁地灯",
  "\"Sunrise Canyon\" Painting": "\"Sunrise Canyon\" Painting",
  "Goldshire Window": "闪金镇窗户",
  "Tall Sturdy Wooden Bookcase": "牢固的木制高书柜",
  "Abandoned Bookcase": "废弃的书柜",
  "Wooden Coffin Lid": "木制棺材板",
  "Empty Stormwind Market Stand": "空的暴风城集市小摊",
  "Stormwind Bean Seller's Stand": "暴风城豆商的摊位",
  "Stormwind Spice Merchant's Stand": "暴风城香料商的摊位",
  "Gryphon Roost": "狮鹫栖木",
  "Sturdy Wooden Coffin": "牢固的木制棺材",
  "Open Wooden Coffin": "打开的木制棺材",
  "Open-Air Sturdy Tent": "牢固的开放式帐篷",
  "Sturdy Sheltering Tent": "牢固的遮蔽式帐篷",
  "Small Stonework Fountain": "小型石制喷泉",
  "Large Stonework Fountain": "大型石制喷泉",
  "Sturdy Roofed Wagon": "牢固的顶棚马车",
  "Sturdy Open Wagon": "牢固的开顶马车",
  "Sturdy Covered Wagon": "牢固的顶罩马车",
  "Well-Built Well": "精良的水井",
  "Sturdy Wooden Wheelbarrow": "牢固的木制独轮车",
  "Sturdy Wooden Chair": "牢固的木制椅子",
  "Sturdy Wooden Bed": "牢固的木制床铺",
  "Covered Wooden Table": "遮盖的木制桌子",
  "Sturdy Wooden Table": "牢固的木制桌子",
  "Circular Woolen Rug": "圆形羊绒毯",
  "Studded Wooden Chair": "镶钉木制椅子",
  "Orcish Wooden Bench": "兽人木制长椅",
  "Gift of Gilneas": "吉尔尼斯的礼物",
  "Charming Laurel Tree": "婀娜的月桂树",
  "Orgrimmar Interior Narrow Wall": "奥格瑞玛室内窄墙",
  "Orgrimmar Interior Doorway": "奥格瑞玛室内门廊",
  "Orgrimmar Interior Wall": "奥格瑞玛室内墙壁",
  "Orgrimmar Round Interior Pillar": "奥格瑞玛室内圆形立柱",
  "Orgrimmar Square Interior Pillar": "奥格瑞玛室内方形立柱",
  "Stormwind Interior Pillar": "暴风城室内立柱",
  "Stormwind Interior Narrow Wall": "暴风城室内窄墙",
  "Stormwind Interior Wall": "暴风城室内墙壁",
  "Stormwind Interior Doorway": "暴风城室内门廊",
  "Sturdy Wooden Interior Pillar": "牢固的木制室内立柱",
  "Plain Interior Wall": "朴素的室内墙壁",
  "Plain Interior Doorway": "朴素的室内门廊",
  "Plain Interior Narrow Wall": "朴素的室内窄墙",
  "Wild Violet Bellflowers": "狂野的紫罗兰风铃草",
  "Reaching Violet Bellflowers": "伸展的紫罗兰风铃草",
  "Arched Violet Bellflowers": "弯垂的紫罗兰风铃草",
  "Algari Lettuce Plant": "阿加盆栽生菜",
  "NYI 12PH_Opulent_INE01_Partition_Pillar.wmo": "NYI 12PH_Opulent_INE01_Partition_Pillar.wmo",
  "NYI 12PH_Opulent_INE01_Partition_W_L.wmo": "NYI 12PH_Opulent_INE01_Partition_W_L.wmo",
  "NYI 12PH_Opulent_INE01_Partition_W_S.wmo": "NYI 12PH_Opulent_INE01_Partition_W_S.wmo",
  "NYI 12PH_Opulent_INE01_Partition_W_L_Arch.wmo": "NYI 12PH_Opulent_INE01_Partition_W_L_Arch.wmo",
  "Moon-Blessed Storage Crate": "月福储物箱",
  "Ancient Elven Highback Chair": "上古精灵高背椅",
  "Cenarion Privacy Screen": "塞纳里奥私密屏风",
  "Deluxe Val'sharah Bed": "豪华瓦尔莎拉床铺",
  "Cenarion Rectangular Rug": "塞纳里奥长方形毯子",
  "Cenarion Round Rug": "塞纳里奥圆形毯子",
  "Kaldorei Desk": "卡多雷桌子",
  "Silvermoon Wooden Chair": "银月城木制椅子",
  "Small Silvermoon Bookcase": "小型银月城书柜",
  "Reliquary Storage Crate": "神圣遗物学会储物箱",
  "Long Sin'dorei Rug": "长条辛多雷毯子",
  "Circular Sin'dorei Rug": "圆形辛多雷毯子",
  "Reliquary Telescope": "神圣遗物学会望远镜",
  "Ceiling Cobweb": "天花板蛛网",
  "Tented Cobweb": "帐篷形蛛网",
  "Small Dangling Cobweb": "小型垂挂蛛网",
  "Large Dangling Cobweb": "大型垂挂蛛网",
  "Pillar Cobweb": "立柱蛛网",
  "Wrought Iron Chandelier": "锻铁吊灯",
  "Hungry Human's Platter": "饥饿人类的拼盘",
  "Tirisgarde Book Tempest": "提瑞斯秘法会魔典风暴",
  "Wooden Mug": "木制酒杯",
  "\"Night on the Jeweled Estate\" Painting": "\"Night on the Jeweled Estate\" Painting",
  "\"The Final Study\" Painting": "\"The Final Study\" Painting",
  "\"The Fallen Archmage\" Painting": "\"The Fallen Archmage\" Painting",
  "Boralus-Style Lobster Platter": "伯拉勒斯风龙虾拼盘",
  "Venthyr Tome of Unforgiven Sins": "温西尔的难赦罪孽之书",
  "\"Aspects in the Clouds\" Painting": "\"Aspects in the Clouds\" Painting",
  "\"Water Falls Home\" Painting": "\"Water Falls Home\" Painting",
  "Dornic Mine and Cheese Platter": "多恩矿石与奶酪拼盘",
  "Literature of Dornogal": "多恩诺嘉尔文学著作",
  "Literature of Taelloch": "塔尔罗克文学著作",
  "Literature of Gundargaz": "冈达加兹文学著作",
  "Collection of Arathi Scripture": "阿拉希雕像收藏",
  "Councilward's Jeweled Goblet": "议会护持的珠宝高脚杯",
  "Kaheti Predator's Assortment": "卡赫提掠食者的什锦",
  "Open Tome of Twilight Nihilism": "翻开的暮光妄想之书",
  "Tome of Silvermoon Intrigue": "银月城阴谋之书",
  "Tome of Twilight Nihilism": "暮光妄想之书",
  "\"Edge of Val'sharah\" Painting": "\"Edge of Val'sharah\" Painting",
  "Stormwind Produce Seller's Stand": "暴风城农产品商的摊位",
  "Small Poppy Cluster": "小簇粟花",
  "Creeping Corner Ivy": "蔓延的墙角藤蔓",
  "Small Boxwood Bush": "小型黄杨灌木",
  "Cozy Four-Pipe Bed": "舒适的四管床",
  "Rocket-Unpowered Rocket": "火箭失能的火箭",
  "Well-Lit Incontinental Loveseat": "Well-Lit Incontinental Loveseat",
  "Lordaeron Banded Crate": "洛丹伦箍边箱",
  "Lordaeron Banded Barrel": "洛丹伦箍边桶",
  "Inert Blight Canister": "失能的荒芜之罐",
  "Banshee Queen's Banner": "女妖之王的旗帜",
  "Brill Coffin": "布瑞尔棺材",
  "Gilnean Cauldron": "吉尔尼斯大锅",
  "Gilnean Celebration Keg": "吉尔尼斯庆典酒桶",
  "Worgen's Chicken Coop": "狼人的鸡窝",
  "Gilnean Bench": "吉尔尼斯长椅",
  "Gilnean Wooden Bed": "吉尔尼斯木制床铺",
  "Open Lordaeron Banded Crate": "打开的洛丹伦箍边箱",
  "Forsaken Studded Table": "被遗忘者镶钉桌子",
  "Tirisfal Wooden Chair": "提瑞斯法木制椅子",
  "Forsaken Spiked Chair": "被遗忘者尖刺椅子",
  "Forsaken Round Rug": "被遗忘者圆形毯子",
  "Studious Sin'dorei Desk": "辛多雷学究桌子",
  "Brill Coffin Lid": "布瑞尔棺材板",
  "Lordaeron Fence": "洛丹伦栅栏",
  "Lordaeron Fencepost": "洛丹伦栅栏桩",
  "Elodor Barrel": "艾洛多尔桶",
  "Argussian Crate": "阿古斯箱子",
  "Spherical Draenic Topiary": "球形德莱尼修剪器",
  "Hanging Draenethyst Light": "德拉诺悬挂灯具",
  "Karabor Bed": "Karabor Bed",
  "Draenic Bookcase": "德莱尼书柜",
  "Draenic Storage Chest": "德莱尼储物箱",
  "Forsaken War Planning Table": "被遗忘者作战规划桌",
  "Lordaeron Spiked Weapon Rack": "洛丹伦尖刺武器架",
  "Lordaeron Lantern": "洛丹伦灯笼",
  "Forsaken Long Table": "被遗忘者长桌",
  "Lordaeron Hanging Lantern": "洛丹伦悬挂灯笼",
  "Large Forsaken War Tent": "大型被遗忘者作战帐篷",
  "Small Forsaken War Tent": "小型被遗忘者作战帐篷",
  "Blightfire Lantern": "疫火灯笼",
  "Blightfire Hanging Lantern": "疫火悬挂灯笼",
  "Lordaeron Sconce": "洛丹伦灯台",
  "Blightfire Sconce": "疫火灯台",
  "Undercity Spiked Chest": "幽暗城尖刺箱子",
  "Lordaeron Rectangular Rug": "洛丹伦长方形毯子",
  "Lordaeron Torch": "洛丹伦火炬",
  "Blightfire Torch": "疫火火炬",
  "Dark Ship's Lantern": "黑船的灯笼",
  "Forsaken Spiked Brazier": "被遗忘者尖刺火盆",
  "Large Forsaken Spiked Brazier": "大型被遗忘者尖刺火盆",
  "Elegant Padded Chair": "Elegant Padded Chair",
  "Elegant Padded Footstool": "Elegant Padded Footstool",
  "Elegant Covered Bench": "Elegant Covered Bench",
  "Elegant Wooden Dresser": "Elegant Wooden Dresser",
  "Small Elegant End Table": "Small Elegant End Table",
  "Ornate Weapon Rack": "Ornate Weapon Rack",
  "Elegant Carved Bench": "Elegant Carved Bench",
  "Open Elven Wood Crate": "Open Elven Wood Crate",
  "Grand Elven Bookcase": "Grand Elven Bookcase",
  "Stormwind Hall Rug": "暴风城厅堂毯子",
  "Secretive Bookcase Wall": "神秘的书柜墙壁",
  "Dark Iron Expedition Tent": "黑铁远征帐篷",
  "Loch Modan Bearskin Rug": "洛克莫丹熊皮毯子",
  "Replica Dark Iron Mole Machine": "仿制的黑铁挖掘机",
  "Gallagio L.U.C.K. Spinner": "加乐宫“试试手气”大转盘",
  "Sturdy Wooden Bench": "牢固的木制长椅",
  "Wicker Basket": "柳条篮",
  "Small Elegant Padded Chair": "Small Elegant Padded Chair",
  "Standing Ornate Weapon Rack": "Standing Ornate Weapon Rack",
  "Small Mask of Bwonsamdi, Loa of Graves": "小型坟墓之神邦桑迪的面具",
  "Elegant Elven Desk": "Elegant Elven Desk",
  "Carved Elven Bookcase": "Carved Elven Bookcase",
  "Grand Elven Bench": "Grand Elven Bench",
  "Red Dazar'alor Rug": "红色达萨罗毯子",
  "Square Pandaren Table": "方形熊猫人桌子",
  "Zandalari Rickshaw": "赞达拉人力车",
  "Pandaren Cradle Stool": "熊猫人摇篮凳",
  "Gemmed Eversong Lantern": "嵌宝的永歌灯笼",
  "Bookcase of Gonk": "贡克的书柜",
  "Circular Silvermoon Table": "圆形银月城桌子",
  "Blood Elven Candelabra": "血精灵大烛台",
  "Dazar'alor Market Tent": "达萨罗集市帐篷",
  "Bwonsamdi's Golden Gong": "邦桑迪的金锣",
  "Blue Dazar'alor Rug": "蓝色达萨罗毯子",
  "Rectangular Sin'dorei Rug": "长方形辛多雷毯子",
  "Grand Mask of Bwonsamdi, Loa of Graves": "大型坟墓之神邦桑迪的面具",
  "Idol of Pa'ku, Master of Winds": "风之主宰帕库的神像",
  "Pandaren Wooden Table": "熊猫人木制桌子",
  "Golden Loa's Altar": "金色神灵祭坛",
  "Stone Zandalari Lamp": "石制赞达拉灯笼",
  "Sin'dorei Display Case": "辛多雷陈列柜",
  "Dazar'alor Forge": "达萨罗熔炉",
  "Zuldazar Stool": "祖达萨凳子",
  "Tired Troll's Bench": "疲惫巨魔的长椅",
  "Pandaren Stone Wall": "熊猫人石制墙壁",
  "Silvermoon Library Bookcase": "银月城图书馆书柜",
  "Idol of Rezan, Loa of Kings": "莱赞，诸王的洛阿神灵的神像",
  "Zandalari Weapon Rack": "赞达拉武器架",
  "Long Silvermoon Table": "银月城长桌",
  "Zandalari Sconce": "赞达拉灯台",
  "Zandalari Skullfire Lamp": "赞达拉颅火灯",
  "Pandaren Cooking Table": "熊猫人烹饪桌",
  "Golden Zandalari Bed": "金色赞达拉床铺",
  "Dark Iron Brazier": "Dark Iron Brazier",
  "Gilded Zandalari Table": "鎏金赞达拉桌子",
  "Red Dazar'alor Tent": "红色达萨罗帐篷",
  "Suramar Dresser": "苏拉玛衣柜",
  "Sin'dorei Winged Chaise": "Sin'dorei Winged Chaise",
  "Stonebull Canoe": "石牛独木舟",
  "Thunder Totem Brazier": "雷霆图腾火盆",
  "Whitewash River Basket": "白水溪篮子",
  "Enchanted Blood Elven Candelabra": "血精灵附魔大烛台",
  "Zandalari Ritual Drum": "赞达拉仪祭之鼓",
  "Tauren Leather Fence": "牛头人皮革栅栏",
  "Tauren Fencepost": "牛头人栅栏桩",
  "Empty Wicker Basket": "空的柳条篮",
  "Circular Elven Floor Rug": "Circular Elven Floor Rug",
  "Rectangular Elven Floor Rug": "Rectangular Elven Floor Rug",
  "Large Highmountain Drum": "大型至高岭之鼓",
  "Tauren Waterwheel": "牛头人水车",
  "Undermine Round Table": "安德麦圆形桌子",
  "Undermine Rectangular Table": "安德麦长方形桌子",
  "Spring-Powered Undermine Chair": "弹簧式安德麦椅子",
  "Rusting Bolted Bench": "锈蚀的螺栓长椅",
  "Very Reliable Undermine Lamppost": "Very Reliable Undermine Lamppost",
  "Undermine Fencepost": "安德麦栅栏桩",
  "Undermine Fence": "安德麦栅栏",
  "Rust-Plated Storage Crate": "锈板储物箱",
  "Rust-Plated Storage Barrel": "锈板储物桶",
  "Undermine Market Stall": "安德麦集市摊位",
  "Cartel Head's Schmancy Desk": "财阀老大的花里胡哨办公台",
  "Undermine Bookcase": "安德麦书柜",
  "Undermine Wall Shelf": "安德麦壁挂架子",
  "Shredderwheel Storage Chest": "伐木机轮盘储物箱",
  "Rocket-Powered Fountain": "火箭动力喷泉",
  "Trashfire Barrel": "垃圾小火桶",
  "Zhevra-Stripe Rug": "Zhevra-Stripe Rug",
  "\"Elegant\" Lawn Flamingo": "\"Elegant\" Lawn Flamingo",
  "Undermine Bean Bag Chair": "安德麦豆袋坐垫",
  "Reinforced Goblin Umbrella": "加固的地精雨伞",
  "Rusty Patchwork Tub": "锈蚀的补丁浴盆",
  "Reinforced Wooden Chest": "加固的木制箱子",
  "Tauren Bluff Rug": "牛头人高崖毯子",
  "Elder Rise Rug": "长者高地毯子",
  "Open Silvermoon Drapes": "拉开的银月城窗帘",
  "Small Silvermoon Drapes": "小型银月城窗帘",
  "Warbrave's Brazier": "武士的火盆",
  "Tauren Vertical Windmill": "牛头人垂直风车",
  "Tauren Windmill": "牛头人风车",
  "Small Highmountain Drum": "小型至高岭之鼓",
  "Riverbend Netting": "河湾渔网",
  "Riverbend Jar": "河湾罐子",
  "Highmountain Totem": "至高岭图腾",
  "Skyhorn Storage Chest": "天角储物箱",
  "Tauren Storage Chest": "牛头人储物箱",
  "Dried Whitewash Corn": "晒干的白水玉米",
  "Akunda the Tapestry": "挂毯的阿昆达",
  "Zanchuli Tapestry": "赞枢利挂毯",
  "Zuldazar Fencepost": "祖达萨栅栏桩",
  "Zuldazar Fence": "祖达萨栅栏",
  "Tauren Soup Pot": "牛头人汤锅",
  "Shadowforge Wooden Box": "暗炉木制箱子",
  "Draenor Cookpot": "德拉诺烹饪锅",
  "Frostwolf Bookcase": "Frostwolf Bookcase",
  "Durotar Signal Brazier": "Durotar Signal Brazier",
  "Durotar Hanging Brazier": "Durotar Hanging Brazier",
  "Blackrock Bunkbed": "黑石双层床",
  "Blackrock Strongbox": "黑石保险箱",
  "Orgrimmar Sconce": "奥格瑞玛灯台",
  "Horde Battle Emblem": "部落战争纹章",
  "Blackrock Weapon Rack": "Blackrock Weapon Rack",
  "Orc-Forged Weaponry": "兽人铸造的武器",
  "Elegant Padded Divan": "Elegant Padded Divan",
  "Rectangular Elegant Table": "Rectangular Elegant Table",
  "Warsong Footrest": "战歌搁脚凳",
  "Frostwolf Round Table": "霜狼圆形桌子",
  "Orcish Communal Stove": "兽人公用火炉",
  "Frostwolf Axe-Dart Board": "霜狼飞斧靶",
  "Elegant Almond Table": "Elegant Almond Table",
  "Frostwall Architect's Table": "霜寒晶壁建筑师的桌子",
  "Orcish Warlord's Planning Table": "兽人督军的规划桌",
  "Warsong Workbench": "战歌工作台",
  "Orcish Banded Barrel": "兽人箍边桶",
  "Wine Barrel": "酒桶",
  "Wooden Shipping Crate": "木制船运箱子",
  "Youngling's Courser Toys": "Youngling's Courser Toys",
  "Orcish Lumberjack's Stool": "兽人伐木工的凳子",
  "Frostwolf Banded Stool": "霜狼箍边凳子",
  "Orcish Sleeping Cot": "兽人折叠床",
  "Peon's Work Bucket": "苦工的工作桶",
  "Zuldazar Cook's Griddle": "祖达萨厨师的平底锅",
  "Zandalari Wall Shelf": "赞达拉壁挂架子",
  "Sturdy Wall Rack": "牢固的壁挂架台",
  "Sturdy Fireplace": "牢固的壁炉",
  "Rugged Stool": "粗犷的凳子",
  "Iron Chain Chandelier": "Iron Chain Chandelier",
  "Iron-Reinforced Door": "钢铁加固的门",
  "Tusked Gazebo": "Tusked Gazebo",
  "Nightborne Fireplace": "夜之子壁炉",
  "Orcish Scribe's Drafting Table": "兽人铭文师的绘图桌",
  "Small Purple Suramar Seat Cushion": "小型紫色苏拉玛座椅软垫",
  "Gilnean Circular Rug": "吉尔尼斯圆形毯子",
  "Wide Silvermoon Seat Cushion": "加宽银月城座椅软垫",
  "Small Silvermoon Seat Cushion": "小型银月城座椅软垫",
  "Triangular Silvermoon Seat Cushion": "三角形银月城座椅软垫",
  "Circular Silvermoon Seat Cushion": "原型银月城座椅软垫",
  "Silvermoon Pillow Roll": "银月城滚卷枕头",
  "Tied-Open Leather Curtains": "卷开的皮革窗帘",
  "Closed Leather Curtains": "封闭的皮革窗帘",
  "Leather Valance": "皮革帷幔",
  "Tied-Open Folk Curtains": "卷开的民间窗帘",
  "Closed Folk Curtains": "封闭的民间窗帘",
  "Durable Folk Valance": "耐用的民间帷幔",
  "Restful Wooden Bench": "宁静的木制长椅",
  "Light-Infused Fountain": "光注喷泉",
  "Tiny String of Schmancy Goblin Lights": "微小花哨地精彩灯串",
  "Small String of Schmancy Goblin Lights": "小型花哨地精彩灯串",
  "Drooping String of Schmancy Goblin Lights": "垂挂花哨地精彩灯串",
  "Very Long String of Schmancy Goblin Lights": "很长一条花哨地精彩灯串",
  "Long String of Schmancy Goblin Lights": "长条花哨地精彩灯串",
  "Teal Suramar Seat Cushion": "青色苏拉玛座椅软垫",
  "Purple Suramar Seat Cushion": "紫色苏拉玛座椅软垫",
  "Small Red Suramar Seat Cushion": "小型红色苏拉玛座椅软垫",
  "Surwich Peddler's Wagon": "瑟维奇小贩的货车",
  "Sethraliss Priest's Pillow": "塞塔里斯祭司的枕头",
  "Sethrak Neckroll Pillow": "蛇人靠颈枕头",
  "Circular Elven Table": "Circular Elven Table",
  "Elegant Wall Drape": "Elegant Wall Drape",
  "Elven Floral Window": "Elven Floral Window",
  "Head of the Broodmother": "龙母的徽记",
  "Val'sharah Bookcase": "瓦尔莎拉书柜",
  "Small Val'sharah Bookcase": "小型瓦尔莎拉书柜",
  "Kaldorei Chef's Table": "卡多雷大厨的桌子",
  "Kaldorei Washbasin": "卡多雷脸盆",
  "Zocalo Drinks": "佐卡罗饮料",
  "Round Stitched Cushion": "圆形缝补软垫",
  "Stitched Pillow Roll": "缝合枕卷",
  "Iron-Studded Wooden Window": "Iron-Studded Wooden Window",
  "Charming Seat Cushion": "魅力座椅软垫",
  "Checkered Charming Seat Cushion": "方格型魅力座椅软垫",
  "Thunder Totem Kiln": "雷霆图腾烧窑",
  "Old Salt's Fireplace": "老水手的壁炉",
  "Orgrimmar Chair": "奥格瑞玛椅子",
  "Rugged Brazier": "粗犷火盆",
  "Frostwall Elevated Brazier": "霜寒晶壁架高火盆",
  "Orgrimmar Nightstand": "奥格瑞玛床头柜",
  "Durable Wooden Chest": "耐用的木制箱子",
  "Wide Charming Couch": "加宽魅力沙发",
  "Iron-Reinforced Cupboard": "钢铁加固的橱柜",
  "Trueshot Lodge Fireplace": "神射手营地壁炉",
  "Runed Dreamweaver Moonstone": "符文织梦者月亮石",
  "Worker's Wooden Desk": "工人的木制桌子",
  "Orgrimmar Tusked Bed": "奥格瑞玛獠牙床铺",
  "Iron-Reinforced Standing Mirror": "钢铁加固的落地镜",
  "Shaded Suramar Window": "阴暗的苏拉玛窗户",
  "Elaborate Suramar Window": "精致的苏拉玛窗户",
  "Octagonal Ochre Window": "八边形赭色窗户",
  "Meadery Ochre Window": "酒庄赭色窗户",
  "Ornate Ochre Window": "华丽赭色窗户",
  "Bel'ameth Interior Wall": "贝拉梅斯室内墙壁",
  "Bel'ameth Round Interior Pillar": "贝拉梅斯室内圆形立柱",
  "Bel'ameth Interior Doorway": "贝拉梅斯室内门廊",
  "Bel'ameth Interior Narrow Wall": "贝拉梅斯室内窄墙",
  "Silvermoon Round Interior Pillar": "银月城室内圆形立柱",
  "Silvermoon Interior Narrow Wall": "银月城室内窄墙",
  "Silvermoon Interior Wall": "银月城室内墙壁",
  "Frostwall Forge": "霜寒晶壁熔炉",
  "Ancestral Signal Brazier": "先祖信号火盆",
  "Gilnean Problem Solver": "吉尔尼斯解忧者",
  "Gilnean Noble's Trellis": "吉尔尼斯贵族的篱笆",
  "Arched Rose Trellis": "弯垂玫瑰篱笆",
  "Gilnean Stone Wall": "吉尔尼斯石制墙壁",
  "Bradensbrook Smoke Lantern": "鲑鱼溪缭烟灯笼",
  "Bradensbrook Thorned Well": "鲑鱼溪荆棘水井",
  "Gilnean Stocks": "吉尔尼斯枷锁",
  "Surwich Expedition Tent": "瑟维奇远征帐篷",
  "Little Wolf's Loo": "小狼的厕所",
  "Gilnean Wooden Table": "吉尔尼斯木制桌子",
  "Gilnean Wall Shelf": "吉尔尼斯壁挂架子",
  "Gilnean Rocking Chair": "吉尔尼斯摇椅",
  "Waning Wood Fence": "不牢的木栅栏",
  "Bel'ameth Bench": "贝拉梅斯长椅",
  "Elven Temple Brazier": "精灵神殿火盆",
  "Silvermoon Interior Doorway": "银月城室内门廊",
  "Filigree Moon Lamp": "丝带月之灯笼",
  "Wooden Gazebo": "木制露台",
  "Stonework Fountain": "石制喷泉",
  "Elwynn Cobblestone Round": "艾尔文圆形卵石",
  "Elwynn Cobblestone": "艾尔文卵石",
  "Elwynn Cobblestone Pair": "艾尔文卵石对",
  "Elwynn Cobblestone Cluster": "艾尔文卵石簇",
  "Carved Wooden Bar Table": "雕刻木制酒吧桌",
  "Orgrimmar Bureaucrat's Desk": "奥格瑞玛官员书桌",
  "Tidesage's Fireplace": "海贤壁炉",
  "Shala'nir Feather Bed": "沙拉尼尔羽毛床铺",
  "Kaldorei Stone Fence": "卡多雷石制围栏",
  "Kaldorei Stone Fencepost": "卡多雷石制围栏桩",
  "Kaldorei Cushioned Seat": "卡多雷软垫座椅",
  "Elven Round Table": "精灵圆形桌子",
  "Kaldorei Wall Shelf": "卡多雷壁挂架子",
  "Kaldorei Treasure Trove": "卡多雷宝库",
  "Bel'ameth Barrel": "贝拉梅斯桶",
  "Crescent Moon Lamppost": "新月路灯",
  "Overgrown Arathi Trellis": "蔓生的阿拉希篱笆",
  "Void-Corrupted Fountain": "虚空腐化的喷泉",
  "Sagehold Window": "贤者要塞窗户",
  "Orange Suramar Seat Cushion": "橙色苏拉玛座椅软垫",
  "Red Suramar Seat Cushion": "红色苏拉玛座椅软垫",
  "High-Backed Orgrimmar Chair": "高背奥格瑞玛椅子",
  "Iron-Reinforced Wooden Rack": "钢铁加固的木制架台",
  "Stitched Leather Rug": "缝补皮革毯子",
  "Schmancy Goblin String Lights": "花哨地精彩灯串",
  "Bel'ameth Wooden Table": "贝拉梅斯木制桌子",
  "Bel'ameth Crafter's Tent": "贝拉梅斯工匠帐篷",
  "Small Bel'ameth Tent": "小型贝拉梅斯帐篷",
  "Small Wooden Stool": "小型木制凳子",
  "Large Covered Wooden Table": "大型遮盖的木制桌子",
  "Small Wooden Nightstand": "小型木制床头柜",
  "Carved Wooden Crate": "雕刻木制箱子",
  "Sturdy Weapon Rack": "牢固的武器架",
  "Wooden Chamberstick": "木制手持烛台",
  "Large Sturdy Wooden Table": "大型牢固的木制桌子",
  "Embellished Dwarven Tome": "装饰的矮人之书",
  "Open Carved Wooden Crate": "打开的雕刻木制箱子",
  "Filigree Moon Sconce": "丝带月之灯台",
  "Shadowforge Sconce": "暗炉灯台",
  "Sprouting Lamppost": "萌芽的路灯",
  "Short Orgrimmar Bench": "短款奥格瑞玛长椅",
  "Iron-Reinforced Crate": "钢铁加固的箱子",
  "Weather-Treated Wooden Table": "防护处理的木制桌子",
  "Leather-Banded Wooden Bench": "蒙皮木制长椅",
  "Boralus String Lights": "伯拉勒斯串灯",
  "Cozy Hide-Covered Bench": "铺着毛皮的舒适长椅",
  "Large Orgrimmar Bookcase": "大型奥格瑞玛书柜",
  "Small Leather Rug": "小型皮革毯子",
  "Stormwind Beam Platform": "Stormwind Beam Platform",
  "Stormwind Round Platform": "Stormwind Round Platform",
  "Stormwind Large Platform": "Stormwind Large Platform",
  "Stormwind Small Platform": "Stormwind Small Platform",
  "Stormwind Angled Platform": "Stormwind Angled Platform",
  "Silvermoon Beam Platform": "Silvermoon Beam Platform",
  "Silvermoon Large Platform": "Silvermoon Large Platform",
  "Silvermoon Small Platform": "Silvermoon Small Platform",
  "Silvermoon Angled Platform": "Silvermoon Angled Platform",
  "Silvermoon Round Platform": "Silvermoon Round Platform",
  "Bel'ameth Beam Platform": "Bel'ameth Beam Platform",
  "Bel'ameth Large Platform": "Bel'ameth Large Platform",
  "Bel'ameth Small Platform": "Bel'ameth Small Platform",
  "Bel'ameth Angled Platform": "Bel'ameth Angled Platform",
  "Bel'ameth Round Platform": "Bel'ameth Round Platform",
  "Orgrimmar Beam Platform": "Orgrimmar Beam Platform",
  "Orgrimmar Round Platform": "Orgrimmar Round Platform",
  "Orgrimmar Large Platform": "Orgrimmar Large Platform",
  "Orgrimmar Small Platform": "Orgrimmar Small Platform",
  "Orgrimmar Angled Platform": "Orgrimmar Angled Platform",
  "Shadowforge Grinding Wheel": "暗炉砂轮",
  "Dark Iron Table Saw": "黑铁台锯",
  "Ironforge Bookcase": "铁炉堡书柜",
  "Small Ironforge Bookcase": "小型铁炉堡书柜",
  "Blackrock Lamppost": "黑石路灯",
  "Light-Infused Rotunda": "光注圆台",
  "Kharanos Bookcase": "卡拉诺斯书柜",
  "Stolen Ironforge Seat": "Stolen Ironforge Seat",
  "Thelsamar Hanging Lantern": "Thelsamar Hanging Lantern",
  "Wooden Ironforge Table": "铁炉堡木制桌子",
  "Square Stormpike Table": "Square Stormpike Table",
  "Round Dwarven Table": "原型矮人桌子",
  "Ornate Ironforge Table": "华丽的铁炉堡桌子",
  "Dilapidated Wildhammer Well": "破旧的蛮锤水井",
  "Overgrown Wildhammer Fountain": "蔓生的蛮锤喷泉",
  "Dark Iron Chandelier": "黑铁吊灯",
  "Elegant Tied Curtain": "Elegant Tied Curtain",
  "Ambient Aethercharged Crystal": "Ambient Aethercharged Crystal",
  "Gnomish T.O.O.L.B.O.X.": "侏儒工具箱",
  "Automated Gnomeregan Guardian": "自动化诺莫瑞根守护者",
  "Retired Industrial Gnomegrabber": "退役的工业化侏儒抓取者",
  "Mechanical Gnomish Lamppost": "机械化侏儒路灯",
  "Redundant Reclamation Rig": "备用的开垦钻机",
  "Mechagon Hanging Floodlight": "麦卡贡悬挂泛光灯",
  "Mechagnome Sustenance Distribution Station": "机械侏儒维生物资分发站",
  "Gnomish Tesla Mega-Coil": "侏儒超级电磁圈",
  "Gnomish Tesla Coil": "侏儒电磁圈",
  "Ironforge Chandelier": "铁炉堡吊灯",
  "Steel Ironforge Emblem": "钢制铁炉堡纹章",
  "Ironforge Fencepost": "铁炉堡栅栏桩",
  "Ironforge Fence": "铁炉堡栅栏",
  "Small Emergency Warning Lamp": "小型应急警告灯",
  "Emergency Warning Lamp": "应急警告灯",
  "Mechagon Eyelight Lamp": "麦卡贡对目照明灯",
  "Mechagon Miniature Artificial Sun": "麦卡贡微缩人造太阳",
  "Gnomish Safety Flamethrower": "侏儒安保喷火器",
  "Charming Couch": "魅力沙发",
  "Large H.O.M.E. Cog": "大型家居齿轮",
  "Short Orgrimmar Bookcase": "奥格瑞玛矮书柜",
  "Sturdy Wooden Trellis": "牢固的木制篱笆",
  "Gnomish Fencepost": "侏儒栅栏桩",
  "Gnomish Fence": "侏儒栅栏",
  "Perpetual Motion Crate": "永动箱子",
  "Screw-Sealed Stembarrel": "螺丝密封的高脚桶",
  "Self-Sealing Stembarrel": "自行密封的高脚桶",
  "Small Mechanical Crate": "小型机械箱子",
  "Bolt Chair": "螺栓椅子",
  "Small H.O.M.E. Cog": "小型家居齿轮",
  "Gnomish Cog Stack": "侏儒齿轮叠",
  "Deactivated Atomic Recalibrator ": "关闭的原子重校器 ",
  "Mecha-Storage Mecha-Chest": "机械仓储的机械箱子",
  "Mechagon Armory Rack": "麦卡贡军械架",
  "Durable Hex Table": "耐用的妖术桌",
  "Long Leather-Clad Table": "加长覆皮桌子",
  "Orgrimmar Open Dresser": "奥格瑞玛开放式衣柜",
  "Razorwind Standing Mirror": "烈风落地镜",
  "Razorwind Fountain": "烈风喷泉",
  "Logger's Picnic Table": "伐木工的野餐桌",
  "Long Durable Table": "加长耐用桌子",
  "Razorwind Bar Table": "烈风酒吧桌",
  "Open Spiky Banded Barrel": "打开的尖刺箍边桶",
  "Open Iron-Reinforced Crate": "打开的钢铁加固的箱子",
  "Dwarven District Banner": "矮人区旗帜",
  "Grummle Sleeping Bag": "土地精睡袋",
  "Tusked Candleholder": "獠牙秉烛台",
  "Grand Elven Wall Curtain": "Grand Elven Wall Curtain",
  "Gnomish Steam-Powered Bed": "侏儒蒸汽动力床",
  "Gnomish Sprocket Table": "侏儒链齿桌子",
  "Double-Sprocket Table": "双链齿桌子",
  "Caramel Mint Noodle Dish": "焦糖薄荷面",
  "Elegant Dracthyr's Tea Cup": "优雅龙希尔的茶杯",
  "Decorative Cinder Honeypot": "装饰性燧烬蜜罐",
  "Dornic Sliced Mineloaf": "多恩矿石切片",
  "Earthen Hospitality Cheese-Like Brick": "土灵待客奶酪砖",
  "Elegant Pillow Roll": "Elegant Pillow Roll",
  "Grummle Bedroll": "土地精铺盖",
  "Tall Sturdy Wooden Chair": "牢固的木制高椅子",
  "Zangarshroom Patch": "赞加沼泽地面",
  "Arched Wooden Bench": "弯拱木制长椅",
  "Kafa Press": "Kafa Press",
  "Tome of Shadowforge Cunning": "暗炉狡诈之书",
  "Tome of Pandaren Wisdom": "熊猫人睿智之书",
  "Tome of Draenei Faith": "德莱尼信仰之书",
  "Scribe's Working Notes": "铭文师的工作笔记",
  "\"Welcoming Pantry\" Painting": "\"Welcoming Pantry\" Painting",
  "\"Fruit of the Arcan'dor\" Painting": "\"Fruit of the Arcan'dor\" Painting",
  "\"Raising Your Eyes\" Painting": "\"Raising Your Eyes\" Painting",
  "\"Healthy Conjuration\" Painting": "\"Healthy Conjuration\" Painting",
  "\"The Water Lilies\" Painting": "\"The Water Lilies\" Painting",
  "\"Broken Steps\" Painting": "\"Broken Steps\" Painting",
  "\"Through the Portal\" Painting": "\"Through the Portal\" Painting",
  "\"Smiling Suns\" Painting": "\"Smiling Suns\" Painting",
  "\"Shu'halo Perspective\" Painting": "\"Shu'halo Perspective\" Painting",
  "\"Tidesage's Omen\" Painting": "\"Tidesage's Omen\" Painting",
  "\"Fate of All Life\" Painting": "\"Fate of All Life\" Painting",
  "Tome of Forsaken Resilience": "被遗忘者坚毅之书",
  "\"Tea and Sin\" Painting": "\"Tea and Sin\" Painting",
  "\"Light's Vengeance\" Painting": "\"Light's Vengeance\" Painting",
  "Open Tome of the Dragon's Dedication": "翻开的巨龙奉献之书",
  "Tome of the Lost Dragon": "Tome of the Lost Dragon",
  "Tome of Reliquary Insights": "神圣遗物学会洞察之书",
  "Kaheti Scribe's Records": "卡赫提铭文师的档案",
  "Tome of Earthen Directives": "土灵指令之书",
  "Wide Hide-Covered Bench": "铺着毛皮的加宽长椅",
  "Razorwind Wall Mirror": "烈风壁挂镜子",
  "Farmer's Water Trough": "农夫的水槽",
  "Hay-Filled Sturdy Feeding Trough": "填满甘草的牢固喂食槽",
  "Carved Stone Bench": "雕刻石制长椅",
  "Sturdy Brazier": "牢固的火盆",
  "Founder's Point Street Light": "创始者之角街灯",
  "Founder's Point Lamppost": "创始者之角路灯",
  "Sturdy Feeding Trough": "牢固的食槽",
  "Tusked Hanging Sconce": "獠牙悬挂灯台",
  "Horned Banded Barrel": "巨角箍边桶",
  "Open Horned Banded Barrel": "打开的巨角箍边桶",
  "Long Orgrimmar Bench": "加长奥格瑞玛长椅",
  "Crude Banded Crate": "粗制箍边箱",
  "Open Crude Banded Crate": "打开的粗制箍边箱",
  "Small Covered Wooden Table": "小型遮盖的木制桌子",
  "Small Sturdy Wooden Table": "小型牢固的木制桌子",
  "Elegant Seat Cushion": "Elegant Seat Cushion",
  "Mushan Dumpling Stack": "穆山饺子堆",
  "Small Orgrimmar Chair": "小型奥格瑞玛椅子",
  "Drake Kebab Platter": "幼龙串烧拼盘",
  "Roast Riverbeast Platter": "香烤淡水兽拼盘",
  "Valdrakken Blossomfruit Platter": "瓦德拉肯繁华水果拼盘",
  "Bruffalon Rib Platter": "驼牛肋排拼盘",
  "Elegant Carved Door": "Elegant Carved Door",
  "Elven Woodvine Trellis": "Elven Woodvine Trellis",
  "Pandaren Signal Brazier": "熊猫人信号火盆",
  "Pandaren Scholar's Lectern": "熊猫人学者的讲台",
  "Pandaren Scholar's Bookcase": "熊猫人学者的书柜",
  "Jade Temple Incense Burner": "青龙寺焚香炉",
  "Gate of the Apexis": "埃匹希斯之门",
  "Dalaran Pedestal": "达拉然底座",
  "MOTHER's Titanic Brazier": "纯净圣母的泰坦火盆",
  "N'Zoth's Captured Eye": "被捕获的恩佐斯之眼",
  "Lorewalker's Bookcase": "游学者的书柜",
  "Pandaren Pantry": "熊猫人食品柜",
  "Iron Dragonmaw Gate": "Iron Dragonmaw Gate",
  "Pandaren Stone Post": "熊猫人石桩",
  "Pandaren Stone Lamppost": "熊猫人石制路灯",
  "Red Crane Kite": "朱鹤风筝",
  "Hanging Paper Lanterns": "Hanging Paper Lanterns",
  "Lucky Hanging Lantern": "Lucky Hanging Lantern",
  "Halfhill Cookpot": "半山烹饪锅",
  "Paw'don Well": "坡东水井",
  "Lucky Traveler's Bench": "好运旅人的长椅",
  "Jade Temple Dragon Fountain": "青龙寺龙口喷泉",
  "Stormstout Brew Keg": "风暴烈酒陈酿桶",
  "Pandaren Meander Rug": "熊猫人蜿蜒毯子",
  "Kun-Lai Lacquered Rickshaw": "昆莱喷漆人力车",
  "Kotmogu Pedestal": "Kotmogu Pedestal",
  "Kotmogu Orb of Power": "Kotmogu Orb of Power",
  "Timeless Dumpling Cart": "永恒馄饨餐车",
  "Alliance Dueling Flag": "Alliance Dueling Flag",
  "Horde Dueling Flag": "Horde Dueling Flag",
  "Silverwing Sentinels Flag": "Silverwing Sentinels Flag",
  "Warsong Outriders Flag": "Warsong Outriders Flag",
  "Earthcrawl Mine Cart": "地匍矿洞矿车",
  "Deephaul Crystal": "Deephaul Crystal",
  "Deactivated K'areshi Warp Cannon": "关闭的卡雷什迁跃火炮",
  "Pandaren Fireplace": "熊猫人壁炉",
  "Challenger's Dueling Flag": "Challenger's Dueling Flag",
  "Alliance Battlefield Banner": "Alliance Battlefield Banner",
  "Fortified Alliance Banner": "Fortified Alliance Banner",
  "Horde Battlefield Banner": "Horde Battlefield Banner",
  "Fortified Horde Banner": "Fortified Horde Banner",
  "Uncontested Battlefield Banner": "Uncontested Battlefield Banner",
  "Netherstorm Battlefield Flag": "Netherstorm Battlefield Flag",
  "Berserker's Empowerment": "Berserker's Empowerment",
  "Enigmatic Purple Crystal": "神秘的紫水晶",
  "Healer's Empowerment": "Healer's Empowerment",
  "Runner's Empowerment": "Runner's Empowerment",
  "Wise Pandaren's Bed": "睿智熊猫人的床铺",
  "Guardian's Empowerment": "Guardian's Empowerment",
  "Chaotic Empowerment": "Chaotic Empowerment",
  "Mysterious Empowerment": "Mysterious Empowerment",
  "Zangarmarsh Lamppost": "Zangarmarsh Lamppost",
  "Small Zangarshroom Patch": "Small Zangarshroom Patch",
  "Sturdy Zangarshelf": "Sturdy Zangarshelf",
  "Orange Zangarmarsh Tree": "Orange Zangarmarsh Tree",
  "Glowing Zangarshroom Bowl": "Glowing Zangarshroom Bowl",
  "Glowing Zangarshroom Cup": "Glowing Zangarshroom Cup",
  "Blue Zangarmarsh Tree": "Blue Zangarmarsh Tree",
  "Green Zangarmarsh Tree": "Green Zangarmarsh Tree",
  "Purple Zangarmarsh Tree": "Purple Zangarmarsh Tree",
  "Withered Zangarmarsh Tree": "Withered Zangarmarsh Tree",
  "Glowing Withered Zangarmarsh Tree": "Glowing Withered Zangarmarsh Tree",
  "Pulsing Zangarshroom": "Pulsing Zangarshroom",
  "Orange Spore Light": "Orange Spore Light",
  "Yellow Spore Light": "Yellow Spore Light",
  "Nightborne Merchant's Stall": "夜之子商人的摊位",
  "Deluxe Suramar Sleeper": "豪华苏拉玛卧铺",
  "Suramar Library": "苏拉玛图书馆",
  "Nightborne Bench": "夜之子长椅",
  "Arcwine Counter": "魔力酒柜台",
  "Pandaren Lacquered Crate": "熊猫人喷漆箱子",
  "Serenity Peak Tent": "晴日峰帐篷",
  "Shaohao Ceremonial Bell": "少昊仪式大钟",
  "Nightborne Lantern": "夜之子灯笼",
  "Suramar Fencepost": "苏拉玛栅栏桩",
  "Suramar Sconce": "苏拉玛灯台",
  "Shal'dorei Seat": "夏多雷座椅",
  "Large Traditional Shal'dorei Rug": "大型传统夏多雷毯子",
  "Ornate Suramar Table": "华丽苏拉玛桌子",
  "Covered Ornate Suramar Table": "遮盖的华丽苏拉玛桌子",
  "Square Suramar Table": "方形苏拉玛桌子",
  "Covered Square Suramar Table": "遮盖的方形苏拉玛桌子",
  "Covered Small Suramar Table": "遮盖的小型苏拉玛桌子",
  "Nightborne Jeweler's Table": "夜之子珠宝匠的桌子",
  "Traditional Shal'dorei Rug": "传统夏多雷毯子",
  "Circular Shal'dorei Rug": "圆形夏多雷毯子",
  "Nightborne Wall Shelf": "夜之子壁挂架子",
  "Suramar Fence": "苏拉玛栅栏",
  "Suramar Containment Cell": "苏拉玛禁闭室",
  "Suramar Street Light": "苏拉玛街灯",
  "Suramar Storage Crate": "苏拉玛储物箱",
  "Suramar Window": "苏拉玛窗户",
  "Shal'dorei Open-Air Tent": "夏多雷开放式帐篷",
  "Trueshot Skeletal Dragon Trophy": "神射骨龙战利品",
  "Pandaren Target Dummy": "熊猫人目标假人",
  "Traditional Brewfest Stein": "传统美酒节酒杯",
  "Venthyr's Target Dummy": "温西尔的目标假人",
  "Draconic Stone Table": "龙族石制桌子",
  "Pentagonal Stone Table": "五边形石制桌子",
  "Valdrakken Sconce": "瓦德拉肯灯台",
  "Valdrakken Banded Barrel": "瓦德拉肯箍边桶",
  "Valdrakken Storage Crate": "瓦德拉肯储物箱",
  "Long Valdrakken Storage Crate": "加长瓦德拉肯储物箱",
  "Valdrakken Fence": "瓦德拉肯栅栏",
  "Valdrakken Fencepost": "瓦德拉肯栅栏桩",
  "Verdant Valdrakken Vase": "翠绿瓦德拉肯花瓶",
  "Valdrakken Garden Fountain": "瓦德拉肯花园喷泉",
  "Thaldraszus Telescope": "索德拉苏斯望远镜",
  "Draconic Nesting Bed": "龙族栖巢之床",
  "Valdrakken Chandelier": "瓦德拉肯吊灯",
  "Studious Dracthyr's Tomes": "勤奋龙希尔的书籍",
  "Literature of the Blue Dragonflight": "蓝龙军团文学著作",
  "Literature of the Green Dragonflight": "绿龙军团文学著作",
  "Literature of the Red Dragonflight": "红龙军团文学著作",
  "Draconic Circular Rug": "龙族圆形毯子",
  "Non-Fatal One-Armed Bandit": "非致命型号的独臂盗匪",
  "The Great Hoard": "宏伟库门",
  "Portal to Damnation": "诅咒传送门",
  "Razorwind Storage Table": "烈风储物桌",
  "Stormwind Footlocker": "暴风城手提箱",
  "Stormwind Large Wooden Table": "暴风城大型木制桌子",
  "Stormwind Wooden Bench": "暴风城木制长椅",
  "Stormwind Wooden Stool": "暴风城木制凳子",
  "Stormwind Wooden Table": "暴风城木制桌子",
  "Round-Top Boulder": "圆顶巨石",
  "Flat Boulder": "平整巨石",
  "Hilltop Boulder": "山顶巨石",
  "Founder's Point Signpost": "创始者之角指示牌",
  "Ornamental Kaldorei Glaive": "纹饰卡多雷战刃",
  "Grummle Kafa Refinery": "Grummle Kafa Refinery",
  "Grummle Tent": "Grummle Tent",
  "Kafa Creamer": "Kafa Creamer",
  "Legerdemain Lounge Sign Board": "Legerdemain Lounge Sign Board",
  "Dalaran Kafa Table": "Dalaran Kafa Table",
  "Stormwind Keg Stand": "暴风城桶架",
  "Westfall Woven Basket": "西部荒野手编篮子",
  "Stormwind Gazebo": "暴风城露台",
  "Stormwind Trellis and Basin": "暴风城篱笆与洗涤槽",
  "Stormwind Arched Trellis": "暴风城弯拱篱笆",
  "Wooden Outhouse": "木制厕所",
  "Kaldorei Scribe's Shelf": "卡多雷铭文师的架子",
  "Cookout Campfire": "野炊营火",
  "Razorwind Succulent Palm": "烈风多肉棕榈",
  "Razorwind Fighting Cactus": "烈风格斗仙人掌",
  "Razorwind Tumbleweed": "烈风风滚草",
  "Razorwind Palm Tree": "烈风棕榈树",
  "Nagrand Blueberry Bush": "纳格兰蓝莓灌木丛",
  "Barrens Hosta Bush": "贫瘠之地玉簪灌木丛",
  "Azsharan Firespear Tree": "艾萨拉火矛树",
  "Hardy Razorwind Grass Patch": "顽强的烈风草皮",
  "Flowering Durotar Cactus": "开化的杜隆塔尔仙人掌",
  "Razorwind Acacia Tree": "烈风合欢树",
  "Elwynn Whitebrush": "艾尔文白灌木",
  "Razorwind Gobtree": "烈风地精树",
  "Sunset Aster Flowers": "日落紫菀花",
  "Pink Razorwind Paintbrush": "Pink Razorwind Paintbrush",
  "Gloomrose": "幽影玫瑰",
  "Duskberry Bush": "暮莓灌木丛",
  "Duskwood Shadebrush": "暮色森林阴影灌木",
  "Creeping Lattice Ivy": "蔓延的爬架藤蔓",
  "Duskwood Sycamore Shrub": "暮色森林梧桐灌木",
  "Spiritbloom Flower": "精神绽花",
  "Pink Gilnean Rose": "粉红吉尔尼斯玫瑰",
  "Silvermoon Sunrise Bush": "银月城晨曦灌木丛",
  "Founder's Point Blooming Grass Patch": "Founder's Point Blooming Grass Patch",
  "Autumn Leaf Pile": "秋日落叶堆",
  "Young Chestnut Tree": "栗子树苗",
  "Razorwind Flamebrush": "烈风焰灌从",
  "Draconic Memorial Stone": "龙族悼念石",
  "Dragon's Grand Mirror": "巨龙的宏大镜子",
  "Valdrakken Stone Stool": "瓦德拉肯石制凳子",
  "Valdrakken Gilded Throne": "瓦德拉肯鎏金王座",
  "Elegant Dracthyr's Tea Set": "优雅龙希尔的茶具",
  "Dragon's Hoard Chest": "巨龙的囤宝箱",
  "Valdrakken Market Tent": "瓦德拉肯集市帐篷",
  "Elven Wood Crate": "Elven Wood Crate",
  "Stormwind Workbench": "暴风城工作台",
  "Northshire Scribe's Desk": "北郡铭文师的抄写台",
  "Jewelcrafter's Tent": "珠宝匠的帐篷",
  "Wooden Doghouse": "木制狗舍",
  "Alliance Soldier's Bed": "联盟士兵的床铺",
  "Stormwind Peddler's Cart": "暴风城小贩的推车",
  "Relaxing Goblin Beach Chair with Cup Gripper": "配有杯托的休闲地精沙滩椅",
  "Amirdrassil Stool": "阿梅达希尔凳子",
  "Lovely Elven Shelf": "Lovely Elven Shelf",
  "Elwynn Fence": "艾尔文栅栏",
  "Elwynn Fencepost": "艾尔文栅栏桩",
  "Goldshire Food Cart": "闪金镇食品餐车",
  "City Wanderer's Candleholder": "City Wanderer's Candleholder",
  "Northshire Barrel": "北郡桶",
  "Wooden Storage Crate": "木制储物箱",
  "Architect's Drafting Table": "建筑师的绘图桌",
  "Stormwind Weapon Rack": "暴风城武器架",
  "Elwynn Grass Patch": "Elwynn Grass Patch",
  "Elwynn Grass Spread": "Elwynn Grass Spread",
  "Nesingwary Shoveltusk Trophy": "奈辛瓦里的铲齿鹿战利品",
  "Nesingwary Elk Trophy": "奈辛瓦里的雷象战利品",
  "Void-Corrupted Rotunda": "虚空腐化的圆台",
  "Rough Wooden Chair": "粗糙的木制椅子",
  "Elwynn Small Grass Patch": "Elwynn Small Grass Patch",
  "Golden Cloud Serpent Treasure Chest": "金色云端翔龙宝箱",
  "Five Dawns Weapon Rack": "Five Dawns Weapon Rack",
  "Five Dawns Shrine of the Smoking Fish": "五晨寺熏鱼坛",
  "Ironpaw Stew Cart": "铁掌炖菜餐车",
  "Hooded Iron Lantern": "蒙住的铁制灯笼",
  "Stormwind Lamppost": "暴风城路灯",
  "Replica Felblood Altar": "仿制的魔血祭坛",
  "Dreadscar Battle Planning Map": "恐痕作战规划地图",
  "Five Dawns Planning Table": "五晨寺规划桌",
  "Black Harvest Banner": "黑暗收割旗帜",
  "Monastery Gong": "禅院锣鼓",
  "Dreadscar Bookcase": "恐痕书柜",
  "Dreadscar Dais": "恐痕讲台",
  "Tauren Hanging Brazier": "牛头人悬挂火盆",
  "Black Harvest Orrery": "黑暗收割星象仪",
  "Smoke Sconce": "烟雾灯台",
  "Replica Cursed Forge of the Nathrezim": "仿制的纳斯雷兹姆的诅咒熔炉",
  "Replica Forge of Odyn": "仿制的奥丁的熔炉",
  "Illidari Glaiverest": "伊利达雷战刃架台",
  "Skyhold Brazier": "苍穹要塞火盆",
  "Skyhold War Table": "苍穹要塞战时指挥桌",
  "Illidari Banner": "伊利达雷旗帜",
  "Illidari Skull Sentinel": "伊利达雷颅骨哨兵",
  "Valarjar Banner": "瓦拉加尔旗帜",
  "Valarjar Keg of Celebration": "瓦拉加尔庆典酒桶",
  "Valarjar Shield Wall": "瓦拉加尔盾墙",
  "Fel Hammer Scouting Map": "邪能之槌号侦察地图",
  "Preserver's Censer": "恩护师的香炉",
  "Dracthyr Weapon Rack": "龙希尔武器架",
  "Evoker's Elegant Rug": "唤魔师的优雅毯子",
  "Augmenter's Opal Banner": "增辉师的蛋白石旗帜",
  "Draconic Crafter's Table": "龙族工匠的桌子",
  "Wind Rider Roost": "驭风者栖木",
  "Skyhold Spear Rack": "苍穹要塞矛架",
  "Elven Standing Mirror": "Elven Standing Mirror",
  "Replica Tome of Fel Secrets": "仿制的邪魔之秘魔典",
  "Founder's Point Street Sign": "创始者之角街道标牌",
  "Founder's Point Navigation Sign": "创始者之角导航标牌",
  "Devastator's Brazier": "湮灭师的火盆",
  "Small Wooden Footstool": "小型木制脚凳",
  "Tusked Weapon Rack": "Tusked Weapon Rack",
  "Empty Orgrimmar Bathtub": "奥格瑞玛空浴盆",
  "Runed Stone Placard": "符文石制铭牌",
  "Trueshot Lodge Weapon Rack": "神射手营地武器架",
  "Replica Tome of the Ancients": "仿制的古树宝典",
  "Ebon Blade Planning Map": "黑锋规划地图",
  "Ebon Blade Tome": "黑锋宝典",
  "Acherus Worktable": "阿彻鲁斯工作台",
  "Ebon Blade Weapon Rack": "黑锋武器架",
  "\"Autumn's Eternal Bliss\" Painting": "\"Autumn's Eternal Bliss\" Painting",
  "\"Heart of Quel'Thalas\" Painting": "\"Heart of Quel'Thalas\" Painting",
  "\"Citadel of Unending Void\" Painting": "\"Citadel of Unending Void\" Painting",
  "\"Forest's Bulwark\" Painting": "\"Forest's Bulwark\" Painting",
  "\"The Verdant Underwild\" Painting": "\"The Verdant Underwild\" Painting",
  "Replica Acherus Soul Forge": "仿制的阿彻鲁斯灵魂熔炉",
  "Ebon Blade Banner": "黑锋旗帜",
  "Replica Altar of the Eternal Hunt": "仿制的永恒狩猎祭坛",
  "Unseen Path Archer's Gallery": "隐秘通途射手画廊",
  "Replica Tales of the Hunt": "仿制的狩猎传说",
  "Banner of the Unseen Path": "隐秘通途旗帜",
  "Tirisgarde Candle": "提瑞斯秘法会蜡烛",
  "Tirisgarde War Map": "提瑞斯秘法会战争地图",
  "Tirisgarde Brazier": "提瑞斯秘法会火盆",
  "Dreamweaver Banner": "织梦者旗帜",
  "Seed of Ages Cutting": "纪元之种插枝",
  "Replica Altar of Ancient Kings": "仿制的远古列王祭坛",
  "Silver Hand Banner": "白银之手旗帜",
  "Sanctum of Light Hallway Rug": "圣光秘殿走廊地毯",
  "Replica Libram of Ancient Kings": "仿制的远古列王圣契",
  "Sanctum of Light Candelabra": "圣光秘殿大烛台",
  "Silver Hand Tribute to the Fallen": "白银之手追思供品",
  "Silver Hand Weapon Rack": "白银之手武器架",
  "Tirisgarde Banner": "提瑞斯秘法会旗帜",
  "Founder's Point Gravestone": "创始者之角墓碑",
  "Small Founder's Point Gravestone": "小型创始者之角墓碑",
  "Founder's Point Gravestone Tower": "创始者之角墓碑塔",
  "Large Founder's Point Gravestone": "大型创始者之角墓碑",
  "Netherlight Conclave Voidwell": "虚空之光教团的虚空之泉",
  "Conclave Pedestal": "教团底座",
  "Netherlight Lightwell": "虚空之光的光明之泉",
  "Conjured Altar of the Guardian": "召唤的守护者祭坛",
  "Forbidden Fork": "Forbidden Fork",
  "Tusked Leather Tapestry": "獠牙皮革挂毯",
  "Razorwind Trophy Pelt": "烈风战利品毛皮",
  "Draconic Metalshaper's Anvil": "Draconic Metalshaper's Anvil",
  "Replica Grathardormu's Hammer": "Replica Grathardormu's Hammer",
  "Green Thumb's Watering Can": "Green Thumb's Watering Can",
  "Draconic Auctioneer's Lectern": "Draconic Auctioneer's Lectern",
  "Obsidian Warder Pennant": "Obsidian Warder Pennant",
  "Dark Talon Pennant": "Dark Talon Pennant",
  "Roasted Ram Leg": "Roasted Ram Leg",
  "Draconic Trader's Cart": "Draconic Trader's Cart",
  "Artisan's Measuring Scales": "Artisan's Measuring Scales",
  "War Creche Teaching Crystal": "War Creche Teaching Crystal",
  "Ancient Weyrn Device": "Ancient Weyrn Device",
  "Uncrowned Apothecary's Cabinet": "无冕者药剂师的柜子",
  "Uncrowned Apothecary's Supplies": "无冕者药剂师的补给",
  "Uncrowned Banner": "无冕者旗帜",
  "Uncrowned Planning Table": "无冕者规划桌",
  "Replica Crucible of the Uncrowned": "仿制的无冕者锻炉",
  "Stolen Copy of the Blood Ledger": "偷来的血腥帐簿副本",
  "Netherlight Conclave Banner": "虚空之光教团旗帜",
  "Replica Altar of Light and Shadow": "仿制的光影祭坛",
  "Replica Word of the Conclave": "仿制的教团箴言",
  "Scroll of the Conclave": "教团卷轴",
  "Draconic Crafter's Forge": "龙族工匠的熔炉",
  "Small Razorwind Bar Table": "小型烈风酒吧桌",
  "Elemental Altar of the Maelstrom": "大漩涡的元素祭坛",
  "Replica Words of Wind and Earth": "仿制的风与地之书",
  "Pedestal of the Maelstrom's Wisdom": "大漩涡智慧座台",
  "Farseer's Furs": "先知的毛皮",
  "Maelstrom Banner": "大漩涡旗帜",
  "Horned Hanging Sconce": "犄角悬挂灯台",
  "Painted Wood Scraps": "彩绘碎木",
  "Painted Wood Scrap Pile": "彩绘碎木堆",
  "Cenarion Arch": "塞纳里奥圆拱",
  "Earthen Ring Scouting Map": "大地之环侦察地图",
  "Maelstrom Chimes": "大漩涡风铃",
  "Bel'ameth Traveler's Pack": "贝拉梅斯旅行者的包裹",
  "Shadowmoon Open-Air Shed": "影月开放式棚屋",
  "Draenic Fencepost": "德莱尼栅栏桩",
  "Draenic Ottoman": "德莱尼搁脚凳",
  "Pandaren Wooden Cart": "Pandaren Wooden Cart",
  "Commander's Kafa Mug": "Commander's Kafa Mug",
  "Ceramic Kafa Mug": "Ceramic Kafa Mug",
  "Dalaran Kafa Grinder": "Dalaran Kafa Grinder",
  "Embroidered Embaari Tent": "镶边安波里帐篷",
  "Draenic Wooden Table": "德莱尼木制桌子",
  "Square Draenic Table": "方形德莱尼桌子",
  "Shadowmoon Greenhouse": "影月温室",
  "Draenic Wooden Wall Shelf": "德莱尼木制壁挂架子",
  "Elodor Armory Rack": "艾洛多尔军械架",
  "Draenei Stargazer's Telescope": "德莱尼观星者的望远镜",
  "Draenethyst Lantern": "德拉诺水晶灯笼",
  "\"Dawning Hope\" Mosaic": "\"Dawning Hope\" Mosaic",
  "Small Karabor Fountain": "小型卡拉波喷泉",
  "Moon-Blessed Barrel": "月福之桶",
  "Draenic Basin": "德莱尼盆子",
  "Telredor Recliner": "泰雷多尔躺椅",
  "Razorwind Cooking Grill": "烈风烹饪烤架",
  "Argussian Circular Rug": "阿古斯原型毯子",
  "Draenei Farmer's Trellis": "德莱尼农夫的篱笆",
  "Draenic Fence": "德莱尼栅栏",
  "Emblem of the Naaru's Blessing": "纳鲁祝福纹章",
  "Draenethyst Sconce": "德拉诺水晶灯台",
  "Grand Draenethyst Lamp": "大型德拉诺水晶灯具",
  "Netherlight Command Map": "虚空之光指挥地图",
  "Tusked Weapon Stand": "獠牙武器架",
  "Jagged Orgrimmar Trellis": "锯齿奥格瑞玛栅栏",
  "Hide-Covered Bench": "铺着毛皮的长椅",
  "Draenic Forge": "德莱尼熔炉",
  "Draenethyst Lamppost": "德拉诺水晶路灯",
  "Large Karabor Fountain": "大型卡拉波喷泉",
  "Draenethyst String Lights": "德拉诺水晶串灯",
  "Test Decor": "Test Decor",
  "Hide-Covered Wall Shelf": "铺着毛皮壁挂架子",
  "Tusked Chandelier": "獠牙吊灯",
  "Tusked Sconce": "獠牙灯台",
  "Wolf Pelt Rug": "狼裘毯",
  "Elegant Elven Chandelier": "Elegant Elven Chandelier",
  "Wooden Planter Pot": "Wooden Planter Pot",
  "Wooden Planter Row": "Wooden Planter Row",
  "Founder's Point Fence": "Founder's Point Fence",
  "Long Founder's Point Fence": "Long Founder's Point Fence",
  "Razorwind Wheelbarrow": "Razorwind Wheelbarrow",
  "Ornate Ironforge Bench": "华丽的铁炉堡长椅",
  "Boralus Barrel": "伯拉勒斯桶",
  "Tidesage's Bookcase": "海贤书柜",
  "Covered Wooden Desk": "Covered Wooden Desk",
  "Sturdy Wooden Desk": "Sturdy Wooden Desk",
  "Open Sack of Roasted Kafa": "Open Sack of Roasted Kafa",
  "Sealed Sack of Roasted Kafa": "Sealed Sack of Roasted Kafa",
  "Dalaran Espresso Machine": "Dalaran Espresso Machine",
  "Admiralty's Upholstered Chair": "海军部的软垫座椅",
  "Boralus Fence": "伯拉勒斯栅栏",
  "Boralus Fencepost": "伯拉勒斯栅栏桩",
  "Proudmoore Shipping Crate": "普罗德摩尔货运箱",
  "Small Hull'n'Home Table": "小型船壳为家桌子",
  "Large Hull'n'Home Table": "大型船壳为家桌子",
  "Admiral's Chandelier": "海军统帅的吊灯",
  "Hull'n'Home Dresser": "船壳为家衣柜",
  "Bowhull Bookcase": "船艏书柜",
  "Brennadam Coop": "布伦纳丹鸡窝",
  "Admiralty's Copper Lantern": "海军部的青铜灯笼",
  "Brennadam Grinder": "布伦纳丹绞肉机",
  "Stormsong Water Pump": "斯托颂水泵",
  "Stormsong Stove": "斯托颂炉子",
  "Tiragarde Emblem": "提拉加德纹章",
  "Boralus Bookshelf": "伯拉勒斯书架",
  "Tidesage's Double Bookshelves": "海贤的双面书柜",
  "Admiral's Bed": "海军统帅的床",
  "Hull'n'Home Chair": "船壳为家椅子",
  "Admiral's Low-Hanging Chandelier": "海军统帅的低垂吊灯",
  "Green Boralus Market Tent": "绿色伯拉勒斯集市帐篷",
  "Founder's Point Framed Torch": "Founder's Point Framed Torch",
  "Long Old Founder's Point Fence": "Long Old Founder's Point Fence",
  "Old Founder's Point Fence": "Old Founder's Point Fence",
  "Founder's Point Fencepost": "Founder's Point Fencepost",
  "Old Founder's Point Fencepost": "Old Founder's Point Fencepost",
  "Founder's Point Waterwheel": "Founder's Point Waterwheel",
  "Broken Founder's Point Fence": "Broken Founder's Point Fence",
  "Old Broken Founder's Point Fence": "Old Broken Founder's Point Fence",
  "Plush Cushioned Chair": "绒毛衬垫椅子",
  "Copper Stormsong Well": "青铜斯托颂水晶",
  "Tiragarde Treasure Chest": "提拉加德藏宝箱",
  "Proudmoore Green Drape": "普罗德摩尔绿色窗帘",
  "Copper Tidesage's Sconce": "青铜海贤灯台",
  "Tied-Right Leather Curtains": "紧缚的皮革窗帘",
  "Founder's Point Front Door": "Founder's Point Front Door",
  "\"The High Exarch\" Painting": "\"The High Exarch\" Painting",
  "\"The Ranger of the Void\" Painting": "\"The Ranger of the Void\" Painting",
  "\"The Harbinger\" Painting": "\"The Harbinger\" Painting",
  "\"The Redeemer\" Painting": "\"The Redeemer\" Painting",
  "Seaworthy Boralus Bell": "适航伯拉勒斯船钟",
  "Dornogal Framed Rug": "多恩诺嘉尔框饰地毯",
  "Stonelight Countertop": "石光柜台",
  "Boulder Springs Recliner": "硌石之泉躺椅",
  "Boulder Springs Hot Tub": "硌石之泉澡盆",
  "Founder's Point Standing Torch": "Founder's Point Standing Torch",
  "Razorwind Banded Planter": "Razorwind Banded Planter",
  "Earthen Etched Throne": "土灵蚀刻王座",
  "Freywold Bench": "芙原长椅",
  "Dornogal Bookcase": "多恩诺嘉尔书柜",
  "Rambleshire Resting Platform": "漫林郡休息台",
  "Fallside Lantern": "Fallside Lantern",
  "Freywold Seat": "芙原座椅",
  "Freywold Table": "芙原桌子",
  "Dornogal Brazier": "多恩诺嘉尔火盆",
  "Dornogal Hanging Lantern": "多恩诺嘉尔悬挂灯笼",
  "Dornogal Hanging Sconce": "多恩诺嘉尔悬挂灯台",
  "Coreway Sentinel Lamppost": "心核隧途哨兵路灯",
  "Earthen Chain Wall Shelf": "Earthen Chain Wall Shelf",
  "Fallside Storage Tent": "Fallside Storage Tent",
  "Algari Fence": "Algari Fence",
  "Algari Fencepost": "Algari Fencepost",
  "Freywold Fountain": "Freywold Fountain",
  "Forgeground Market Bins": "Forgeground Market Bins",
  "Earthen Storage Crate": "Earthen Storage Crate",
  "Meadery Storage Chest": "Meadery Storage Chest",
  "Earthen Contender's Target": "Earthen Contender's Target",
  "Replica Awakening Machine Stasis Pod": "Replica Awakening Machine Stasis Pod",
  "Gundargaz Grand Keg": "Gundargaz Grand Keg",
  "Meadery Storage Barrel": "Meadery Storage Barrel",
  "Dried Gilnean Roses": "Dried Gilnean Roses",
  "Hyjal Climbing Vine": "Hyjal Climbing Vine",
  "Ancient Zandalari Ritual Scroll": "Ancient Zandalari Ritual Scroll",
  "Pylon Fragment": "Pylon Fragment",
  "Inactive Filigree Moon Lamp": "Inactive Filigree Moon Lamp",
  "Ornamental Proudmoore Anchor": "Ornamental Proudmoore Anchor",
  "Elegant Elven Canopy Bed": "Elegant Elven Canopy Bed",
  "Gemmed Elven Chest": "Gemmed Elven Chest",
  "Reliquary Tent": "Reliquary Tent",
  "Horde Warlord's Throne": "Horde Warlord's Throne",
  "Bel'ameth Front Door": "Bel'ameth Front Door",
  "Tirisfal Hollow Campfire": "Tirisfal Hollow Campfire",
  "Blightfire Candle": "Blightfire Candle",
  "Replica Rumbling Wastes Drill Pod": "Replica Rumbling Wastes Drill Pod",
  "Gundargaz Candelabra": "Gundargaz Candelabra",
  "Thalassian Chest": "Thalassian Chest",
  "Astalor's Hookah": "Astalor's Hookah",
  "590 Quel'Lithien Red Display Bottle": "590 Quel'Lithien Red Display Bottle",
  "Thalassion Academy Dictation Device": "Thalassion Academy Dictation Device",
  "Sin'dorei Wine Display": "Sin'dorei Wine Display",
  "Goldshire Wardrobe": "Goldshire Wardrobe",
  "Iskaaran Open-Air Tent": "Iskaaran Open-Air Tent",
  "Iskaaran Smith's Anvil": "Iskaaran Smith's Anvil",
  "Iskaaran Cookpot": "Iskaaran Cookpot",
  "Iskaaran Hanging Lampfish": "Iskaaran Hanging Lampfish",
  "Iskaaran Hanging Lantern": "Iskaaran Hanging Lantern",
  "Iskaaran Standing Lantern": "Iskaaran Standing Lantern",
  "Tuskarr Meditative Incense Burner": "Tuskarr Meditative Incense Burner",
  "Tuskarr Crabber's Basket": "Tuskarr Crabber's Basket",
  "Fur-Adorned Iskaaran Worktable": "Fur-Adorned Iskaaran Worktable",
  "Tuskarr Postbag": "Tuskarr Postbag",
  "Finned Iskaaran Teapot": "Finned Iskaaran Teapot",
  "Iskaaran Charcuterie Board": "Iskaaran Charcuterie Board",
  "Big Kinook's Legendary Soup Pot": "Big Kinook's Legendary Soup Pot",
  "Arch of Iskaara": "Arch of Iskaara",
  "Scarred Orcish Spear": "Scarred Orcish Spear",
  "Clefthoof Hide Rug": "Clefthoof Hide Rug",
  "Weathered History of the Warchiefs": "Weathered History of the Warchiefs",
  "Short Wooden Cabinet": "Short Wooden Cabinet",
  "Coal-Fired Stovetop": "Coal-Fired Stovetop",
  "Sturdy Wooden Washbasin": "Sturdy Wooden Washbasin",
  "Sturdy Wooden Bathtub": "Sturdy Wooden Bathtub",
  "Banner of the Ebon Blade": "Banner of the Ebon Blade",
  "Artisanal Display Tent": "Artisanal Display Tent",
  "Eversong Crystal Glass": "Eversong Crystal Glass",
  "590 Quel'Lithien Red": "590 Quel'Lithien Red",
  "\"Silvermoon in Summer\" Painting": "\"Silvermoon in Summer\" Painting",
  "\"The Last Day of the Semester\" Painting": "\"The Last Day of the Semester\" Painting",
  "\"A Bridge Over Calm Waters\" Painting": "\"A Bridge Over Calm Waters\" Painting",
  "\"Family Portrait\" Painting": "\"Family Portrait\" Painting",
  "\"Brunch and a Book\" Unframed Painting": "\"Brunch and a Book\" Unframed Painting",
  "\"Eversong in Bloom\" Painting": "\"Eversong in Bloom\" Painting",
  "\"Nature's Strength\" Painting": "\"Nature's Strength\" Painting",
  "\"River's Protectors\" Unframed Painting": "\"River's Protectors\" Unframed Painting",
  "\"Isolation\" Unframed Painting": "\"Isolation\" Unframed Painting",
  "\"The Fallen Protectors\" Unframed Painting": "\"The Fallen Protectors\" Unframed Painting",
  "\"Autumnal Eversong\" Unframed Painting": "\"Autumnal Eversong\" Unframed Painting",
  "\"Reclamation\" Unframed Painting": "\"Reclamation\" Unframed Painting",
  "\"Brunch and a Book\" Painting": "\"Brunch and a Book\" Painting",
  "\"Autumnal Eversong\" Painting": "\"Autumnal Eversong\" Painting",
  "\"Isolation\" Painting": "\"Isolation\" Painting",
  "\"Reclamation\" Painting": "\"Reclamation\" Painting",
  "\"The Light Blooms\" Painting": "\"The Light Blooms\" Painting",
  "\"The Fallen Protectors\" Painting": "\"The Fallen Protectors\" Painting",
  "\"River's Protectors\" Painting": "\"River's Protectors\" Painting",
  "Sandy Vulpera Banner": "Sandy Vulpera Banner",
  "Fresh Canvas": "Fresh Canvas",
  "\"The Light Blooms\" Unframed Painting": "\"The Light Blooms\" Unframed Painting",
  "Small Orgrimmar Tusked Bed": "Small Orgrimmar Tusked Bed",
  "Razorwind Smith's Hammer": "Razorwind Smith's Hammer",
  "Razorwind Miner's Pickaxe": "Razorwind Miner's Pickaxe",
  "Razorwind Woodworker's Hand Saw": "Razorwind Woodworker's Hand Saw",
  "Razorwind Crafter's Chisel": "Razorwind Crafter's Chisel",
  "Razorwind Peon's Shovel": "Razorwind Peon's Shovel",
  "Triple-Tested Steam Valve": "Triple-Tested Steam Valve",
  "Mad Science Blueprints": "Mad Science Blueprints",
  "Safety Electrical Cabling": "Safety Electrical Cabling",
  "Mechagon Control Console": "Mechagon Control Console",
  "Sticky Lever": "Sticky Lever",
  "Dual-Action Turbo Pro Lever": "Dual-Action Turbo Pro Lever",
  "Mechanical Gauge": "Mechanical Gauge",
  "Dual Mechanical Gauge": "Dual Mechanical Gauge",
  "Lively Pistons": "Lively Pistons",
  "Sturdy Drive Belt": "Sturdy Drive Belt",
  "Blue-Glo Lantern": "Blue-Glo Lantern",
  "Z-205 Mechanical Device": "Z-205 Mechanical Device",
  "Well-Oiled Machine Cog": "Well-Oiled Machine Cog",
  "Jury-Rigged Electrical Couple": "Jury-Rigged Electrical Couple",
  "Miniature Charging Station": "Miniature Charging Station",
  "Galvanic Storage and Maintenance Device": "Galvanic Storage and Maintenance Device",
  "Small Razorwind Square Table": "Small Razorwind Square Table",
  "Razorwind Logger's Axe": "Razorwind Logger's Axe",
  "Ineffective Mechanical Privacy Screen": "Ineffective Mechanical Privacy Screen",
  "Large Razorwind Gazebo": "Large Razorwind Gazebo",
  "Undermine Mechanic's Hanging Lamp": "Undermine Mechanic's Hanging Lamp",
  "Undermine Alleyway Sconce": "Undermine Alleyway Sconce",
  "Silvermoon Barrel": "Silvermoon Barrel",
  "Elwynn Apple Tree": "Elwynn Apple Tree",
  "Founder's Point Apple Tree": "Founder's Point Apple Tree",
  "Spring-Powered Pointer": "Spring-Powered Pointer",
  "Elegant Table Lamp": "Elegant Table Lamp",
  "Gnomish Tesla Tower": "Gnomish Tesla Tower",
  "Moonclasp Satchel": "Moonclasp Satchel",
  "Incontinental Table Lamp": "Incontinental Table Lamp",
  "Razorwind Iron Chandelier": "Razorwind Iron Chandelier",
  "Low-Hanging Razorwind Iron Chandelier": "Low-Hanging Razorwind Iron Chandelier",
  "Small Jagged Orgrimmar Trellis": "Small Jagged Orgrimmar Trellis",
  "Razorwind Shores Canoe": "Razorwind Shores Canoe",
  "Champion Brawler's Gloves": "Champion Brawler's Gloves",
  "Silvermoon Gemmed Chair": "Silvermoon Gemmed Chair",
  "Silvermoon Bench": "Silvermoon Bench",
  "Silvermoon Fencepost": "Silvermoon Fencepost",
  "Sin'dorei Sleeper": "Sin'dorei Sleeper",
  "Razorwind Shores Front Door": "Razorwind Shores Front Door",
  "Draconic Sconce": "Draconic Sconce",
  "Valdrakken Oven": "Valdrakken Oven",
  "Draconic Scribe's Basin": "Draconic Scribe's Basin",
  "Five Flights' Grimoire": "Five Flights' Grimoire",
  "Silvermoon Fence": "Silvermoon Fence",
  "Silvermoon Front Door": "Silvermoon Front Door",
  "Open Rust-Plated Storage Crate": "Open Rust-Plated Storage Crate",
  "Leftover Undermine Takeout": "Leftover Undermine Takeout",
  "Razorwind Standing Tusk": "Razorwind Standing Tusk",
  "Kharanos Stone Bed": "Kharanos Stone Bed",
  "Shadowforge Lamppost": "Shadowforge Lamppost",
  "Ornate Dwarven Wardrobe": "Ornate Dwarven Wardrobe",
  "Qalashi Goulash": "Qalashi Goulash",
  "Sunsmoke Censer": "Sunsmoke Censer",
  "Razorwind Porch Chair": "Razorwind Porch Chair",
  "Shadowforge Stone Chair": "Shadowforge Stone Chair",
  "Wingrest Signal Brazier": "Wingrest Signal Brazier",
  "Valdrakken Hanging Lamp": "Valdrakken Hanging Lamp",
  "Valdrakken Lamppost": "Valdrakken Lamppost",
  "Valdrakken Hanging Cauldron": "Valdrakken Hanging Cauldron",
  "Stormwind Forge": "Stormwind Forge",
  "Conjured Archive of the Tirisgarde": "Conjured Archive of the Tirisgarde",
  "Illidari Tent": "Illidari Tent",
  "Replica Hammer of Khaz'goroth": "Replica Hammer of Khaz'goroth",
  "Replica Chronicle of Ages": "Replica Chronicle of Ages",
  "Arcan'dor Cutting Fountain": "Arcan'dor Cutting Fountain",
  "Nightspire Fountain": "Nightspire Fountain",
  "Magistrix's Garden Fountain": "Magistrix's Garden Fountain",
  "Smoke Lamppost": "Smoke Lamppost",
  "Gilnean Banded Crate": "Gilnean Banded Crate",
  "Small Gilnean Table": "Small Gilnean Table",
  "Replica Tome of Blighted Implements": "Replica Tome of Blighted Implements",
  "Tauren Jeweler's Roller": "Tauren Jeweler's Roller",
  "Tauren Cookpot": "Tauren Cookpot",
  "Zandalari War Chandelier": "Zandalari War Chandelier",
  "Pentagonal Valdrakken Tapestry": "Pentagonal Valdrakken Tapestry",
  "Bronze Banner of the Exiled": "Bronze Banner of the Exiled",
  "Draenei Smith's Anvil": "Draenei Smith's Anvil",
  "Draenei Holo-Dais": "Draenei Holo-Dais",
  "Draenei Holo-Path": "Draenei Holo-Path",
  "Draenei Crystal Forge": "Draenei Crystal Forge",
  "Dalaran Runic Anvil": "Dalaran Runic Anvil",
  "Stoppered Black Potion": "Stoppered Black Potion",
  "Gilnean Pitchfork": "Gilnean Pitchfork",
  "Pandaren Alchemist's Retort": "Pandaren Alchemist's Retort",
  "Orcish Felblood Cauldron": "Orcish Felblood Cauldron",
  "Starry Scrying Pool": "Starry Scrying Pool",
  "Boralus Bottle Lamp": "Boralus Bottle Lamp",
  "Zandalari Bottle Shipment": "Zandalari Bottle Shipment",
  "Aspirant's Meditation Pool": "Aspirant's Meditation Pool",
  "Bejeweled Venthyr Chalice": "Bejeweled Venthyr Chalice",
  "Veil-Secured Animacone": "Veil-Secured Animacone",
  "Sintallow Candles": "Sintallow Candles",
  "Dragon's Elixir Bottle": "Dragon's Elixir Bottle",
  "Tapestry of the Five Flights": "Tapestry of the Five Flights",
  "Aldor Stellar Console": "Aldor Stellar Console",
  "Mark of the Mages' Eye": "Mark of the Mages' Eye",
  "Twilight Fire Canister": "Twilight Fire Canister",
  "Pandaren Table Lamp": "Pandaren Table Lamp",
  "Intense Mogu Brazier": "Intense Mogu Brazier",
  "Venthyr Anima Bottle": "Venthyr Anima Bottle",
  "Razorwind Covered Well": "Razorwind Covered Well",
  "Apothecary's Work Table": "Apothecary's Work Table",
  "Stampwhistle's Postal Portal": "Stampwhistle's Postal Portal",
  "Nerubian Alchemist's Retort": "Nerubian Alchemist's Retort",
  "Naaru Crystal Icon": "Naaru Crystal Icon",
  "Tale of the Penultimate Lich King": "Tale of the Penultimate Lich King",
  "Large Brazier of Elune": "Large Brazier of Elune",
  "Drained Dark Heart of Galakrond": "Drained Dark Heart of Galakrond",
  "Scroll of K'aresh's Fall": "Scroll of K'aresh's Fall",
  "Tome of the Survivor": "Tome of the Survivor",
  "Slate Cobblestone Pair": "Slate Cobblestone Pair",
  "Slate Cobblestone": "Slate Cobblestone",
  "Iron-Reinforced Wooden Window": "Iron-Reinforced Wooden Window",
  "Slate Cobblestone Path": "Slate Cobblestone Path",
  "Slate Cobblestone Trio": "Slate Cobblestone Trio",
  "Suramar Stepping Stone": "Suramar Stepping Stone",
  "Zandalari War Torch": "Zandalari War Torch",
  "Trueshot Lodge Food Nook": "Trueshot Lodge Food Nook",
  "Replica Saga of the Valarjar": "Replica Saga of the Valarjar",
  "Tauren Storyteller's Frame": "Tauren Storyteller's Frame",
  "\"Portrait of the Artist as a Young Goblin\" Painting": "\"Portrait of the Artist as a Young Goblin\" Painting",
  "Zandalari War Brazier": "Zandalari War Brazier",
  "Highmountain Tanner's Frame": "Highmountain Tanner's Frame",
  "Skyhorn Banner": "Skyhorn Banner",
  "\"Unity of Thorns\" Tapestry": "\"Unity of Thorns\" Tapestry",
  "Maelstrom Lava Lamp": "Maelstrom Lava Lamp",
  "Pyrewood Glass Bottle": "Pyrewood Glass Bottle",
  "Baradin Bay Fishing Rack": "Baradin Bay Fishing Rack",
  "Smoke Lamp": "Smoke Lamp",
  "Standing Smoke Lamp": "Standing Smoke Lamp",
  "Stoppered Gilnean Barrel": "Stoppered Gilnean Barrel",
  "Ornate Sin'dorei Sconce": "Ornate Sin'dorei Sconce",
  "Sin'dorei Crafter's Forge": "Sin'dorei Crafter's Forge",
  "Silvermoon Spire Fountain": "Silvermoon Spire Fountain",
  "Bejeweled Silvermoon Chandelier": "Bejeweled Silvermoon Chandelier",
  "Gilded Sunfury Chair": "Gilded Sunfury Chair",
  "\"That Thing What You've Always Needed\" Advertisement": "\"That Thing What You've Always Needed\" Advertisement",
  "Suramar Stepping Stone Set": "Suramar Stepping Stone Set",
  "Small Gilnean Windmill": "Small Gilnean Windmill",
  "Elegant Padded Chaise": "Elegant Padded Chaise",
  "Open Elegant Elven Barrel": "Open Elegant Elven Barrel",
  "Elegant Curved Table": "Elegant Curved Table",
  "Snowfall Tribe Scare-Totem": "Snowfall Tribe Scare-Totem",
  "Gilnean Green Potion": "Gilnean Green Potion",
  "Gilnean Postbox": "Gilnean Postbox",
  "Gilnean Map": "Gilnean Map",
  "Skyhorn Arrow Kite": "Skyhorn Arrow Kite",
  "Hanging Arrow Kite": "Hanging Arrow Kite",
  "Skyhorn Eagle Kite": "Skyhorn Eagle Kite",
  "Highmountain Banner": "Highmountain Banner",
  "Camp Narache Rug": "Camp Narache Rug",
  "Dalaran Kafa Press": "Dalaran Kafa Press",
  "Scaled Twilight Mosaic": "Scaled Twilight Mosaic",
  "Nazjatar Framing Post": "Nazjatar Framing Post",
  "Spirit Anemones": "Spirit Anemones",
  "Elegant Silvermoon Dessert Tray": "Elegant Silvermoon Dessert Tray",
  "Eversong Party Platter": "Eversong Party Platter",
  "Empty Lorewalker's Bookcase": "Empty Lorewalker's Bookcase",
  "Orgrimmar Bathtub": "Orgrimmar Bathtub",
  "Outland Mag'har Banner": "Outland Mag'har Banner",
  "Arakkoa Decoy Scarecrow": "Arakkoa Decoy Scarecrow",
  "Talon King's Totem": "Talon King's Totem",
  "Draenei Holo-Projector Pedestal": "Draenei Holo-Projector Pedestal",
  "Tempest Keep Cryo-Pod": "Tempest Keep Cryo-Pod",
  "Draenei Weaver's Loom": "Draenei Weaver's Loom",
  "Draenei Transmitter": "Draenei Transmitter",
  "Crystal Signpost": "Crystal Signpost",
  "Gilded Draenei Round Table": "Gilded Draenei Round Table",
  "Aldor Bookcase": "Aldor Bookcase",
  "Shattrath Sconce": "Shattrath Sconce",
  "Shattrath Lamppost": "Shattrath Lamppost",
  "Grand Drape of the Exiles": "Grand Drape of the Exiles",
  "Silver Dalaran Bench": "Silver Dalaran Bench",
  "Dalaran Post": "Dalaran Post",
  "Wolvar Postbag": "Wolvar Postbag",
  "Gilded Dalaran Banner": "Gilded Dalaran Banner",
  "Dalaran Scholar's Bookcase": "Dalaran Scholar's Bookcase",
  "Kirin Tor Sun Chandelier": "Kirin Tor Sun Chandelier",
  "Kirin Tor Crate": "Kirin Tor Crate",
  "Dalaran Street Sign": "Dalaran Street Sign",
  "Kirin Tor Glass Table": "Kirin Tor Glass Table",
  "San'layn Blood Orb": "San'layn Blood Orb",
  "Icecrown Plague Canister": "Icecrown Plague Canister",
  "Pandaren Alchemist's Kit": "Pandaren Alchemist's Kit",
  "Halaa Bench": "Halaa Bench",
  "Reconstructed Mogu Lightning Drill": "Reconstructed Mogu Lightning Drill",
  "Driftwood Barrel": "Driftwood Barrel",
  "Murloc Driftwood Hut": "Murloc Driftwood Hut",
  "Driftwood Junk Pile": "Driftwood Junk Pile",
  "Shellscale Standard": "Shellscale Standard",
  "Murloc's Wind Chimes": "Murloc's Wind Chimes",
  "Dalaran Display Shelves": "Dalaran Display Shelves",
  "Failed Failure Detection Pylon": "Failed Failure Detection Pylon",
  "Dalaran Auto-Hammer": "Dalaran Auto-Hammer",
  "Suramar Jeweler's Assortment": "Suramar Jeweler's Assortment",
  "Naga's Scale Bag": "Naga's Scale Bag",
  "Azshara's Eternal Prize": "Azshara's Eternal Prize",
  "Azsharan Brazier": "Azsharan Brazier",
  "Aspiring Soul's Chair": "Aspiring Soul's Chair",
  "Ardenweald Lamppost": "Ardenweald Lamppost",
  "Maldraxxian Crate": "Maldraxxian Crate",
  "Tome of Maldraxxian Rituals": "Tome of Maldraxxian Rituals",
  "Kyrian Anima Barrel": "Kyrian Anima Barrel",
  "Hollow Night Fae Shrine": "Hollow Night Fae Shrine",
  "Broker's Hex Table": "Broker's Hex Table",
  "Ardenweald Hanging Baskets": "Ardenweald Hanging Baskets",
  "Large Revendreth Storage Crate": "Large Revendreth Storage Crate",
  "Margrave's Stitched Leather Rug": "Margrave's Stitched Leather Rug",
  "Cartel Ta Bookcase": "Cartel Ta Bookcase",
  "Cartel Xy Capture Crate": "Cartel Xy Capture Crate",
  "Titanic Tyrhold Fountain": "Titanic Tyrhold Fountain",
  "Kobold Digger's Chair": "Kobold Digger's Chair",
  "Kobold Candle Trio": "Kobold Candle Trio",
  "Kobold Wagon": "Kobold Wagon",
  "Candle-Festooned Wooden Awning": "Candle-Festooned Wooden Awning",
  "Waxmaster's Candle Rack": "Waxmaster's Candle Rack",
  "Thunder Bluff Totem": "Thunder Bluff Totem",
  "Kirin Tor Skyline Banner": "Kirin Tor Skyline Banner",
  "Sparse Razorwind Fisher's Rack": "Sparse Razorwind Fisher's Rack",
  "Gilnean Washing Line": "Gilnean Washing Line",
  "Pandaren Fishing Net": "Pandaren Fishing Net",
  "Beloved Elekk Plushie": "Beloved Elekk Plushie",
  "Flying Skyhorn Eagle Kite": "Flying Skyhorn Eagle Kite",
  "K'areshi Warp Platform": "K'areshi Warp Platform",
  "Razorwind Fisher's Rack": "Razorwind Fisher's Rack",
  "Naakroan Brazier": "Naakroan Brazier",
  "Shadowguard Collection Pylon": "Shadowguard Collection Pylon",
  "K'areshi Protectorate Portal": "K'areshi Protectorate Portal",
  "Shadowguard Energy Siphon": "Shadowguard Energy Siphon",
  "Beloved Raptor Plushie": "Beloved Raptor Plushie",
  "Sandfury Diplomat's Banner": "Sandfury Diplomat's Banner",
  "Tidesage's Totem": "Tidesage's Totem",
  "Drust Enchanter's Rod": "Drust Enchanter's Rod",
  "Kyrian Aspirant's Rolled Cushion": "Kyrian Aspirant's Rolled Cushion",
  "Elwynn Autumn Apple Tree": "Elwynn Autumn Apple Tree",
  "Founder's Point Autumn Apple Tree": "Founder's Point Autumn Apple Tree",
  "Razorwind River Paddle": "Razorwind River Paddle",
  "Tusk-Adorned Stitched Rug": "Tusk-Adorned Stitched Rug",
  "Small Stitched Rug": "Small Stitched Rug",
  "Ethereal Pipe Segment": "Ethereal Pipe Segment",
  "Angled Ethereal Pipe Segment": "Angled Ethereal Pipe Segment",
  "Long Ethereal Pipe Segment": "Long Ethereal Pipe Segment",
  "Corner Ethereal Pipe Segment": "Corner Ethereal Pipe Segment",
  "Empty Wooden Bathtub": "Empty Wooden Bathtub",
  "Glorious Pendant of Rukhmar": "Glorious Pendant of Rukhmar",
  "Writings of Reshad the Outcast": "Writings of Reshad the Outcast",
  "Scroll of the Adherent": "Scroll of the Adherent",
  "Arakkoan Alchemy Tools": "Arakkoan Alchemy Tools",
  "Skyreach Circular Table": "Skyreach Circular Table",
  "High Arakkoan Library Shelf": "High Arakkoan Library Shelf",
  "High Arakkoan Alchemist's Shelf": "High Arakkoan Alchemist's Shelf",
  "High Arakkoan Shelf": "High Arakkoan Shelf",
  "\"Rising Glory of Rukhmar\" Statue": "\"Rising Glory of Rukhmar\" Statue",
  "Uncorrupted Eye of Terokk": "Uncorrupted Eye of Terokk",
  "Hull'n'Home Window": "Hull'n'Home Window",
  "Exposed Corner Ethereal Pipe Segment": "Exposed Corner Ethereal Pipe Segment",
  "Exposed Long Ethereal Pipe Segment": "Exposed Long Ethereal Pipe Segment",
  "Exposed Intersecting Ethereal Pipe Segment": "Exposed Intersecting Ethereal Pipe Segment",
  "Exposed Corner Ethereal Pipe Segment": "Exposed Corner Ethereal Pipe Segment",
  "Exposed Angled Ethereal Pipe Segment": "Exposed Angled Ethereal Pipe Segment",
  "Brawler's Guild Punching Bag": "Brawler's Guild Punching Bag",
  "Rolled Razorwind Leathers": "Rolled Razorwind Leathers",
  "Low-Hanging Razorwind Ropes": "Low-Hanging Razorwind Ropes",
  "Knotted Hanging Razorwind Ropes": "Knotted Hanging Razorwind Ropes",
  "Tusked Hanging Razorwind Ropes": "Tusked Hanging Razorwind Ropes",
  "Plain Hanging Razorwind Ropes": "Plain Hanging Razorwind Ropes",
  "Adorned Hanging Razorwind Ropes": "Adorned Hanging Razorwind Ropes",
  "Lightly Adorned Hanging Razorwind Ropes": "Lightly Adorned Hanging Razorwind Ropes",
  "Valdrakken Bookcase": "Valdrakken Bookcase",
  "Large Razorwind Farmer's Hay Pile": "Large Razorwind Farmer's Hay Pile",
  "Razorwind Farmer's Hay Pile": "Razorwind Farmer's Hay Pile",
  "Small Razorwind Farmer's Hay Pile": "Small Razorwind Farmer's Hay Pile",
  "Brazier of Elune": "Brazier of Elune",
  "Cartel Collector's Cage": "Cartel Collector's Cage",
  "Arathi Bartender's Shelves": "Arathi Bartender's Shelves",
  "Replica Libram of the Dead": "Replica Libram of the Dead",
  "Kobold Trassure Pile": "Kobold Trassure Pile",
  "Maldraxxian Runic Tablet": "Maldraxxian Runic Tablet",
  "Gob-chanical Trash Heap": "Gob-chanical Trash Heap",
  "Red Razorwind Paintbrush": "Red Razorwind Paintbrush",
  "Dry Razorwind Grass Patch": "Dry Razorwind Grass Patch",
  "Uncrowned Market Stall": "Uncrowned Market Stall",
  "Draenei Crystal Chandelier": "Draenei Crystal Chandelier",
  "Leather Haranir Bed": "Leather Haranir Bed",
  "Replica Forge of the Roaring Mountain": "Replica Forge of the Roaring Mountain",
  "Kyrian Floating Lamp": "Kyrian Floating Lamp",
  "Small Telogrus Lamp": "Small Telogrus Lamp",
  "Restful Bronze Bench": "Restful Bronze Bench",
  "Brumewood Hollow Grassy Patch": "Brumewood Hollow Grassy Patch",
  "Brumewood Hollow Grassy Spread": "Brumewood Hollow Grassy Spread",
  "Founder's Point Grassy Patch": "Founder's Point Grassy Patch",
  "Founder's Point Grassy Spread": "Founder's Point Grassy Spread",
  "Sturdy Wine Press": "Sturdy Wine Press",
  "Brawler's Barricade": "Brawler's Barricade",
  "Darkmaster's Mystical Brazier": "Darkmaster's Mystical Brazier",
  
  "All Subcategories": "所有子分类",
  "Floor": "地板",
  "Food and Drink": "食品和饮料",
  "Misc Accents": "装饰杂项",
  "Ornamental": "装饰品",
  "Wall Hangings": "壁挂装饰",
  "Utility": "效能",
  "Beds": "床铺",
  "Misc Furnishings": "家具杂项",
  "Seating": "座椅",
  "Storage": "储物",
  "Tables and Desks": "桌台",
  "Ambient Lighting": "环境照明",
  "Large Lights": "大型灯具",
  "Misc Lighting": "灯具杂项",
  "Small Lights": "小型灯具",
  "Wall Lights": "壁灯",
  "Miscellaneous - All": "全部杂项",
  "Bushes": "灌木",
  "Large Foliage": "大型植物",
  "Small Foliage": "小型植物",
  "Ground Cover": "地被植物",
  "Doors": "门",
  "Large Structures": "大型结构",
  "Misc Structural": "结构杂项",
  "Walls and Columns": "墙壁和柱子",
  "Windows": "窗户",

  "All Categories": "所有分类",
  "Accents": "点缀",
  "Functional": "功能",
  "Furnishing": "家具",
  "Furnishings": "家具",
  "Lighting": "照明",
  "Miscellaneous": "杂项",
  "Nature": "植被",
  "Structural": "构造",

  "Game Object Proxy": "游戏对象代理",
  "Deprecated": "已弃用",
  "Exterior": "室外",
  "HiddenInCatalog": "在目录中隐藏",
  "Interior": "室内",
  "Can't Remove from Chest": "不可自柜中移除",

  "Low": "低",
  "Medium": "中",
  "High": "高",
  "No Budget Cost": "无预算占用",

  "Dyeable": "染色",
  "Dyeable Items Only": "仅可染色物品",

  "Achievement": "成就",
  "Crafting": "专业制造",
  "Quest": "任务",
  "Filter by Profession": "按专业过滤",
  "Alchemy": "炼金",
  "Blacksmithing": "锻造",
  "Cooking": "烹饪",
  "Enchanting": "附魔",
  "Engineering": "工程学",
  "Inscription": "铭文",
  "Jewelcrafting": "珠宝加工",
  "Leatherworking": "制皮",
  "Tailoring": "裁缝",
  "Encounter": "战斗",
  "Vendor": "商人出售",

  "Blood Elf": "血精灵",
  "Zandalari Troll": "赞达拉巨魔",
  "Bronzebeard Dwarf": "铜须部族",
  "Ironforge": "铁炉堡",
  "Dark Iron Dwarf": "黑铁矮人",
  "Dracthyr": "龙希尔",
  "Draenei": "德莱尼",
  "Dwarven": "矮人",
  "Earthen": "土灵",
  "Dornish": "多恩",
  "Elven": "精灵",
  "Gilnean / Worgen": "吉尔尼斯人/狼人",
  "Gnomish": "侏儒",
  "Goblin": "地精",
  "Haranir": "哈籁尼尔",
  "Human": "人类",
  "Kul Tiran": "库尔提拉斯人",
  "Nightborne": "夜之子",
  "Night Elf": "暗夜精灵",
  "Orcish": "兽人",
  "Pandaren": "熊猫人",
  "Tauren": "牛头人",
  "Troll": "巨魔",
  "Undead": "亡灵",
  "Void Elf": "虚空精灵",
  "Wildhammer Dwarf": "蛮锤部族",

  "Battle for Azeroth": "争霸艾泽拉斯",
  "Burning Crusade": "燃烧的远征",
  "Cataclysm": "大地的裂变",
  "Classic": "旧世经典",
  "Dragonflight": "巨龙时代",
  "Legion": "军团再临",
  "Midnight": "至暗之夜",
  "Mists of Pandaria": "熊猫人之谜",
  "Shadowlands": "暗影国度",
  "The War Within": "地心之战",
  "Warlords of Draenor": "德拉诺之王",
  "Wrath of the Lich King": "巫妖王之怒",

  "Brewfest": "美酒节",
  "Feast of Winter Veil": "冬幕节",
  "Hallow's End": "万圣节",
  
  "Stormwind": "暴风城",
  "craft crafting crafted profession": "制造/专业",
  
  "Huge": "巨大",
  "Large": "大",
  "Medium": "中",
  "Small": "小",
  "Tiny": "微小",

  "Alliance": "联盟",
  "Bold": "粗犷",
  "Casual": "休闲",
  "Cute": "可爱",
  "Elegant": "优雅",
  "Fae": "精灵",
  "Fall": "秋季",
  "Fel": "邪能",
  "Horde": "部落",
  "Lavish": "奢华",
  "Light": "圣光",
  "Magical": "魔法",
  "Mechanical": "机械",
  "Nature": "自然",
  "Pirate": "海盗",
  "Simple": "简约",
  "Spooky": "阴森",
  "Spring": "春季",
  "Void": "虚空",
  "Whimsical": "怪诞",

  "art artwork painting canvas": "艺术、艺术品、画作、画布",
  "book books tome tomes": "书、书籍、大部头",
  "cabinet cabinets": "橱柜、柜子",
  "chair chairs": "椅子",
  "column columns pillar pillars post": "柱子、柱、立柱",
  "cook cooking oven stove range grill": "烹饪、烤箱、炉子、炉具、烤架",
  "couch couches sofa sofas": "长沙发、沙发",
  "counter counters countertop countertops": "柜台、台面、操作台",
  "cup cups mug mugs tankard stein": "杯、杯子、马克杯、啤酒杯",
  "desk desks": "书桌、桌子",
  "drink drinks beverage beverages": "饮料",
  "fence fences fencing": "栅栏、围栏",
  "food meal feast snack": "食物、餐、大餐、点心",
  "kitchen": "厨房",
  "partition partitions wall walls": "分隔、隔断、墙",
  "rug rugs": "地毯",
  "shelf shelves shelving": "架子、搁板",
  "table tables": "桌子",
  "vases vase": "花瓶",
  "water pond": "水、池塘",

  "Folk": "民间",
  "Holiday/Event": "节日/活动",
  "Opulent": "奢华",
  "Rugged": "粗犷",
  
  "Build Version": "构建版本",
  "Added In Build": "新增于构建版本",
  "All Build": "全部构建版本",
  
  "Category": "分类",
  "Categories": "分类",
  "Subcategory": "子分类",
  "Flags": "标记",
  "Budget Cost": "预算占用",
  "Sources": "来源",
  "Tags": "标签",
  "Culture": "文化",
  "Expansion": "资料片",
  "Holiday": "节日",
  "Other": "其他",
  "Size": "尺寸",
  "Style": "风格",
  "Tertiary_Categories": "三级分类",
  "Theme": "主题",

  "art artwork painting canvas": "艺术、艺术品、画作、画布",
  "book books tome tomes": "书、书籍、大部头",
  "cabinet cabinets": "橱柜、柜子",
  "chair chairs": "椅子",
  "column columns pillar pillars post": "柱子、柱、立柱",
  "cook cooking oven stove range grill": "烹饪、烤箱、炉子、炉具、烤架",
  "couch couches sofa sofas": "长沙发、沙发",
  "counter counters countertop countertops": "柜台、台面、操作台",
  "cup cups mug mugs tankard stein": "杯、杯子、马克杯、大啤酒杯",
  "desk desks": "书桌、桌子",
  "drink drinks beverage beverages": "饮料",
  "fence fences fencing": "栅栏、围栏",
  "food meal feast snack": "食物、餐、大餐、点心",
  "kitchen": "厨房",
  "partition partitions wall walls": "分隔、隔断、墙",
  "rug rugs": "地毯",
  "shelf shelves shelving": "架子、搁板",
  "table tables": "桌子",
  "vases vase": "花瓶",
  "water pond": "水、池塘",

  "Home": "主页",
  "Tools": "工具",
  "Item Information": "物品信息",
  "Quick Actions": "快速跳转",
  "View 3D Model": "查看3D模型",
  "Browse Decor": "浏览装饰",
  "Neighborhoods": "住宅区",
  "Neighborhood": "住宅区",
  "Founder's Point": "创始者之角",
  "Razorwind Shores": "烈风海岸",
  "Flight Masters": "飞行管理员",
  "Portals": "传送门",
  "View All": "查看所有",
  "World map": "世界地图",
  "Minimap tiles": "小地图区块",
  "Plots": "地块",
  "Transports": "交通",
  "Back to Browse": "返回浏览页",
  "Feedback": "反馈",
  "Login": "登录",
  "Changelog": "更新日志",
  "Search": "搜索",
  "Apply Filters": "应用过滤器",
  "Clear All": "清除全部",
  "Thumbnail": "缩略图",
  "Name": "名字",
  "Source": "来源",
  "Grid": "网格",
  "Table": "列表",
  "Embed": "嵌入",
  
  "Added": "添加",
  "Updated": "更新",
  "Updates": "更新",
  "Related": "相关",
  "Items": "物品",
  "items": "物品",
  "Misc": "杂项",
  "Recently": "最近",
  "Housing": "家宅",
  "Latest": "最新",
  "Browse": "浏览",
  "Search items": "搜索物品",
  "Model Viewer": "模型查看器",
  "double-click to fullscreen": "双击以全屏查看",

  "new asset coming": "即将更新",
  "DO NOT USE": "请勿使用",
  "DNT": "勿用",
  "AUTOGEN": "自动生成"
};
