window.WowDBDict = {
  "Housing Hub": "家宅中心",
  "Horde Housing District": "部落住宅区",
  "Alliance Housing District": "联盟住宅区",
  "Housing Plots": "房屋地块",

  // 当前版本：12.0.0.64339
  // 更新时间：2025/11/12
  "Ornate Stonework Fireplace": "华丽的石制壁炉",
  "Tusked Fireplace": "獠牙壁炉",
  "Rolled Scroll": "卷起来的卷轴",
  "Sturdy Wooden Bookcase": "牢固的木制书柜",
  "Sturdy Wooden Shelf": "牢固的木制架子",
  "Three-Candle Wrought Iron Chandelier": "三烛锻铁吊灯",
  "Sturdy Wooden Interior Door": "牢固的木制室内门",
  "Small Fruit Platter": "小型果盘",
  "Wrought Iron Floor Lamp": "锻铁地灯",
  "\"Sunrise Canyon\" Painting": "“日出峡谷”画作",
  "Goldshire Window": "闪金镇窗户",
  "Tall Sturdy Wooden Bookcase": "牢固的木制高书柜",
  "Abandoned Bookcase": "废弃的书柜",
  "Wooden Coffin Lid": "木制棺材板",
  "Empty Stormwind Market Stand": "空的暴风城集市小摊",
  "Stormwind Bean Seller's Stand": "暴风城豆商的摊位",
  "Stormwind Spice Merchant's Stand": "暴风城香料商的摊位",
  "Gryphon Roost": "狮鹫栖木",
  "Sturdy Wooden Coffin": "牢固的木制棺材",
  "Open Wooden Coffin": "打开的木制棺材",
  "Open-Air Sturdy Tent": "牢固的开放式帐篷",
  "Sturdy Sheltering Tent": "牢固的遮蔽式帐篷",
  "Small Stonework Fountain": "小型石制喷泉",
  "Large Stonework Fountain": "大型石制喷泉",
  "Sturdy Roofed Wagon": "牢固的顶棚马车",
  "Sturdy Open Wagon": "牢固的开顶马车",
  "Sturdy Covered Wagon": "牢固的顶罩马车",
  "Well-Built Well": "精良的水井",
  "Sturdy Wooden Wheelbarrow": "牢固的木制独轮车",
  "Sturdy Wooden Chair": "牢固的木制椅子",
  "Sturdy Wooden Bed": "牢固的木制床铺",
  "Covered Wooden Table": "遮盖的木制桌子",
  "Sturdy Wooden Table": "牢固的木制桌子",
  "Circular Woolen Rug": "圆形羊绒毯",
  "Studded Wooden Chair": "镶钉木制椅子",
  "Orcish Wooden Bench": "兽人木制长椅",
  "Gift of Gilneas": "吉尔尼斯的礼物",
  "Charming Laurel Tree": "婀娜的月桂树",
  "Orgrimmar Interior Narrow Wall": "奥格瑞玛室内窄墙",
  "Orgrimmar Interior Doorway": "奥格瑞玛室内门廊",
  "Orgrimmar Interior Wall": "奥格瑞玛室内墙壁",
  "Orgrimmar Round Interior Pillar": "奥格瑞玛室内圆形立柱",
  "Orgrimmar Square Interior Pillar": "奥格瑞玛室内方形立柱",
  "Stormwind Interior Pillar": "暴风城室内立柱",
  "Stormwind Interior Narrow Wall": "暴风城室内窄墙",
  "Stormwind Interior Wall": "暴风城室内墙壁",
  "Stormwind Interior Doorway": "暴风城室内门廊",
  "Sturdy Wooden Interior Pillar": "牢固的木制室内立柱",
  "Plain Interior Wall": "朴素的室内墙壁",
  "Plain Interior Doorway": "朴素的室内门廊",
  "Plain Interior Narrow Wall": "朴素的室内窄墙",
  "Winter Veil Tree": "冬幕树",
  "Wild Violet Bellflowers": "狂野的紫罗兰风铃草",
  "Reaching Violet Bellflowers": "伸展的紫罗兰风铃草",
  "Arched Violet Bellflowers": "弯垂的紫罗兰风铃草",
  "Algari Lettuce Plant": "阿加盆栽生菜",
  "NYI 12PH_Opulent_INE01_Partition_Pillar.wmo": "NYI 12PH_Opulent_INE01_Partition_Pillar.wmo",
  "NYI 12PH_Opulent_INE01_Partition_W_L.wmo": "NYI 12PH_Opulent_INE01_Partition_W_L.wmo",
  "NYI 12PH_Opulent_INE01_Partition_W_S.wmo": "NYI 12PH_Opulent_INE01_Partition_W_S.wmo",
  "NYI 12PH_Opulent_INE01_Partition_W_L_Arch.wmo": "NYI 12PH_Opulent_INE01_Partition_W_L_Arch.wmo",
  "Moon-Blessed Storage Crate": "月福储物箱",
  "Ancient Elven Highback Chair": "上古精灵高背椅",
  "Cenarion Privacy Screen": "塞纳里奥私密屏风",
  "Deluxe Val'sharah Bed": "豪华瓦尔莎拉床铺",
  "Cenarion Rectangular Rug": "塞纳里奥长方形毯子",
  "Kaldorei Desk": "卡多雷桌子",
  "Silvermoon Wooden Chair": "银月城木制椅子",
  "Small Silvermoon Bookcase": "小型银月城书柜",
  "Reliquary Storage Crate": "神圣遗物学会储物箱",
  "Long Sin'dorei Rug": "长条辛多雷毯子",
  "Circular Sin'dorei Rug": "圆形辛多雷毯子",
  "Reliquary Telescope": "神圣遗物学会望远镜",
  "Ceiling Cobweb": "天花板蛛网",
  "Tented Cobweb": "帐篷形蛛网",
  "Small Dangling Cobweb": "小型垂挂蛛网",
  "Large Dangling Cobweb": "大型垂挂蛛网",
  "Pillar Cobweb": "立柱蛛网",
  "Wrought Iron Chandelier": "锻铁吊灯",
  "Hungry Human's Platter": "饥饿人类的拼盘",
  "Tirisgarde Book Tempest": "提瑞斯秘法会魔典风暴",
  "Wooden Mug": "木制酒杯",
  "\"Night on the Jeweled Estate\" Painting": "“夜游华彩宅邸”画作",
  "\"The Final Study\" Painting": "“最后一课”画作",
  "\"The Fallen Archmage\" Painting": "“陨落的大法师”画作",
  "Boralus-Style Lobster Platter": "伯拉勒斯风龙虾拼盘",
  "Venthyr Tome of Unforgiven Sins": "温西尔的难赦罪孽之书",
  "\"Aspects in the Clouds\" Painting": "“守护巨龙在云端”画作",
  "\"Water Falls Home\" Painting": "“水帘之家”画作",
  "Dornic Mine and Cheese Platter": "多恩矿石与奶酪拼盘",
  "Literature of Dornogal": "多恩诺嘉尔文学著作",
  "Literature of Taelloch": "塔尔罗克文学著作",
  "Literature of Gundargaz": "冈达加兹文学著作",
  "Collection of Arathi Scripture": "阿拉希雕像收藏",
  "Councilward's Jeweled Goblet": "议会护持的珠宝高脚杯",
  "Kaheti Predator's Assortment": "卡赫提掠食者的什锦",
  "Open Tome of Twilight Nihilism": "翻开的暮光妄想之书",
  "Tome of Silvermoon Intrigue": "银月城阴谋之书",
  "Tome of Twilight Nihilism": "暮光妄想之书",
  "\"Edge of Val'sharah\" Painting": "“瓦尔莎拉边界”画作",
  "Stormwind Produce Seller's Stand": "暴风城农产品商的摊位",
  "Small Poppy Cluster": "小簇粟花",
  "Creeping Corner Ivy": "蔓延的墙角藤蔓",
  "Small Boxwood Bush": "小型黄杨灌木",
  "Cozy Four-Pipe Bed": "舒适的四管床",
  "Rocket-Unpowered Rocket": "火箭失能的火箭",
  "Well-Lit Incontinental Loveseat": "明亮的洋际双人沙发",
  "Well-Lit Incontinental Couch": "明亮的洋际沙发",
  "Lordaeron Banded Crate": "洛丹伦箍边箱",
  "Lordaeron Banded Barrel": "洛丹伦箍边桶",
  "Inert Blight Canister": "失能的荒芜之罐",
  "Banshee Queen's Banner": "女妖之王的旗帜",
  "Elegant Elven Interior Wall": "Elegant Elven Interior Wall",
  "Brill Coffin": "布瑞尔棺材",
  "Gilnean Cauldron": "吉尔尼斯大锅",
  "Gilnean Celebration Keg": "吉尔尼斯庆典酒桶",
  "Worgen's Chicken Coop": "狼人的鸡窝",
  "Gilnean Bench": "吉尔尼斯长椅",
  "Gilnean Wooden Bed": "吉尔尼斯木制床铺",
  "Open Lordaeron Banded Crate": "打开的洛丹伦箍边箱",
  "Forsaken Studded Table": "被遗忘者镶钉桌子",
  "Tirisfal Wooden Chair": "提瑞斯法木制椅子",
  "Forsaken Spiked Chair": "被遗忘者尖刺椅子",
  "Forsaken Round Rug": "被遗忘者圆形毯子",
  "Studious Sin'dorei Desk": "辛多雷学究桌子",
  "Elegant Elven Interior Narrow Wall": "Elegant Elven Interior Narrow Wall",
  "Brill Coffin Lid": "布瑞尔棺材板",
  "Lordaeron Fence": "洛丹伦栅栏",
  "Lordaeron Fencepost": "洛丹伦栅栏桩",
  "Elodor Barrel": "艾洛多尔桶",
  "Argussian Crate": "阿古斯箱子",
  "Spherical Draenic Topiary": "球形德莱尼修剪器",
  "Hanging Draenethyst Light": "德拉诺悬挂灯具",
  "Karabor Bed": "卡拉波床铺",
  "Draenic Bookcase": "德莱尼书柜",
  "Draenic Storage Chest": "德莱尼储物箱",
  "Forsaken War Planning Table": "被遗忘者作战规划桌",
  "Lordaeron Spiked Weapon Rack": "洛丹伦尖刺武器架",
  "Lordaeron Lantern": "洛丹伦灯笼",
  "Forsaken Long Table": "被遗忘者长桌",
  "Lordaeron Hanging Lantern": "洛丹伦悬挂灯笼",
  "Large Forsaken War Tent": "大型被遗忘者作战帐篷",
  "Small Forsaken War Tent": "小型被遗忘者作战帐篷",
  "Blightfire Lantern": "疫火灯笼",
  "Blightfire Hanging Lantern": "疫火悬挂灯笼",
  "Lordaeron Sconce": "洛丹伦灯台",
  "Blightfire Sconce": "疫火灯台",
  "Undercity Spiked Chest": "幽暗城尖刺箱子",
  "Lordaeron Rectangular Rug": "洛丹伦长方形毯子",
  "Lordaeron Torch": "洛丹伦火炬",
  "Blightfire Torch": "疫火火炬",
  "Dark Ship's Lantern": "黑船的灯笼",
  "Forsaken Spiked Brazier": "被遗忘者尖刺火盆",
  "Large Forsaken Spiked Brazier": "大型被遗忘者尖刺火盆",
  "Elegant Padded Chair": "优雅的软垫椅子",
  "Elegant Padded Footstool": "优雅的软垫脚凳",
  "Elegant Covered Bench": "优雅的遮盖长椅",
  "Elegant Wooden Dresser": "优雅的木制衣柜",
  "Small Elegant End Table": "小型优雅边桌",
  "Ornate Weapon Rack": "华丽的武器架",
  "Elegant Elven Barrel": "Elegant Elven Barrel",
  "Elegant Carved Bench": "优雅的雕花长椅",
  "Open Elven Wood Crate": "打开的精灵木箱",
  "Grand Elven Bookcase": "华美的精灵书柜",
  "Stormwind Hall Rug": "暴风城厅堂毯子",
  "Replica Sky's Hope": "Replica Sky's Hope",
  "Secretive Bookcase Wall": "神秘的书柜墙壁",
  "Dark Iron Expedition Tent": "黑铁远征帐篷",
  "Loch Modan Bearskin Rug": "洛克莫丹熊皮毯子",
  "Replica Dark Iron Mole Machine": "仿制的黑铁挖掘机",
  "Gallagio L.U.C.K. Spinner": "加乐宫“试试手气”大转盘",
  "Sturdy Wooden Bench": "牢固的木制长椅",
  "Wicker Basket": "柳条篮",
  "Leather-Bound Haranir Wall Shelf": "Leather-Bound Haranir Wall Shelf",
  "Small Elegant Padded Chair": "小型优雅软垫椅",
  "Standing Ornate Weapon Rack": "立式华丽武器架",
  "Sturdy Haranir Chair": "Sturdy Haranir Chair",
  "Small Mask of Bwonsamdi, Loa of Graves": "小型坟墓之神邦桑迪的面具",
  "Elegant Elven Desk": "优雅的精灵书桌",
  "Carved Elven Bookcase": "雕花精灵书柜",
  "Grand Elven Bench": "华美的精灵长椅",
  "Red Dazar'alor Rug": "红色达萨罗毯子",
  "Square Pandaren Table": "方形熊猫人桌子",
  "Zandalari Rickshaw": "赞达拉人力车",
  "Pandaren Cradle Stool": "熊猫人摇篮凳",
  "Gemmed Eversong Lantern": "嵌宝的永歌灯笼",
  "Bookcase of Gonk": "贡克的书柜",
  "Circular Silvermoon Table": "圆形银月城桌子",
  "Blood Elven Candelabra": "血精灵大烛台",
  "Dazar'alor Market Tent": "达萨罗集市帐篷",
  "Bwonsamdi's Golden Gong": "邦桑迪的金锣",
  "Blue Dazar'alor Rug": "蓝色达萨罗毯子",
  "Rectangular Sin'dorei Rug": "长方形辛多雷毯子",
  "Grand Mask of Bwonsamdi, Loa of Graves": "大型坟墓之神邦桑迪的面具",
  "Idol of Pa'ku, Master of Winds": "风之主宰帕库的神像",
  "Pandaren Wooden Table": "熊猫人木制桌子",
  "Golden Loa's Altar": "金色神灵祭坛",
  "Stone Zandalari Lamp": "石制赞达拉灯笼",
  "Sin'dorei Display Case": "辛多雷陈列柜",
  "Dazar'alor Forge": "达萨罗熔炉",
  "Zuldazar Stool": "祖达萨凳子",
  "Tired Troll's Bench": "疲惫巨魔的长椅",
  "Pandaren Stone Wall": "熊猫人石制墙壁",
  "Silvermoon Library Bookcase": "银月城图书馆书柜",
  "Idol of Rezan, Loa of Kings": "莱赞，诸王的洛阿神灵的神像",
  "Zandalari Weapon Rack": "赞达拉武器架",
  "Long Silvermoon Table": "银月城长桌",
  "Zandalari Sconce": "赞达拉灯台",
  "Zandalari Skullfire Lamp": "赞达拉颅火灯",
  "Pandaren Cooking Table": "熊猫人烹饪桌",
  "Golden Zandalari Bed": "金色赞达拉床铺",
  "Dark Iron Brazier": "黑铁火盆",
  "Gilded Zandalari Table": "鎏金赞达拉桌子",
  "Red Dazar'alor Tent": "红色达萨罗帐篷",
  "Suramar Dresser": "苏拉玛衣柜",
  "Embroidered Sunfury Chair": "Embroidered Sunfury Chair",
  "Sin'dorei Winged Chaise": "Sin'dorei Winged Chaise",
  "Stonebull Canoe": "石牛独木舟",
  "Thunder Totem Brazier": "雷霆图腾火盆",
  "Whitewash River Basket": "白水溪篮子",
  "Enchanted Blood Elven Candelabra": "血精灵附魔大烛台",
  "Zandalari Ritual Drum": "赞达拉仪祭之鼓",
  "Tauren Leather Fence": "牛头人皮革栅栏",
  "Tauren Fencepost": "牛头人栅栏桩",
  "Empty Wicker Basket": "空的柳条篮",
  "Circular Elven Floor Rug": "圆形精灵地毯",
  "Rectangular Elven Floor Rug": "长方形精灵地毯",
  "Rootbound Vat": "Rootbound Vat",
  "Large Highmountain Drum": "大型至高岭之鼓",
  "Tauren Waterwheel": "牛头人水车",
  "Undermine Round Table": "安德麦圆形桌子",
  "Undermine Rectangular Table": "安德麦长方形桌子",
  "Spring-Powered Undermine Chair": "弹簧式安德麦椅子",
  "Rusting Bolted Bench": "锈蚀的螺栓长椅",
  "Very Reliable Undermine Lamppost": "非常可靠的安德麦路灯",
  "Undermine Fencepost": "安德麦栅栏桩",
  "Undermine Fence": "安德麦栅栏",
  "Rust-Plated Storage Crate": "锈板储物箱",
  "Rust-Plated Storage Barrel": "锈板储物桶",
  "Undermine Market Stall": "安德麦集市摊位",
  "Cartel Head's Schmancy Desk": "财阀老大的花里胡哨办公台",
  "Undermine Bookcase": "安德麦书柜",
  "Undermine Wall Shelf": "安德麦壁挂架子",
  "Shredderwheel Storage Chest": "伐木机轮盘储物箱",
  "Rocket-Powered Fountain": "火箭动力喷泉",
  "Trashfire Barrel": "垃圾小火桶",
  "Zhevra-Stripe Rug": "角斑马条纹毯子",
  "\"Elegant\" Lawn Flamingo": "“优雅的”草坪火烈鸟",
  "Undermine Bean Bag Chair": "安德麦豆袋坐垫",
  "Reinforced Goblin Umbrella": "加固的地精雨伞",
  "Rusty Patchwork Tub": "锈蚀的补丁浴盆",
  "Reinforced Wooden Chest": "加固的木制箱子",
  "Tauren Bluff Rug": "牛头人高崖毯子",
  "Elder Rise Rug": "长者高地毯子",
  "Open Silvermoon Drapes": "拉开的银月城窗帘",
  "Small Silvermoon Drapes": "小型银月城窗帘",
  "Warbrave's Brazier": "武士的火盆",
  "Tauren Vertical Windmill": "牛头人垂直风车",
  "Tauren Windmill": "牛头人风车",
  "Small Highmountain Drum": "小型至高岭之鼓",
  "Riverbend Netting": "河湾渔网",
  "Riverbend Jar": "河湾罐子",
  "Highmountain Totem": "至高岭图腾",
  "Skyhorn Storage Chest": "天角储物箱",
  "Tauren Storage Chest": "牛头人储物箱",
  "Dried Whitewash Corn": "晒干的白水玉米",
  "Akunda the Tapestry": "挂毯的阿昆达",
  "Zanchuli Tapestry": "赞枢利挂毯",
  "Zuldazar Fencepost": "祖达萨栅栏桩",
  "Zuldazar Fence": "祖达萨栅栏",
  "Tauren Soup Pot": "牛头人汤锅",
  "Shadowforge Wooden Box": "暗炉木制箱子",
  "Draenor Cookpot": "德拉诺烹饪锅",
  "Frostwolf Bookcase": "霜狼书柜",
  "Durotar Signal Brazier": "杜隆塔尔信号火盆",
  "Durotar Hanging Brazier": "杜隆塔尔悬挂火盆",
  "Blackrock Bunkbed": "黑石双层床",
  "Blackrock Strongbox": "黑石保险箱",
  "Orgrimmar Sconce": "奥格瑞玛灯台",
  "Horde Battle Emblem": "部落战争纹章",
  "Blackrock Weapon Rack": "黑石武器架",
  "Orc-Forged Weaponry": "兽人铸造的武器",
  "Harandar Signpost": "Harandar Signpost",
  "Elegant Padded Divan": "优雅的软垫沙发床",
  "Rectangular Elegant Table": "长方形优雅桌子",
  "Orcish Fencepost": "兽人栅栏桩",
  "Warsong Footrest": "战歌搁脚凳",
  "Frostwolf Round Table": "霜狼圆形桌子",
  "Orcish Communal Stove": "兽人公用火炉",
  "Frostwolf Axe-Dart Board": "霜狼飞斧靶",
  "Elegant Almond Table": "优雅的杏仁形桌子",
  "Orcish Fence": "兽人栅栏",
  "Frostwall Architect's Table": "霜寒晶壁建筑师的桌子",
  "Orcish Warlord's Planning Table": "兽人督军的规划桌",
  "Warsong Workbench": "战歌工作台",
  "Orcish Banded Barrel": "兽人箍边桶",
  "Wine Barrel": "酒桶",
  "Wooden Shipping Crate": "木制船运箱子",
  "Youngling's Courser Toys": "幼崽的骏马玩具",
  "Orcish Lumberjack's Stool": "兽人伐木工的凳子",
  "Frostwolf Banded Stool": "霜狼箍边凳子",
  "Orcish Sleeping Cot": "兽人折叠床",
  "Peon's Work Bucket": "苦工的工作桶",
  "Zuldazar Cook's Griddle": "祖达萨厨师的平底锅",
  "Zandalari Wall Shelf": "赞达拉壁挂架子",
  "Sturdy Wall Rack": "牢固的壁挂架台",
  "Sturdy Fireplace": "牢固的壁炉",
  "Rugged Stool": "粗犷的凳子",
  "Iron Chain Chandelier": "铁链吊灯",
  "Iron-Reinforced Door": "钢铁加固的门",
  "Tusked Gazebo": "獠牙露台",
  "Nightborne Fireplace": "夜之子壁炉",
  "Orcish Scribe's Drafting Table": "兽人铭文师的绘图桌",
  "Small Purple Suramar Seat Cushion": "小型紫色苏拉玛座椅软垫",
  "Gilnean Circular Rug": "吉尔尼斯圆形毯子",
  "Silvermoon Painter's Cushion": "Silvermoon Painter's Cushion",
  "Small Silvermoon Seat Cushion": "小型银月城座椅软垫",
  "Triangular Silvermoon Seat Cushion": "三角形银月城座椅软垫",
  "Circular Silvermoon Seat Cushion": "原型银月城座椅软垫",
  "Silvermoon Pillow Roll": "银月城滚卷枕头",
  "Tied-Open Leather Curtains": "卷开的皮革窗帘",
  "Closed Leather Curtains": "封闭的皮革窗帘",
  "Leather Valance": "皮革帷幔",
  "Tied-Open Folk Curtains": "卷开的民间窗帘",
  "Closed Folk Curtains": "封闭的民间窗帘",
  "Durable Folk Valance": "耐用的民间帷幔",
  "Restful Wooden Bench": "宁静的木制长椅",
  "Light-Infused Fountain": "光注喷泉",
  "Tiny String of Schmancy Goblin Lights": "微小花哨地精彩灯串",
  "Small String of Schmancy Goblin Lights": "小型花哨地精彩灯串",
  "Drooping String of Schmancy Goblin Lights": "垂挂花哨地精彩灯串",
  "Very Long String of Schmancy Goblin Lights": "很长一条花哨地精彩灯串",
  "Long String of Schmancy Goblin Lights": "长条花哨地精彩灯串",
  "Teal Suramar Seat Cushion": "青色苏拉玛座椅软垫",
  "Purple Suramar Seat Cushion": "紫色苏拉玛座椅软垫",
  "Small Red Suramar Seat Cushion": "小型红色苏拉玛座椅软垫",
  "Surwich Peddler's Wagon": "瑟维奇小贩的货车",
  "Sethraliss Priest's Pillow": "塞塔里斯祭司的枕头",
  "Sethrak Neckroll Pillow": "蛇人靠颈枕头",
  "Circular Elven Table": "圆形精灵桌子",
  "Elegant Wall Drape": "优雅的壁挂帷幔",
  "Elven Floral Window": "精灵花卉窗户",
  "Head of the Broodmother": "龙母的徽记",
  "Val'sharah Bookcase": "瓦尔莎拉书柜",
  "Small Val'sharah Bookcase": "小型瓦尔莎拉书柜",
  "Kaldorei Chef's Table": "卡多雷大厨的桌子",
  "Kaldorei Washbasin": "卡多雷脸盆",
  "Zocalo Drinks": "佐卡罗饮料",
  "Round Stitched Cushion": "圆形缝补软垫",
  "Stitched Pillow Roll": "缝合枕卷",
  "Iron-Studded Wooden Window": "钉铁的木制窗户",
  "Charming Seat Cushion": "魅力座椅软垫",
  "Checkered Charming Seat Cushion": "方格型魅力座椅软垫",
  "Thunder Totem Kiln": "雷霆图腾烧窑",
  "Old Salt's Fireplace": "老水手的壁炉",
  "Orgrimmar Chair": "奥格瑞玛椅子",
  "Rugged Brazier": "粗犷火盆",
  "Frostwall Elevated Brazier": "霜寒晶壁架高火盆",
  "Orgrimmar Nightstand": "奥格瑞玛床头柜",
  "Durable Wooden Chest": "耐用的木制箱子",
  "Wide Charming Couch": "加宽魅力沙发",
  "Iron-Reinforced Cupboard": "钢铁加固的橱柜",
  "Trueshot Lodge Fireplace": "神射手营地壁炉",
  "Runed Dreamweaver Moonstone": "符文织梦者月亮石",
  "Worker's Wooden Desk": "工人的木制桌子",
  "Orgrimmar Tusked Bed": "奥格瑞玛獠牙床铺",
  "Iron-Reinforced Standing Mirror": "钢铁加固的落地镜",
  "Shaded Suramar Window": "阴暗的苏拉玛窗户",
  "Elaborate Suramar Window": "精致的苏拉玛窗户",
  "Octagonal Ochre Window": "八边形赭色窗户",
  "Meadery Ochre Window": "酒庄赭色窗户",
  "Ornate Ochre Window": "华丽赭色窗户",
  "Bel'ameth Interior Wall": "贝拉梅斯室内墙壁",
  "Bel'ameth Round Interior Pillar": "贝拉梅斯室内圆形立柱",
  "Bel'ameth Interior Doorway": "贝拉梅斯室内门廊",
  "Bel'ameth Interior Narrow Wall": "贝拉梅斯室内窄墙",
  "Silvermoon Round Interior Pillar": "银月城室内圆形立柱",
  "Silvermoon Interior Narrow Wall": "银月城室内窄墙",
  "Silvermoon Interior Wall": "银月城室内墙壁",
  "Frostwall Forge": "霜寒晶壁熔炉",
  "Ancestral Signal Brazier": "先祖信号火盆",
  "Gilnean Problem Solver": "吉尔尼斯解忧者",
  "Gilnean Noble's Trellis": "吉尔尼斯贵族的篱笆",
  "Arched Rose Trellis": "弯垂玫瑰篱笆",
  "Gilnean Stone Wall": "吉尔尼斯石制墙壁",
  "Bradensbrook Smoke Lantern": "鲑鱼溪缭烟灯笼",
  "Bradensbrook Thorned Well": "鲑鱼溪荆棘水井",
  "Gilnean Stocks": "吉尔尼斯枷锁",
  "Surwich Expedition Tent": "瑟维奇远征帐篷",
  "Little Wolf's Loo": "小狼的厕所",
  "Gilnean Wooden Table": "吉尔尼斯木制桌子",
  "Gilnean Wall Shelf": "吉尔尼斯壁挂架子",
  "Gilnean Rocking Chair": "吉尔尼斯摇椅",
  "Waning Wood Fence": "不牢的木栅栏",
  "Bel'ameth Bench": "贝拉梅斯长椅",
  "Elven Temple Brazier": "精灵神殿火盆",
  "Silvermoon Interior Doorway": "银月城室内门廊",
  "Filigree Moon Lamp": "丝带月之灯笼",
  "Wooden Gazebo": "木制露台",
  "Stonework Fountain": "石制喷泉",
  "Elwynn Cobblestone Round": "艾尔文圆形卵石",
  "Elwynn Cobblestone": "艾尔文卵石",
  "Elwynn Cobblestone Pair": "艾尔文卵石对",
  "Elwynn Cobblestone Cluster": "艾尔文卵石簇",
  "Carved Wooden Bar Table": "雕刻木制酒吧桌",
  "Orgrimmar Bureaucrat's Desk": "奥格瑞玛官员书桌",
  "Tidesage's Fireplace": "海贤壁炉",
  "Shala'nir Feather Bed": "沙拉尼尔羽毛床铺",
  "Kaldorei Stone Fence": "卡多雷石制围栏",
  "Kaldorei Stone Fencepost": "卡多雷石制围栏桩",
  "Kaldorei Cushioned Seat": "卡多雷软垫座椅",
  "Elven Round Table": "精灵圆形桌子",
  "Kaldorei Wall Shelf": "卡多雷壁挂架子",
  "Kaldorei Treasure Trove": "卡多雷宝库",
  "Bel'ameth Barrel": "贝拉梅斯桶",
  "Crescent Moon Lamppost": "新月路灯",
  "Overgrown Arathi Trellis": "蔓生的阿拉希篱笆",
  "Void-Corrupted Fountain": "虚空腐化的喷泉",
  "Silvermoon Sanctum Teleporter": "Silvermoon Sanctum Teleporter",
  "Sagehold Window": "贤者要塞窗户",
  "Floating Azure Lantern": "Floating Azure Lantern",
  "Orange Suramar Seat Cushion": "橙色苏拉玛座椅软垫",
  "Red Suramar Seat Cushion": "红色苏拉玛座椅软垫",
  "High-Backed Orgrimmar Chair": "高背奥格瑞玛椅子",
  "Iron-Reinforced Wooden Rack": "钢铁加固的木制架台",
  "Stitched Leather Rug": "缝补皮革毯子",
  "Schmancy Goblin String Lights": "花哨地精彩灯串",
  "Bel'ameth Wooden Table": "贝拉梅斯木制桌子",
  "Bel'ameth Crafter's Tent": "贝拉梅斯工匠帐篷",
  "Small Bel'ameth Tent": "小型贝拉梅斯帐篷",
  "Small Wooden Stool": "小型木制凳子",
  "Large Covered Wooden Table": "大型遮盖的木制桌子",
  "Small Wooden Nightstand": "小型木制床头柜",
  "Carved Wooden Crate": "雕刻木制箱子",
  "Sturdy Weapon Rack": "牢固的武器架",
  "Wooden Chamberstick": "木制手持烛台",
  "Large Sturdy Wooden Table": "大型牢固的木制桌子",
  "Embellished Dwarven Tome": "装饰的矮人之书",
  "Open Carved Wooden Crate": "打开的雕刻木制箱子",
  "Filigree Moon Sconce": "丝带月之灯台",
  "Shadowforge Sconce": "暗炉灯台",
  "Sprouting Lamppost": "萌芽的路灯",
  "Short Orgrimmar Bench": "短款奥格瑞玛长椅",
  "Iron-Reinforced Crate": "钢铁加固的箱子",
  "Weather-Treated Wooden Table": "防护处理的木制桌子",
  "Leather-Banded Wooden Bench": "蒙皮木制长椅",
  "Boralus String Lights": "伯拉勒斯串灯",
  "Cozy Hide-Covered Bench": "铺着毛皮的舒适长椅",
  "Large Orgrimmar Bookcase": "大型奥格瑞玛书柜",
  "Small Leather Rug": "小型皮革毯子",
  "Spiky Banded Barrel": "尖刺箍边桶",
  "Stormwind Beam Platform": "暴风城柱状平台",
  "Stormwind Round Platform": "暴风城圆形平台",
  "Stormwind Large Platform": "暴风城大型平台",
  "Stormwind Small Platform": "暴风城小型平台",
  "Stormwind Angled Platform": "暴风城斜角平台",
  "Silvermoon Beam Platform": "银月城柱状平台",
  "Silvermoon Large Platform": "银月城大型平台",
  "Silvermoon Small Platform": "银月城小型平台",
  "Silvermoon Angled Platform": "银月城斜角平台",
  "Silvermoon Round Platform": "银月城圆形平台",
  "Bel'ameth Beam Platform": "贝拉梅斯柱状平台",
  "Bel'ameth Large Platform": "贝拉梅斯大型平台",
  "Bel'ameth Small Platform": "贝拉梅斯小型平台",
  "Bel'ameth Angled Platform": "贝拉梅斯斜角平台",
  "Bel'ameth Round Platform": "贝拉梅斯圆形平台",
  "Orgrimmar Beam Platform": "奥格瑞玛柱状平台",
  "Orgrimmar Round Platform": "奥格瑞玛圆形平台",
  "Orgrimmar Large Platform": "奥格瑞玛大型平台",
  "Orgrimmar Small Platform": "奥格瑞玛小型平台",
  "Orgrimmar Angled Platform": "奥格瑞玛斜角平台",
  "Hollowed Harandar Gourds": "Hollowed Harandar Gourds",
  "Haranir Herb Rack": "Haranir Herb Rack",
  "Shadowforge Grinding Wheel": "暗炉砂轮",
  "Dark Iron Table Saw": "黑铁台锯",
  "Ironforge Bookcase": "铁炉堡书柜",
  "Small Ironforge Bookcase": "小型铁炉堡书柜",
  "Blackrock Lamppost": "黑石路灯",
  "Light-Infused Rotunda": "光注圆台",
  "Kharanos Bookcase": "卡拉诺斯书柜",
  "Stolen Ironforge Seat": "失窃的铁炉堡座椅",
  "Thelsamar Hanging Lantern": "塞尔萨玛悬挂灯笼",
  "Wooden Ironforge Table": "铁炉堡木制桌子",
  "Square Stormpike Table": "方形雷矛桌子",
  "Round Dwarven Table": "原型矮人桌子",
  "Ornate Ironforge Table": "华丽的铁炉堡桌子",
  "Dilapidated Wildhammer Well": "破旧的蛮锤水井",
  "Overgrown Wildhammer Fountain": "蔓生的蛮锤喷泉",
  "Dark Iron Chandelier": "黑铁吊灯",
  "Elegant Tied Curtain": "优雅的系结窗帘",
  "Ambient Aethercharged Crystal": "Ambient Aethercharged Crystal",
  "Gnomish T.O.O.L.B.O.X.": "侏儒工具箱",
  "Automated Gnomeregan Guardian": "自动化诺莫瑞根守护者",
  "Retired Industrial Gnomegrabber": "退役的工业化侏儒抓取者",
  "Mechanical Gnomish Lamppost": "机械化侏儒路灯",
  "Redundant Reclamation Rig": "备用的开垦钻机",
  "Mechagon Hanging Floodlight": "麦卡贡悬挂泛光灯",
  "Mechagnome Sustenance Distributor": "机械侏儒维生物资分发站",
  "Gnomish Tesla Mega-Coil": "侏儒超级电磁圈",
  "Gnomish Tesla Coil": "侏儒电磁圈",
  "Ironforge Chandelier": "铁炉堡吊灯",
  "Steel Ironforge Emblem": "钢制铁炉堡纹章",
  "Ironforge Fencepost": "铁炉堡栅栏桩",
  "Ironforge Fence": "铁炉堡栅栏",
  "Small Emergency Warning Lamp": "小型应急警告灯",
  "Emergency Warning Lamp": "应急警告灯",
  "Mechagon Eyelight Lamp": "麦卡贡对目照明灯",
  "Mechagon Miniature Artificial Sun": "麦卡贡微缩人造太阳",
  "Gnomish Safety Flamethrower": "侏儒安保喷火器",
  "Charming Couch": "魅力沙发",
  "Large H.O.M.E. Cog": "大型家居齿轮",
  "Short Orgrimmar Bookcase": "奥格瑞玛矮书柜",
  "Sturdy Wooden Trellis": "牢固的木制篱笆",
  "Gnomish Fencepost": "侏儒栅栏桩",
  "Gnomish Fence": "侏儒栅栏",
  "Perpetual Motion Crate": "永动箱子",
  "Screw-Sealed Stembarrel": "螺丝密封的高脚桶",
  "Self-Sealing Stembarrel": "自行密封的高脚桶",
  "Small Mechanical Crate": "小型机械箱子",
  "Bolt Chair": "螺栓椅子",
  "Small H.O.M.E. Cog": "小型家居齿轮",
  "Gnomish Cog Stack": "侏儒齿轮叠",
  "Deactivated Atomic Recalibrator ": "关闭的原子重校器 ",
  "Mecha-Storage Mecha-Chest": "机械仓储的机械箱子",
  "Mechagon Armory Rack": "麦卡贡军械架",
  "Durable Hex Table": "耐用的妖术桌",
  "Long Leather-Clad Table": "加长覆皮桌子",
  "Orgrimmar Open Dresser": "奥格瑞玛开放式衣柜",
  "Razorwind Standing Mirror": "烈风落地镜",
  "Razorwind Fountain": "烈风喷泉",
  "Logger's Picnic Table": "伐木工的野餐桌",
  "Long Durable Table": "加长耐用桌子",
  "Razorwind Bar Table": "烈风酒吧桌",
  "Open Spiky Banded Barrel": "打开的尖刺箍边桶",
  "Open Iron-Reinforced Crate": "打开的钢铁加固的箱子",
  "Dwarven District Banner": "矮人区旗帜",
  "Grummle Sleeping Bag": "土地精睡袋",
  "Tusked Candleholder": "獠牙秉烛台",
  "Grand Elven Wall Curtain": "华美的精灵壁挂窗帘",
  "Murder Row Wine Decanter": "Murder Row Wine Decanter",
  "Self-Pouring Thalassian Sunwine": "Self-Pouring Thalassian Sunwine",
  "Gnomish Steam-Powered Bed": "侏儒蒸汽动力床",
  "Gnomish Sprocket Table": "侏儒链齿桌子",
  "Double-Sprocket Table": "双链齿桌子",
  "Caramel Mint Noodle Dish": "焦糖薄荷面",
  "Elegant Dracthyr's Tea Cup": "优雅龙希尔的茶杯",
  "Decorative Cinder Honeypot": "装饰性燧烬蜜罐",
  "Dornic Sliced Mineloaf": "多恩矿石切片",
  "Earthen Hospitality Cheese-Like Brick": "土灵待客奶酪砖",
  "Elegant Pillow Roll": "优雅的滚卷枕头",
  "Grummle Bedroll": "土地精铺盖",
  "Tall Sturdy Wooden Chair": "牢固的木制高椅子",
  "Hanging Mana Brazier": "Hanging Mana Brazier",
  "Zangarshroom Patch": "赞加沼泽地面",
  "Arched Wooden Bench": "弯拱木制长椅",
  "Kafa Press": "Kafa Press",
  "Tome of Shadowforge Cunning": "暗炉狡诈之书",
  "Tome of Pandaren Wisdom": "熊猫人睿智之书",
  "Tome of Draenei Faith": "德莱尼信仰之书",
  "Scribe's Working Notes": "铭文师的工作笔记",
  "\"Welcoming Pantry\" Painting": "“迎宾果盘”画作",
  "\"Fruit of the Arcan'dor\" Painting": "“阿坎多尔的果实”画作",
  "\"Raising Your Eyes\" Painting": "“仰望天空”画作",
  "\"Healthy Conjuration\" Painting": "“健康造餐”画作",
  "\"The Water Lilies\" Painting": "“池塘睡莲”画作",
  "\"Broken Steps\" Painting": "“破碎之阶”画作",
  "\"Through the Portal\" Painting": "“突入传送门”画作",
  "\"Smiling Suns\" Painting": "“向日笑颜”画作",
  "\"Shu'halo Perspective\" Painting": "“舒哈鲁视角”画作",
  "\"Tidesage's Omen\" Painting": "“海贤的预兆”画作",
  "\"Fate of All Life\" Painting": "“万物的命运”画作",
  "Tome of Forsaken Resilience": "被遗忘者坚毅之书",
  "\"Tea and Sin\" Painting": "“煮茶论罪”画作",
  "\"Light's Vengeance\" Painting": "“圣光的复仇”画作",
  "Open Tome of the Dragon's Dedication": "翻开的巨龙奉献之书",
  "Tome of the Lost Dragon": "失落巨龙之书",
  "Tome of Reliquary Insights": "神圣遗物学会洞察之书",
  "Kaheti Scribe's Records": "卡赫提铭文师的档案",
  "Tome of Earthen Directives": "土灵指令之书",
  "Wide Hide-Covered Bench": "铺着毛皮的加宽长椅",
  "Razorwind Wall Mirror": "烈风壁挂镜子",
  "Farmer's Water Trough": "农夫的水槽",
  "Hay-Filled Sturdy Feeding Trough": "填满甘草的牢固喂食槽",
  "Carved Stone Bench": "雕刻石制长椅",
  "Sturdy Brazier": "牢固的火盆",
  "Founder's Point Street Light": "创始者之角街灯",
  "Founder's Point Lamppost": "创始者之角路灯",
  "Sturdy Feeding Trough": "牢固的食槽",
  "Tusked Hanging Sconce": "獠牙悬挂灯台",
  "Horned Banded Barrel": "巨角箍边桶",
  "Open Horned Banded Barrel": "打开的巨角箍边桶",
  "Long Orgrimmar Bench": "加长奥格瑞玛长椅",
  "Crude Banded Crate": "粗制箍边箱",
  "Open Crude Banded Crate": "打开的粗制箍边箱",
  "Small Covered Wooden Table": "小型遮盖的木制桌子",
  "Small Sturdy Wooden Table": "小型牢固的木制桌子",
  "Sealed Fungal Jar": "Sealed Fungal Jar",
  "Opened Fungal Jar": "Opened Fungal Jar",
  "Elegant Seat Cushion": "优雅的座椅软垫",
  "Mushan Dumpling Stack": "穆山饺子堆",
  "Small Orgrimmar Chair": "小型奥格瑞玛椅子",
  "Drake Kebab Platter": "幼龙串烧拼盘",
  "Roast Riverbeast Platter": "香烤淡水兽拼盘",
  "Valdrakken Blossomfruit Platter": "瓦德拉肯繁华水果拼盘",
  "Bruffalon Rib Platter": "驼牛肋排拼盘",
  "Elegant Carved Door": "优雅的雕花门",
  "Elven Woodvine Trellis": "精灵木藤篱笆",
  "Pandaren Signal Brazier": "熊猫人信号火盆",
  "Pandaren Scholar's Lectern": "熊猫人学者的讲台",
  "Pandaren Scholar's Bookcase": "熊猫人学者的书柜",
  "Jade Temple Incense Burner": "青龙寺焚香炉",
  "Gate of the Apexis": "埃匹希斯之门",
  "Dalaran Pedestal": "达拉然底座",
  "MOTHER's Titanic Brazier": "纯净圣母的泰坦火盆",
  "N'Zoth's Captured Eye": "被捕获的恩佐斯之眼",
  "Lorewalker's Bookcase": "游学者的书柜",
  "Pandaren Pantry": "熊猫人食品柜",
  "Iron Dragonmaw Gate": "钢铁龙喉大门",
  "Pandaren Stone Post": "熊猫人石桩",
  "Pandaren Stone Lamppost": "熊猫人石制路灯",
  "Red Crane Kite": "朱鹤风筝",
  "Hanging Paper Lanterns": "垂挂的纸制灯笼",
  "Lucky Hanging Lantern": "幸运悬挂灯笼",
  "Halfhill Cookpot": "半山烹饪锅",
  "Paw'don Well": "坡东水井",
  "Lucky Traveler's Bench": "好运旅人的长椅",
  "Jade Temple Dragon Fountain": "青龙寺龙口喷泉",
  "Stormstout Brew Keg": "风暴烈酒陈酿桶",
  "Pandaren Meander Rug": "熊猫人蜿蜒毯子",
  "Kotmogu Pedestal": "寇魔古底座",
  "Kotmogu Orb of Power": "寇魔古能量球",
  "Timeless Dumpling Cart": "永恒馄饨餐车",
  "Alliance Dueling Flag": "联盟决斗旗",
  "Horde Dueling Flag": "部落决斗旗",
  "Silverwing Sentinels Flag": "银翼要塞旗帜",
  "Warsong Outriders Flag": "战歌氏族旗帜",
  "Earthcrawl Mine Cart": "地匍矿洞矿车",
  "Deephaul Crystal": "御渊水晶",
  "Deactivated K'areshi Warp Cannon": "关闭的卡雷什迁跃火炮",
  "Pandaren Fireplace": "熊猫人壁炉",
  "Challenger's Dueling Flag": "挑战者的决斗旗",
  "Alliance Battlefield Banner": "联盟战场军旗",
  "Fortified Alliance Banner": "强韧联盟军旗",
  "Horde Battlefield Banner": "部落战场军旗",
  "Fortified Horde Banner": "强韧部落军旗",
  "Uncontested Battlefield Banner": "非争夺中的战场军旗",
  "Netherstorm Battlefield Flag": "虚空风暴战场军旗",
  "Berserker's Empowerment": "狂战士强化",
  "Enigmatic Purple Crystal": "神秘的紫水晶",
  "Healer's Empowerment": "治疗者强化",
  "Runner's Empowerment": "奔跑者强化",
  "Wise Pandaren's Bed": "睿智熊猫人的床铺",
  "Guardian's Empowerment": "守护者强化",
  "Chaotic Empowerment": "混乱强化",
  "Mysterious Empowerment": "神秘强化",
  "Zangarmarsh Lamppost": "Zangarmarsh Lamppost",
  "Small Zangarshroom Patch": "Small Zangarshroom Patch",
  "Sturdy Zangarshelf": "Sturdy Zangarshelf",
  "Orange Zangarmarsh Tree": "Orange Zangarmarsh Tree",
  "Glowing Zangarshroom Bowl": "Glowing Zangarshroom Bowl",
  "Glowing Zangarshroom Cup": "Glowing Zangarshroom Cup",
  "Blue Zangarmarsh Tree": "Blue Zangarmarsh Tree",
  "Green Zangarmarsh Tree": "Green Zangarmarsh Tree",
  "Purple Zangarmarsh Tree": "Purple Zangarmarsh Tree",
  "Withered Zangarmarsh Tree": "Withered Zangarmarsh Tree",
  "Glowing Withered Zangarmarsh Tree": "Glowing Withered Zangarmarsh Tree",
  "Pulsing Zangarshroom": "Pulsing Zangarshroom",
  "Orange Spore Light": "Orange Spore Light",
  "Yellow Spore Light": "Yellow Spore Light",
  "Galactic Void-Scarred Banner": "Galactic Void-Scarred Banner",
  "Nightborne Merchant's Stall": "夜之子商人的摊位",
  "Deluxe Suramar Sleeper": "豪华苏拉玛卧铺",
  "Suramar Library": "苏拉玛图书馆",
  "Nightborne Bench": "夜之子长椅",
  "Arcwine Counter": "魔力酒柜台",
  "Pandaren Lacquered Crate": "熊猫人喷漆箱子",
  "Serenity Peak Tent": "晴日峰帐篷",
  "Shaohao Ceremonial Bell": "少昊仪式大钟",
  "Nightborne Lantern": "夜之子灯笼",
  "Suramar Fencepost": "苏拉玛栅栏桩",
  "Suramar Sconce": "苏拉玛灯台",
  "Shal'dorei Seat": "夏多雷座椅",
  "Large Traditional Shal'dorei Rug": "大型传统夏多雷毯子",
  "Ornate Suramar Table": "华丽苏拉玛桌子",
  "Covered Ornate Suramar Table": "遮盖的华丽苏拉玛桌子",
  "Square Suramar Table": "方形苏拉玛桌子",
  "Covered Square Suramar Table": "遮盖的方形苏拉玛桌子",
  "Covered Small Suramar Table": "遮盖的小型苏拉玛桌子",
  "Nightborne Jeweler's Table": "夜之子珠宝匠的桌子",
  "Traditional Shal'dorei Rug": "传统夏多雷毯子",
  "Circular Shal'dorei Rug": "圆形夏多雷毯子",
  "Nightborne Wall Shelf": "夜之子壁挂架子",
  "Suramar Fence": "苏拉玛栅栏",
  "Suramar Containment Cell": "苏拉玛禁闭室",
  "Suramar Street Light": "苏拉玛街灯",
  "Suramar Storage Crate": "苏拉玛储物箱",
  "Suramar Window": "苏拉玛窗户",
  "Shal'dorei Open-Air Tent": "夏多雷开放式帐篷",
  "Trueshot Skeletal Dragon Trophy": "神射骨龙战利品",
  "Pandaren Target Dummy": "熊猫人目标假人",
  "Traditional Brewfest Stein": "传统美酒节酒杯",
  "Venthyr's Target Dummy": "温西尔的目标假人",
  "Draconic Stone Table": "龙族石制桌子",
  "Pentagonal Stone Table": "五边形石制桌子",
  "Valdrakken Sconce": "瓦德拉肯灯台",
  "Valdrakken Banded Barrel": "瓦德拉肯箍边桶",
  "Valdrakken Storage Crate": "瓦德拉肯储物箱",
  "Long Valdrakken Storage Crate": "加长瓦德拉肯储物箱",
  "Valdrakken Fence": "瓦德拉肯栅栏",
  "Valdrakken Fencepost": "瓦德拉肯栅栏桩",
  "Verdant Valdrakken Vase": "翠绿瓦德拉肯花瓶",
  "Valdrakken Garden Fountain": "瓦德拉肯花园喷泉",
  "Thaldraszus Telescope": "索德拉苏斯望远镜",
  "Draconic Nesting Bed": "龙族栖巢之床",
  "Valdrakken Chandelier": "瓦德拉肯吊灯",
  "Studious Dracthyr's Tomes": "勤奋龙希尔的书籍",
  "Literature of the Blue Dragonflight": "蓝龙军团文学著作",
  "Literature of the Green Dragonflight": "绿龙军团文学著作",
  "Literature of the Red Dragonflight": "红龙军团文学著作",
  "Draconic Circular Rug": "龙族圆形毯子",
  "Non-Fatal One-Armed Bandit": "非致命型号的独臂盗匪",
  "The Great Hoard": "宏伟库门",
  "Portal to Damnation": "诅咒传送门",
  "Razorwind Storage Table": "烈风储物桌",
  "Stormwind Footlocker": "暴风城手提箱",
  "Stormwind Large Wooden Table": "暴风城大型木制桌子",
  "Stormwind Wooden Bench": "暴风城木制长椅",
  "Stormwind Wooden Stool": "暴风城木制凳子",
  "Stormwind Wooden Table": "暴风城木制桌子",
  "Round-Top Boulder": "圆顶巨石",
  "Flat Boulder": "平整巨石",
  "Hilltop Boulder": "山顶巨石",
  "Founder's Point Signpost": "创始者之角指示牌",
  "Ornamental Kaldorei Glaive": "纹饰卡多雷战刃",
  "Grummle Kafa Refinery": "Grummle Kafa Refinery",
  "Grummle Tent": "Grummle Tent",
  "Kafa Creamer": "Kafa Creamer",
  "Legerdemain Lounge Sign Board": "Legerdemain Lounge Sign Board",
  "Dalaran Kafa Table": "Dalaran Kafa Table",
  "Stormwind Keg Stand": "暴风城桶架",
  "Westfall Woven Basket": "西部荒野手编篮子",
  "Stormwind Gazebo": "暴风城露台",
  "Stormwind Trellis and Basin": "暴风城篱笆与洗涤槽",
  "Stormwind Arched Trellis": "暴风城弯拱篱笆",
  "Wooden Outhouse": "木制厕所",
  "Kaldorei Scribe's Shelf": "卡多雷铭文师的架子",
  "Cookout Campfire": "野炊营火",
  "Razorwind Succulent Palm": "烈风多肉棕榈",
  "Razorwind Fighting Cactus": "烈风格斗仙人掌",
  "Razorwind Tumbleweed": "烈风风滚草",
  "Razorwind Palm Tree": "烈风棕榈树",
  "Nagrand Blueberry Bush": "纳格兰蓝莓灌木丛",
  "Barrens Hosta Bush": "贫瘠之地玉簪灌木丛",
  "Azsharan Firespear Tree": "艾萨拉火矛树",
  "Hardy Razorwind Grass Patch": "顽强的烈风草丛",
  "Flowering Durotar Cactus": "开花的杜隆塔尔仙人掌",
  "Razorwind Acacia Tree": "烈风合欢树",
  "Elwynn Whitebrush": "艾尔文白灌木",
  "Razorwind Gobtree": "烈风地精树",
  "Sunset Aster Flowers": "日落紫菀花",
  "Pink Razorwind Paintbrush": "粉红烈风火焰草",
  "Gloomrose": "幽影玫瑰",
  "Duskberry Bush": "暮莓灌木丛",
  "Duskwood Shadebrush": "暮色森林阴影灌木",
  "Creeping Lattice Ivy": "蔓延的爬架藤蔓",
  "Duskwood Sycamore Shrub": "暮色森林梧桐灌木",
  "Spiritbloom Flower": "精神绽花",
  "Pink Gilnean Rose": "粉红吉尔尼斯玫瑰",
  "Silvermoon Sunrise Bush": "银月城晨曦灌木丛",
  "Founder's Point Blooming Grass Patch": "创始者之角盛放草丛",
  "Autumn Leaf Pile": "秋日落叶堆",
  "Young Chestnut Tree": "栗子树苗",
  "Razorwind Flamebrush": "烈风焰灌从",
  "Draconic Memorial Stone": "龙族悼念石",
  "Dragon's Grand Mirror": "巨龙的宏大镜子",
  "Valdrakken Stone Stool": "瓦德拉肯石制凳子",
  "Valdrakken Gilded Throne": "瓦德拉肯鎏金王座",
  "Elegant Dracthyr's Tea Set": "优雅龙希尔的茶具",
  "Dragon's Hoard Chest": "巨龙的囤宝箱",
  "Valdrakken Market Tent": "瓦德拉肯集市帐篷",
  "Elven Wood Crate": "精灵木制箱子",
  "Stormwind Workbench": "暴风城工作台",
  "Northshire Scribe's Desk": "北郡铭文师的抄写台",
  "Jewelcrafter's Tent": "珠宝匠的帐篷",
  "Wooden Doghouse": "木制狗舍",
  "Alliance Soldier's Bed": "联盟士兵的床铺",
  "Stormwind Peddler's Cart": "暴风城小贩的推车",
  "Relaxing Goblin Beach Chair with Cup Gripper": "配有杯托的休闲地精沙滩椅",
  "Amirdrassil Stool": "阿梅达希尔凳子",
  "Lovely Elven Shelf": "可爱的精灵架子",
  "Elwynn Fence": "艾尔文栅栏",
  "Elwynn Fencepost": "艾尔文栅栏桩",
  "Goldshire Food Cart": "闪金镇食品餐车",
  "City Wanderer's Candleholder": "城市漫游者烛台",
  "Northshire Barrel": "北郡桶",
  "Wooden Storage Crate": "木制储物箱",
  "Architect's Drafting Table": "建筑师的绘图桌",
  "Stormwind Weapon Rack": "暴风城武器架",
  "Elwynn Grass Patch": "艾尔文草丛",
  "Elwynn Grass Spread": "艾尔文草簇",
  "Nesingwary Shoveltusk Trophy": "奈辛瓦里的铲齿鹿战利品",
  "Nesingwary Elk Trophy": "奈辛瓦里的雷象战利品",
  "Void-Corrupted Rotunda": "虚空腐化的圆台",
  "Rough Wooden Chair": "粗糙的木制椅子",
  "Elwynn Small Grass Patch": "小型艾尔文草丛",
  "Golden Cloud Serpent Treasure Chest": "金色云端翔龙宝箱",
  "Five Dawns Weapon Rack": "五晨寺武器架",
  "Five Dawns Shrine of the Smoking Fish": "五晨寺熏鱼坛",
  "Ironpaw Stew Cart": "铁掌炖菜餐车",
  "Hooded Iron Lantern": "蒙住的铁制灯笼",
  "Stormwind Lamppost": "暴风城路灯",
  "Replica Felblood Altar": "仿制的魔血祭坛",
  "Five Dawns Planning Table": "五晨寺规划桌",
  "Black Harvest Banner": "黑暗收割旗帜",
  "Monastery Gong": "禅院锣鼓",
  "Dreadscar Bookcase": "恐痕书柜",
  "Dreadscar Dais": "恐痕讲台",
  "Cosmic Void Table": "Cosmic Void Table",
  "Resplendent Highborne Statue": "Resplendent Highborne Statue",
  "Tauren Hanging Brazier": "牛头人悬挂火盆",
  "Black Harvest Orrery": "黑暗收割星象仪",
  "Smoke Sconce": "烟雾灯台",
  "Replica Cursed Forge of the Nathrezim": "仿制的纳斯雷兹姆的诅咒熔炉",
  "Replica Forge of Odyn": "仿制的奥丁的熔炉",
  "Illidari Glaiverest": "伊利达雷战刃架台",
  "Skyhold Brazier": "苍穹要塞火盆",
  "Skyhold War Table": "苍穹要塞战时指挥桌",
  "Illidari Banner": "伊利达雷旗帜",
  "Illidari Skull Sentinel": "伊利达雷颅骨哨兵",
  "Valarjar Banner": "瓦拉加尔旗帜",
  "Valarjar Keg of Celebration": "瓦拉加尔庆典酒桶",
  "Valarjar Shield Wall": "瓦拉加尔盾墙",
  "Fel Hammer Scouting Map": "邪能之槌号侦察地图",
  "Preserver's Censer": "恩护师的香炉",
  "Dracthyr Weapon Rack": "龙希尔武器架",
  "Evoker's Elegant Rug": "唤魔师的优雅毯子",
  "Augmenter's Opal Banner": "增辉师的蛋白石旗帜",
  "Draconic Crafter's Table": "龙族工匠的桌子",
  "Wind Rider Roost": "驭风者栖木",
  "Skyhold Spear Rack": "苍穹要塞矛架",
  "Elven Standing Mirror": "精灵落地镜",
  "Statue of Reverent Grace": "Statue of Reverent Grace",
  "Replica Tome of Fel Secrets": "仿制的邪魔之秘魔典",
  "Fungarian Barrel": "Fungarian Barrel",
  "Founder's Point Street Sign": "创始者之角街道标牌",
  "Founder's Point Navigation Sign": "创始者之角导航标牌",
  "Devastator's Brazier": "湮灭师的火盆",
  "Small Wooden Footstool": "小型木制脚凳",
  "Tusked Weapon Rack": "獠牙武器支架",
  "Empty Orgrimmar Bathtub": "奥格瑞玛空浴盆",
  "Runed Stone Placard": "符文石制铭牌",
  "Trueshot Lodge Weapon Rack": "神射手营地武器架",
  "Replica Tome of the Ancients": "仿制的古树宝典",
  "Ebon Blade Planning Map": "黑锋规划地图",
  "Ebon Blade Tome": "黑锋宝典",
  "Acherus Worktable": "阿彻鲁斯工作台",
  "Ebon Blade Weapon Rack": "黑锋武器架",
  "\"Autumn's Eternal Bliss\" Painting": "“秋日的永恒乐园”画作",
  "\"Heart of Quel'Thalas\" Painting": "“奎尔萨拉斯之心”画作",
  "\"Citadel of Unending Void\" Painting": "“不竭虚空的堡垒”画作",
  "\"Forest's Bulwark\" Painting": "“森林的壁垒”画作",
  "\"The Verdant Underwild\" Painting": "“笼葱地林”画作",
  "Replica Acherus Soul Forge": "仿制的阿彻鲁斯灵魂熔炉",
  "Ebon Blade Banner": "黑锋旗帜",
  "Replica Altar of the Eternal Hunt": "仿制的永恒狩猎祭坛",
  "Unseen Path Archer's Gallery": "隐秘通途射手画廊",
  "Replica Tales of the Hunt": "仿制的狩猎传说",
  "Banner of the Unseen Path": "隐秘通途旗帜",
  "Tirisgarde Candle": "提瑞斯秘法会蜡烛",
  "Tirisgarde War Map": "提瑞斯秘法会战争地图",
  "Tirisgarde Brazier": "提瑞斯秘法会火盆",
  "Dreamweaver Banner": "织梦者旗帜",
  "Seed of Ages Cutting": "纪元之种插枝",
  "Replica Altar of Ancient Kings": "仿制的远古列王祭坛",
  "Silver Hand Banner": "白银之手旗帜",
  "Sanctum of Light Hallway Rug": "圣光秘殿走廊地毯",
  "Replica Libram of Ancient Kings": "仿制的远古列王圣契",
  "Sanctum of Light Candelabra": "圣光秘殿大烛台",
  "Silver Hand Tribute to the Fallen": "白银之手追思供品",
  "Silver Hand Weapon Rack": "白银之手武器架",
  "Tirisgarde Banner": "提瑞斯秘法会旗帜",
  "Founder's Point Gravestone": "创始者之角墓碑",
  "Small Founder's Point Gravestone": "小型创始者之角墓碑",
  "Founder's Point Gravestone Tower": "创始者之角墓碑塔",
  "Large Founder's Point Gravestone": "大型创始者之角墓碑",
  "Netherlight Conclave Voidwell": "虚空之光教团的虚空之泉",
  "Conclave Pedestal": "教团底座",
  "Netherlight Lightwell": "虚空之光的光明之泉",
  "Conjured Altar of the Guardian": "召唤的守护者祭坛",
  "Tome of the Corrupt": "腐化秘典",
  "Vrykul Lord's Throne": "维库领主的王座",
  "Legion's Holo-Communicator": "军团的全息联络器",
  "Hanging Felsteel Chain": "悬挂的魔钢锁链",
  "Legion's Fel Torch": "军团的邪能火炬",
  "Corruption Pit": "腐化之窟",
  "Legion's Fel Brazier": "军团的邪能火盆",
  "Vertical Felsteel Chain": "垂直的魔钢锁链",
  "Forbidden Fork": "Forbidden Fork",
  "Legion Torture Rack": "军团折磨架",
  "Eredar Lord's Fel Torch": "艾瑞达领主的邪能火炬",
  "Tusked Leather Tapestry": "獠牙皮革挂毯",
  "Razorwind Trophy Pelt": "烈风战利品毛皮",
  "Altar of the Corrupted Flames": "堕落烈焰祭坛",
  "Draconic Metalshaper's Anvil": "Draconic Metalshaper's Anvil",
  "Replica Grathardormu's Hammer": "Replica Grathardormu's Hammer",
  "Green Thumb's Watering Can": "Green Thumb's Watering Can",
  "Draconic Auctioneer's Lectern": "Draconic Auctioneer's Lectern",
  "Obsidian Warder Pennant": "Obsidian Warder Pennant",
  "Dark Talon Pennant": "Dark Talon Pennant",
  "Roasted Ram Leg": "Roasted Ram Leg",
  "Draconic Trader's Cart": "Draconic Trader's Cart",
  "Artisan's Measuring Scales": "Artisan's Measuring Scales",
  "War Creche Teaching Crystal": "War Creche Teaching Crystal",
  "Ancient Weyrn Device": "上古阅兵装置",
  "Silvermoon Privacy Screen": "Silvermoon Privacy Screen",
  "Crimson Lightwood Screen": "Crimson Lightwood Screen",
  "Uncrowned Apothecary's Cabinet": "无冕者药剂师的柜子",
  "Uncrowned Apothecary's Supplies": "无冕者药剂师的补给",
  "Uncrowned Banner": "无冕者旗帜",
  "Uncrowned Planning Table": "无冕者规划桌",
  "Replica Crucible of the Uncrowned": "仿制的无冕者锻炉",
  "Stolen Copy of the Blood Ledger": "偷来的血腥帐簿副本",
  "Netherlight Conclave Banner": "虚空之光教团旗帜",
  "Replica Altar of Light and Shadow": "仿制的光影祭坛",
  "Replica Word of the Conclave": "仿制的教团箴言",
  "Scroll of the Conclave": "教团卷轴",
  "Draconic Crafter's Forge": "龙族工匠的熔炉",
  "Small Razorwind Bar Table": "小型烈风酒吧桌",
  "Elemental Altar of the Maelstrom": "大漩涡的元素祭坛",
  "Replica Words of Wind and Earth": "仿制的风与地之书",
  "Pedestal of the Maelstrom's Wisdom": "大漩涡智慧座台",
  "Farseer's Furs": "先知的毛皮",
  "Maelstrom Banner": "大漩涡旗帜",
  "Horned Hanging Sconce": "犄角悬挂灯台",
  "Painted Wood Scraps": "彩绘碎木",
  "Painted Wood Scrap Pile": "彩绘碎木堆",
  "Cenarion Arch": "塞纳里奥圆拱",
  "Earthen Ring Scouting Map": "大地之环侦察地图",
  "Maelstrom Chimes": "大漩涡风铃",
  "Bel'ameth Traveler's Pack": "贝拉梅斯旅行者的包裹",
  "Shadowmoon Open-Air Shed": "影月开放式棚屋",
  "Draenic Fencepost": "德莱尼栅栏桩",
  "Draenic Ottoman": "德莱尼搁脚凳",
  "Pandaren Wooden Cart": "Pandaren Wooden Cart",
  "Commander's Kafa Mug": "Commander's Kafa Mug",
  "Ceramic Kafa Mug": "Ceramic Kafa Mug",
  "Dalaran Kafa Grinder": "Dalaran Kafa Grinder",
  "Embroidered Embaari Tent": "镶边安波里帐篷",
  "Draenic Wooden Table": "德莱尼木制桌子",
  "Square Draenic Table": "方形德莱尼桌子",
  "Shadowmoon Greenhouse": "影月温室",
  "Draenic Wooden Wall Shelf": "德莱尼木制壁挂架子",
  "Elodor Armory Rack": "艾洛多尔军械架",
  "Draenei Stargazer's Telescope": "德莱尼观星者的望远镜",
  "Draenethyst Lantern": "德拉诺水晶灯笼",
  "\"Dawning Hope\" Mosaic": "“晨光希望”镶嵌",
  "Small Karabor Fountain": "小型卡拉波喷泉",
  "Moon-Blessed Barrel": "月福之桶",
  "Draenic Basin": "德莱尼盆子",
  "Telredor Recliner": "泰雷多尔躺椅",
  "Razorwind Cooking Grill": "烈风烹饪烤架",
  "Argussian Circular Rug": "阿古斯圆形毯子",
  "Draenei Farmer's Trellis": "德莱尼农夫的篱笆",
  "Draenic Fence": "德莱尼栅栏",
  "Emblem of the Naaru's Blessing": "纳鲁祝福纹章",
  "Draenethyst Sconce": "德拉诺水晶灯台",
  "Grand Draenethyst Lamp": "大型德拉诺水晶灯具",
  "Netherlight Command Map": "虚空之光指挥地图",
  "Tusked Weapon Stand": "獠牙武器架",
  "Jagged Orgrimmar Trellis": "锯齿奥格瑞玛栅栏",
  "Hide-Covered Bench": "铺着毛皮的长椅",
  "Draenic Forge": "德莱尼熔炉",
  "Draenethyst Lamppost": "德拉诺水晶路灯",
  "Large Karabor Fountain": "大型卡拉波喷泉",
  "Draenethyst String Lights": "德拉诺水晶串灯",
  "Sentinel's Moonwing Gaze": "哨兵的月翼凝视",
  "Fel Fountain": "邪能喷泉",
  "Test Decor": "Test Decor",
  "Fungarian Banner": "Fungarian Banner",
  "Hide-Covered Wall Shelf": "铺着毛皮壁挂架子",
  "Tusked Chandelier": "獠牙吊灯",
  "Tusked Sconce": "獠牙灯台",
  "Wolf Pelt Rug": "狼裘毯",
  "Fungarian Sack": "Fungarian Sack",
  "Elegant Elven Chandelier": "优雅的精灵吊灯",
  "Wooden Planter Pot": "木制花盆",
  "Wooden Planter Row": "木制花槽",
  "Founder's Point Fence": "创始者之角栅栏",
  "Long Founder's Point Fence": "创始者之角加长栅栏",
  "Razorwind Wheelbarrow": "烈风独轮车",
  "Ornate Ironforge Bench": "华丽的铁炉堡长椅",
  "Boralus Barrel": "伯拉勒斯桶",
  "Tidesage's Bookcase": "海贤书柜",
  "Covered Wooden Desk": "遮盖的木制书桌",
  "Sturdy Wooden Desk": "牢固的木制书桌",
  "Open Sack of Roasted Kafa": "敞口的烘焙咔啡袋",
  "Sealed Sack of Roasted Kafa": "密封的烘焙咔啡袋",
  "Dalaran Espresso Machine": "达拉然浓缩咖啡机",
  "Admiralty's Upholstered Chair": "海军部的软垫座椅",
  "Boralus Fence": "伯拉勒斯栅栏",
  "Boralus Fencepost": "伯拉勒斯栅栏桩",
  "Proudmoore Shipping Crate": "普罗德摩尔货运箱",
  "Small Hull'n'Home Table": "小型船壳为家桌子",
  "Large Hull'n'Home Table": "大型船壳为家桌子",
  "Admiral's Chandelier": "海军统帅的吊灯",
  "Hull'n'Home Dresser": "船壳为家衣柜",
  "Bowhull Bookcase": "船艏书柜",
  "Brennadam Coop": "布伦纳丹鸡窝",
  "Admiralty's Copper Lantern": "海军部的青铜灯笼",
  "Brennadam Grinder": "布伦纳丹绞肉机",
  "Stormsong Water Pump": "斯托颂水泵",
  "Stormsong Stove": "斯托颂炉子",
  "Tiragarde Emblem": "提拉加德纹章",
  "Boralus Bookshelf": "伯拉勒斯书架",
  "Tidesage's Double Bookshelves": "海贤的双面书柜",
  "Admiral's Bed": "海军统帅的床",
  "Hull'n'Home Chair": "船壳为家椅子",
  "Admiral's Low-Hanging Chandelier": "海军统帅的低垂吊灯",
  "Green Boralus Market Tent": "绿色伯拉勒斯集市帐篷",
  "Founder's Point Framed Torch": "创始者之角框饰火炬",
  "Long Old Founder's Point Fence": "旧创始者之角加长栅栏",
  "Old Founder's Point Fence": "旧创始者之角栅栏",
  "Founder's Point Fencepost": "创始者之角栅栏桩",
  "Old Founder's Point Fencepost": "旧创始者之角栅栏桩",
  "Founder's Point Waterwheel": "创始者之角水车",
  "Broken Founder's Point Fence": "破损的创始者之角栅栏",
  "Old Broken Founder's Point Fence": "破损的旧创始者之角栅栏",
  "Plush Cushioned Chair": "绒毛衬垫椅子",
  "Copper Stormsong Well": "青铜斯托颂水晶",
  "Tiragarde Treasure Chest": "提拉加德藏宝箱",
  "Proudmoore Green Drape": "普罗德摩尔绿色窗帘",
  "Copper Tidesage's Sconce": "青铜海贤灯台",
  "Tied-Right Leather Curtains": "紧缚的皮革窗帘",
  "Founder's Point Front Door": "创始者之角前门",
  "\"The High Exarch\" Painting": "“大主教”画作",
  "\"The Ranger of the Void\" Painting": "“虚空游侠”画作",
  "\"The Harbinger\" Painting": "“先驱”画作",
  "\"The Redeemer\" Painting": "“救赎者”画作",
  "Demonic Storage Chest": "恶魔储物箱",
  "Seaworthy Boralus Bell": "适航伯拉勒斯船钟",
  "Dornogal Framed Rug": "多恩诺嘉尔框饰地毯",
  "Stonelight Countertop": "石光柜台",
  "Boulder Springs Recliner": "硌石之泉躺椅",
  "Boulder Springs Hot Tub": "硌石之泉澡盆",
  "Founder's Point Standing Torch": "创始者之角立式火炬",
  "Razorwind Banded Planter": "烈风箍边花盆",
  "Earthen Etched Throne": "土灵蚀刻王座",
  "Freywold Bench": "芙原长椅",
  "Dornogal Bookcase": "多恩诺嘉尔书柜",
  "Rambleshire Resting Platform": "漫林郡休息台",
  "Fallside Lantern": "陡坡灯笼",
  "Freywold Seat": "芙原座椅",
  "Freywold Table": "芙原桌子",
  "Dornogal Brazier": "多恩诺嘉尔火盆",
  "Dornogal Hanging Lantern": "多恩诺嘉尔悬挂灯笼",
  "Dornogal Hanging Sconce": "多恩诺嘉尔悬挂灯台",
  "Coreway Sentinel Lamppost": "心核隧途哨兵路灯",
  "Earthen Chain Wall Shelf": "土灵饰链壁挂架子",
  "Fallside Storage Tent": "陡坡储藏帐篷",
  "Algari Fence": "阿加栅栏",
  "Algari Fencepost": "阿加栅栏桩",
  "Freywold Fountain": "芙原喷泉",
  "Forgeground Market Bins": "铸炉园集市桶",
  "Earthen Storage Crate": "土灵储物箱",
  "Meadery Storage Chest": "酒庄储物箱",
  "Earthen Contender's Target": "土灵挑战者的靶子",
  "Replica Awakening Machine Stasis Pod": "仿制的觉醒主机静滞舱",
  "Gundargaz Grand Keg": "冈达加兹大桶",
  "Meadery Storage Barrel": "酒庄储物桶",
  "Dried Gilnean Roses": "Dried Gilnean Roses",
  "Hyjal Climbing Vine": "Hyjal Climbing Vine",
  "Ancient Zandalari Ritual Scroll": "Ancient Zandalari Ritual Scroll",
  "Pylon Fragment": "Pylon Fragment",
  "Inactive Filigree Moon Lamp": "Inactive Filigree Moon Lamp",
  "Ornamental Proudmoore Anchor": "Ornamental Proudmoore Anchor",
  "Elegant Elven Canopy Bed": "优雅的精灵华盖床",
  "Gemmed Elven Chest": "嵌宝精灵箱",
  "Reliquary Tent": "神圣遗物学会帐篷",
  "Horde Warlord's Throne": "部落督军的王座",
  "Bel'ameth Front Door": "贝拉梅斯前门",
  "Tirisfal Hollow Campfire": "提瑞斯法空洞营火",
  "Blightfire Candle": "疫火蜡烛",
  "Replica Rumbling Wastes Drill Pod": "仿制的响岩废土钻机",
  "Gundargaz Candelabra": "冈达加兹大烛台",
  "Thalassian Chest": "Thalassian Chest",
  "Astalor's Hookah": "Astalor's Hookah",
  "590 Quel'Lithien Red Display Bottle": "590 Quel'Lithien Red Display Bottle",
  "Thalassion Academy Dictation Device": "Thalassion Academy Dictation Device",
  "Sin'dorei Wine Display": "Sin'dorei Wine Display",
  "Goldshire Wardrobe": "闪金镇衣橱",
  "Iskaaran Open-Air Tent": "伊斯卡拉开放式帐篷",
  "Iskaaran Smith's Anvil": "伊斯卡拉铁匠的铁砧",
  "Iskaaran Cookpot": "伊斯卡拉烹饪锅",
  "Iskaaran Hanging Lampfish": "伊斯卡拉悬挂灯鱼",
  "Iskaaran Hanging Lantern": "伊斯卡拉悬挂灯笼",
  "Iskaaran Standing Lantern": "伊斯卡拉立式灯笼",
  "Tuskarr Meditative Incense Burner": "海象人冥思焚香炉",
  "Tuskarr Crabber's Basket": "海象人捕蟹篮",
  "Fur-Adorned Iskaaran Worktable": "毛皮装饰的伊斯卡拉工作台",
  "Tuskarr Postbag": "海象人邮包",
  "Finned Iskaaran Teapot": "带鳍的伊斯卡拉茶壶",
  "Iskaaran Charcuterie Board": "伊斯卡拉熟食板",
  "Big Kinook's Legendary Soup Pot": "大个子基努克的传奇汤锅",
  "Arch of Iskaara": "伊斯卡拉之拱",
  "Scarred Orcish Spear": "Scarred Orcish Spear",
  "Clefthoof Hide Rug": "Clefthoof Hide Rug",
  "Weathered History of the Warchiefs": "Weathered History of the Warchiefs",
  "Sandy Vulpera Tapestry": "Sandy Vulpera Tapestry",
  "Short Wooden Cabinet": "矮式木制柜子",
  "Coal-Fired Stovetop": "燃煤炉灶",
  "Sturdy Wooden Washbasin": "牢固的木制脸盆",
  "Sturdy Wooden Bathtub": "牢固的木制浴缸",
  "Banner of the Ebon Blade": "Banner of the Ebon Blade",
  "Artisanal Display Tent": "Artisanal Display Tent",
  "Eversong Crystal Glass": "Eversong Crystal Glass",
  "590 Quel'Lithien Red": "590奎尔林斯红酒",
  "\"Silvermoon in Summer\" Painting": "\"Silvermoon in Summer\" Painting",
  "\"The Last Day of the Semester\" Painting": "\"The Last Day of the Semester\" Painting",
  "\"A Bridge Over Calm Waters\" Painting": "\"A Bridge Over Calm Waters\" Painting",
  "\"Family Portrait\" Painting": "\"Family Portrait\" Painting",
  "\"Brunch and a Book\" Unframed Painting": "\"Brunch and a Book\" Unframed Painting",
  "\"Eversong in Bloom\" Painting": "\"Eversong in Bloom\" Painting",
  "\"Nature's Strength\" Painting": "\"Nature's Strength\" Painting",
  "\"River's Protectors\" Unframed Painting": "\"River's Protectors\" Unframed Painting",
  "\"Isolation\" Unframed Painting": "\"Isolation\" Unframed Painting",
  "\"The Fallen Protectors\" Unframed Painting": "\"The Fallen Protectors\" Unframed Painting",
  "\"Autumnal Eversong\" Unframed Painting": "\"Autumnal Eversong\" Unframed Painting",
  "\"Reclamation\" Unframed Painting": "\"Reclamation\" Unframed Painting",
  "\"Brunch and a Book\" Painting": "\"Brunch and a Book\" Painting",
  "\"Autumnal Eversong\" Painting": "\"Autumnal Eversong\" Painting",
  "\"Isolation\" Painting": "\"Isolation\" Painting",
  "\"Reclamation\" Painting": "\"Reclamation\" Painting",
  "\"The Light Blooms\" Painting": "\"The Light Blooms\" Painting",
  "\"The Fallen Protectors\" Painting": "\"The Fallen Protectors\" Painting",
  "\"River's Protectors\" Painting": "\"River's Protectors\" Painting",
  "Sandy Vulpera Banner": "Sandy Vulpera Banner",
  "Fresh Canvas": "Fresh Canvas",
  "\"The Light Blooms\" Unframed Painting": "\"The Light Blooms\" Unframed Painting",
  "Sin'dori Artisan's Easel": "Sin'dori Artisan's Easel",
  "Small Orgrimmar Tusked Bed": "小型奥格瑞玛獠牙床铺",
  "Razorwind Smith's Hammer": "烈风铁匠的锤子",
  "Razorwind Miner's Pickaxe": "烈风矿工的镐子",
  "Razorwind Woodworker's Hand Saw": "烈风木工的手锯",
  "Razorwind Crafter's Chisel": "烈风工匠的凿子",
  "Razorwind Peon's Shovel": "烈风苦工的铲子",
  "Triple-Tested Steam Valve": "Triple-Tested Steam Valve",
  "Mad Science Blueprints": "Mad Science Blueprints",
  "Safety Electrical Cabling": "Safety Electrical Cabling",
  "Mechagon Control Console": "Mechagon Control Console",
  "Sticky Lever": "黏性拉杆",
  "Dual-Action Turbo Pro Lever": "双动涡轮专业拉杆",
  "Mechanical Gauge": "机械仪表",
  "Dual Mechanical Gauge": "Dual Mechanical Gauge",
  "Lively Pistons": "活力活塞",
  "Sturdy Drive Belt": "Sturdy Drive Belt",
  "Blue-Glo Lantern": "Blue-Glo Lantern",
  "Z-205 Mechanical Device": "Z-205 Mechanical Device",
  "Well-Oiled Machine Cog": "Well-Oiled Machine Cog",
  "Jury-Rigged Electrical Couple": "Jury-Rigged Electrical Couple",
  "Miniature Charging Station": "Miniature Charging Station",
  "Galvanic Storage and Maintenance Device": "Galvanic Storage and Maintenance Device",
  "Small Razorwind Square Table": "小型烈风方桌",
  "Razorwind Logger's Axe": "烈风伐木工的斧子",
  "Ineffective Mechanical Privacy Screen": "Ineffective Mechanical Privacy Screen",
  "Large Razorwind Gazebo": "大型烈风露台",
  "Undermine Mechanic's Hanging Lamp": "安德麦技工的悬挂灯",
  "Undermine Alleyway Sconce": "安德麦小巷灯台",
  "Silvermoon Barrel": "银月城木桶",
  "Elwynn Apple Tree": "艾尔文苹果树",
  "Founder's Point Apple Tree": "创始者之角苹果树",
  "Spring-Powered Pointer": "弹簧式指示牌",
  "Elegant Table Lamp": "优雅的台灯",
  "Gnomish Tesla Tower": "侏儒电磁塔",
  "Moonclasp Satchel": "月扣挎包",
  "Incontinental Table Lamp": "洋际台灯",
  "Razorwind Iron Chandelier": "烈风铁吊灯",
  "Low-Hanging Razorwind Iron Chandelier": "低垂的烈风铁吊灯",
  "Small Jagged Orgrimmar Trellis": "小型锯齿奥格瑞玛栅栏",
  "Razorwind Shores Canoe": "烈风海岸独木舟",
  "Champion Brawler's Gloves": "搏击冠军的手套",
  "Silvermoon Gemmed Chair": "银月城嵌宝椅子",
  "Silvermoon Bench": "银月城长椅",
  "Silvermoon Fencepost": "银月城栅栏桩",
  "Sin'dorei Sleeper": "辛多雷卧铺",
  "Razorwind Shores Front Door": "烈风海岸前门",
  "Draconic Sconce": "龙族灯台",
  "Valdrakken Oven": "瓦德拉肯烤炉",
  "Draconic Scribe's Basin": "龙族铭文师的盆子",
  "Five Flights' Grimoire": "五色巨龙魔典",
  "Silvermoon Fence": "银月城栅栏",
  "Silvermoon Front Door": "银月城前门",
  "Open Rust-Plated Storage Crate": "打开的锈板储物箱",
  "Leftover Undermine Takeout": "吃剩的安德麦外卖",
  "Razorwind Standing Tusk": "烈风立式獠牙",
  "Kharanos Stone Bed": "卡拉诺斯石床",
  "Shadowforge Lamppost": "暗炉路灯",
  "Ornate Dwarven Wardrobe": "华丽的矮人衣柜",
  "Qalashi Goulash": "卡拉希菜炖牛肉",
  "Sunsmoke Censer": "日烟香炉",
  "Razorwind Porch Chair": "烈风门廊椅",
  "Shadowforge Stone Chair": "暗炉石椅子",
  "Wingrest Signal Brazier": "翼眠信号火盆",
  "Valdrakken Hanging Lamp": "瓦德拉肯吊灯",
  "Valdrakken Lamppost": "瓦德拉肯路灯",
  "Valdrakken Hanging Cauldron": "瓦德拉肯悬挂式大锅",
  "Stormwind Forge": "暴风城熔炉",
  "Conjured Archive of the Tirisgarde": "召唤的提瑞斯秘法会档案",
  "Illidari Tent": "伊利达雷帐篷",
  "Replica Hammer of Khaz'goroth": "仿制的卡兹格罗斯之锤",
  "Large Legion Candle": "大号军团蜡烛",
  "Small Legion Candle": "小号军团蜡烛",
  "Replica Chronicle of Ages": "仿制的历代记",
  "Arcan'dor Cutting Fountain": "阿坎多尔插枝喷泉",
  "Nightspire Fountain": "暗夜之塔喷泉",
  "Magistrix's Garden Fountain": "魔导师的花园喷泉",
  "Smoke Lamppost": "烟熏路灯",
  "Gilnean Banded Crate": "吉尔尼斯箍边箱",
  "Small Gilnean Table": "小型吉尔尼斯桌子",
  "Replica Tome of Blighted Implements": "仿制的毁灭利器之书",
  "Tauren Jeweler's Roller": "牛头人珠宝匠的碾轧机",
  "Zandalari War Chandelier": "赞达拉战争吊灯",
  "Pentagonal Valdrakken Tapestry": "五边形瓦德拉肯挂毯",
  "Hash'ey Heartbroth Cauldron": "Hash'ey Heartbroth Cauldron",
  "Empty Amani Cauldron": "Empty Amani Cauldron",
  "Carved Idol of Nalorakk": "Carved Idol of Nalorakk",
  "Carved Idol of Jan'alai": "Carved Idol of Jan'alai",
  "Boiling Amani Cauldron": "Boiling Amani Cauldron",
  "Bronze Banner of the Exiled": "流亡者青铜旗帜",
  "Draenei Smith's Anvil": "德莱尼铁匠的铁砧",
  "Draenei Holo-Dais": "德莱尼全息讲台",
  "Draenei Holo-Path": "德莱尼全息之路",
  "Draenei Crystal Forge": "德莱尼水晶熔炉",
  "Dalaran Runic Anvil": "达拉然符文铁砧",
  "Stoppered Black Potion": "带塞的黑色药水",
  "Gilnean Pitchfork": "吉尔尼斯干草叉",
  "Pandaren Alchemist's Retort": "熊猫人炼金师的蒸馏器",
  "Orcish Felblood Cauldron": "兽人魔血大锅",
  "Starry Scrying Pool": "星光占卜之池",
  "Boralus Bottle Lamp": "伯拉勒斯瓶灯",
  "Zandalari Bottle Shipment": "赞达拉瓶装货物",
  "Aspirant's Meditation Pool": "候选者的冥想池",
  "Bejeweled Venthyr Chalice": "珠光温西尔酒杯",
  "Veil-Secured Animacone": "纱罩固定的心能球果",
  "Sintallow Candles": "罪油蜡烛",
  "Dragon's Elixir Bottle": "巨龙的药剂瓶",
  "Tapestry of the Five Flights": "五色巨龙挂毯",
  "Aldor Stellar Console": "奥尔多星光控制台",
  "Mark of the Mages' Eye": "法师之眼印记",
  "Twilight Fire Canister": "暮光火焰之罐",
  "Pandaren Table Lamp": "熊猫人台灯",
  "Intense Mogu Brazier": "魔古烈燃火盆",
  "Venthyr Anima Bottle": "温西尔心能瓶",
  "Razorwind Covered Well": "烈风带顶水井",
  "Apothecary's Worktable": "药剂师的工作台",
  "Stampwhistle's Postal Portal": "印哨的邮政传送门",
  "Nerubian Alchemist's Retort": "蛛魔炼金师的蒸馏器",
  "Naaru Crystal Icon": "纳鲁水晶圣像",
  "Tale of the Penultimate Lich King": "倒数第二位巫妖王的传说",
  "Large Brazier of Elune": "大型艾露恩火盆",
  "Drained Dark Heart of Galakrond": "枯竭的迦拉克隆幽暗之心",
  "Scroll of K'aresh's Fall": "卡雷什陨落卷轴",
  "Tome of the Survivor": "幸存者宝典",
  "Slate Cobblestone Pair": "板岩卵石对",
  "Slate Cobblestone": "板岩卵石",
  "Iron-Reinforced Wooden Window": "钢铁加固的木制窗户",
  "Slate Cobblestone Path": "板岩卵石路",
  "Slate Cobblestone Trio": "板岩卵石三联组",
  "Suramar Stepping Stone": "苏拉玛踏脚石",
  "Zandalari War Torch": "赞达拉战争火炬",
  "Trueshot Lodge Food Nook": "神射手营地食物角",
  "Replica Saga of the Valarjar": "仿制的瓦拉加尔的传说",
  "Tauren Storyteller's Frame": "牛头人说书人画框",
  "\"Portrait of the Artist as a Young Goblin\" Painting": "“一个青年地精艺术家的画像”画作",
  "Zandalari War Brazier": "赞达拉战争火盆",
  "Highmountain Tanner's Frame": "至高岭制革匠画框",
  "Skyhorn Banner": "天角旗帜",
  "\"Unity of Thorns\" Tapestry": "“荆棘的统一”挂毯",
  "Maelstrom Lava Lamp": "大漩涡熔岩灯",
  "Pyrewood Glass Bottle": "焚木玻璃瓶",
  "Baradin Bay Fishing Rack": "巴拉丁海湾渔具架",
  "Smoke Lamp": "烟熏灯",
  "Standing Smoke Lamp": "立式烟熏灯",
  "Stoppered Gilnean Barrel": "带塞的吉尔尼斯木桶",
  "Ornate Sin'dorei Sconce": "华丽的辛多雷灯台",
  "Sin'dorei Crafter's Forge": "辛多雷工匠的熔炉",
  "Silvermoon Spire Fountain": "银月城尖塔喷泉",
  "Bejeweled Silvermoon Chandelier": "珠光银月城吊灯",
  "Gilded Sunfury Chair": "鎏金日怒椅子",
  "\"That Thing What You've Always Needed\" Advertisement": "“你一直需要的那玩意儿”广告",
  "Suramar Stepping Stone Set": "苏拉玛踏脚石套组",
  "Small Gilnean Windmill": "小型吉尔尼斯风车",
  "Elegant Padded Chaise": "优雅的软垫躺椅",
  "Open Elegant Elven Barrel": "打开的优雅精灵木桶",
  "Elegant Curved Table": "优雅的弧形桌子",
  "Snowfall Tribe Scare-Totem": "飘雪部族威吓图腾",
  "Gilnean Green Potion": "吉尔尼斯绿色药水",
  "Gilnean Postbox": "吉尔尼斯邮箱",
  "Gilnean Map": "吉尔尼斯地图",
  "Skyhorn Arrow Kite": "天角箭头风筝",
  "Hanging Arrow Kite": "悬挂箭头风筝",
  "Skyhorn Eagle Kite": "天角雄鹰风筝",
  "Bloodtotem Banner": "鲜血图腾旗帜",
  "Camp Narache Rug": "纳拉其营地地毯",
  "Dalaran Kafa Press": "达拉然咔啡压榨机",
  "Scaled Twilight Mosaic": "鳞饰暮光拼贴",
  "Gnomeregan Recyli-Kiln": "诺莫瑞根循环窑",
  "Nazjatar Framing Post": "纳沙塔尔框架柱",
  "Spirit Anemones": "灵魂海葵",
  "Elegant Silvermoon Dessert Tray": "优雅的银月城甜品盘",
  "Eversong Party Platter": "永歌宴会拼盘",
  "Empty Lorewalker's Bookcase": "游学者的空书柜",
  "Orgrimmar Bathtub": "奥格瑞玛浴盆",
  "Outland Mag'har Banner": "外域玛格汉旗帜",
  "Arakkoa Decoy Scarecrow": "鸦人诱饵稻草人",
  "Talon King's Totem": "利爪之王图腾",
  "Draenei Holo-Projector Pedestal": "德莱尼全息投影基座",
  "Tempest Keep Cryo-Pod": "风暴要塞冷冻舱",
  "Draenei Weaver's Loom": "德莱尼织工的织布机",
  "Draenei Transmitter": "德莱尼发射器",
  "Crystal Signpost": "水晶路标",
  "Gilded Draenei Round Table": "鎏金德莱尼圆桌",
  "Aldor Bookcase": "奥尔多书柜",
  "Shattrath Sconce": "沙塔斯灯台",
  "Shattrath Lamppost": "沙塔斯路灯",
  "Grand Drape of the Exiles": "华美的流亡者帷幔",
  "Silver Dalaran Bench": "银色达拉然长椅",
  "Dalaran Post": "达拉然立柱",
  "Wolvar Postbag": "狼獾人邮包",
  "Gilded Dalaran Banner": "鎏金达拉然旗帜",
  "Dalaran Scholar's Bookcase": "达拉然学者的书柜",
  "Kirin Tor Sun Chandelier": "肯瑞托太阳吊灯",
  "Kirin Tor Crate": "肯瑞托板条箱",
  "Dalaran Street Sign": "达拉然街道标志",
  "Kirin Tor Glass Table": "肯瑞托玻璃桌",
  "San'layn Blood Orb": "萨莱因鲜血宝珠",
  "Icecrown Plague Canister": "冰冠天灾之罐",
  "Pandaren Alchemist's Kit": "熊猫人炼金工具包",
  "Halaa Bench": "哈兰长椅",
  "Reconstructed Mogu Lightning Drill": "重建的魔古闪电钻机",
  "Driftwood Barrel": "浮木桶",
  "Murloc Driftwood Hut": "鱼人浮木小屋",
  "Driftwood Junk Pile": "浮木杂物堆",
  "Shellscale Standard": "壳鳞军旗",
  "Murloc's Wind Chimes": "鱼人风铃",
  "Dalaran Display Shelves": "达拉然陈列架",
  "Failed Failure Detection Pylon": "失效的故障检测水晶塔",
  "Dalaran Auto-Hammer": "达拉然自动铁锤",
  "Suramar Jeweler's Assortment": "苏拉玛珠宝匠的全套工具",
  "Naga's Scale Bag": "纳迦的鳞片袋",
  "Azshara's Eternal Prize": "艾萨拉的永恒奖赏",
  "Azsharan Brazier": "艾萨拉火盆",
  "Aspiring Soul's Chair": "上进之魂的椅子",
  "Ardenweald Lamppost": "炽蓝仙野路灯",
  "Maldraxxian Crate": "玛卓克萨斯板条箱",
  "Tome of Maldraxxian Rituals": "玛卓克萨斯仪式之书",
  "Kyrian Anima Barrel": "格里恩心能之桶",
  "Hollow Night Fae Shrine": "空洞的法夜圣殿",
  "Broker's Hex Table": "掮灵的妖术桌",
  "Ardenweald Hanging Baskets": "炽蓝仙野吊篮",
  "Large Revendreth Storage Crate": "大型雷文德斯储物箱",
  "Margrave's Stitched Leather Rug": "侯爵的缝合皮毯",
  "Cartel Ta Bookcase": "塔财团书柜",
  "Cartel Xy Capture Crate": "赛财团捕获箱",
  "Titanic Tyrhold Fountain": "泰坦提尔要塞喷泉",
  "Kobold Digger's Chair": "狗头人矿工的椅子",
  "Kobold Candle Trio": "狗头人蜡烛三联组",
  "Kobold Wagon": "狗头人货车",
  "Candle-Festooned Wooden Awning": "蜡烛点缀的木制遮篷",
  "Waxmaster's Candle Rack": "塑蜡大师的蜡烛架",
  "Thunder Bluff Totem": "Thunder Bluff Totem",
  "Carved Idol of Halazzi": "Carved Idol of Halazzi",
  "Kirin Tor Skyline Banner": "肯瑞托天际旗帜",
  "Hanging Felsteel Cage": "魔钢吊笼",
  "Sparse Razorwind Fisher's Rack": "冷清的烈风渔夫晒架",
  "Gilnean Washing Line": "吉尔尼斯晾衣绳",
  "Pandaren Fishing Net": "熊猫人渔网",
  "Beloved Elekk Plushie": "心爱的毛绒雷象",
  "Flying Skyhorn Eagle Kite": "飞翔的天角雄鹰风筝",
  "K'areshi Warp Platform": "卡雷什迁跃平台",
  "Razorwind Fisher's Rack": "烈风渔夫晒架",
  "Naakroan Brazier": "纳克罗安火盆",
  "Shadowguard Collection Pylon": "影卫采集晶塔",
  "K'areshi Protectorate Portal": "卡雷什维序派传送门",
  "Shadowguard Energy Siphon": "影卫能量虹管",
  "Burning Amani Pinecone": "Burning Amani Pinecone",
  "Beloved Raptor Plushie": "心爱的毛绒迅猛龙",
  "Sandfury Diplomat's Banner": "沙怒外交官的旗帜",
  "Tidesage's Totem": "海贤图腾",
  "Drust Enchanter's Rod": "德鲁斯特附魔师的魔棒",
  "Kyrian Aspirant's Rolled Cushion": "格里恩候选者的滚边软垫",
  "Elwynn Autumn Apple Tree": "艾尔文秋季苹果树",
  "Founder's Point Autumn Apple Tree": "创始者之角秋季苹果树",
  "Razorwind River Paddle": "烈风涉川桨",
  "Tusk-Adorned Stitched Rug": "獠牙装饰的缝补毯子",
  "Small Stitched Rug": "小型缝补毯子",
  "Ethereal Pipe Segment": "虚灵管道段落",
  "Angled Ethereal Pipe Segment": "斜角虚灵管道段落",
  "Long Ethereal Pipe Segment": "加长虚灵管道段落",
  "Corner Ethereal Pipe Segment": "拐角虚灵管道段落",
  "Empty Wooden Bathtub": "空的木桶浴缸",
  "Glorious Pendant of Rukhmar": "鲁克玛的辉煌吊坠",
  "Writings of Reshad the Outcast": "流亡者瑞沙德的文稿",
  "Scroll of the Adherent": "信徒的卷轴",
  "Arakkoan Alchemy Tools": "鸦人炼金工具",
  "Skyreach Circular Table": "通天峰圆形桌子",
  "High Arakkoan Library Shelf": "高等鸦人的图书架子",
  "High Arakkoan Alchemist's Shelf": "高等鸦人的炼金架子",
  "High Arakkoan Shelf": "高等鸦人的架子",
  "\"Rising Glory of Rukhmar\" Statue": "“鲁克玛的飞升荣光”雕像",
  "Uncorrupted Eye of Terokk": "未腐化的泰罗克之眼",
  "Hull'n'Home Window": "船壳为家窗户",
  "Exposed Corner Ethereal Pipe Segment": "暴露的拐角虚灵管道段落",
  "Exposed Long Ethereal Pipe Segment": "暴露的加长虚灵管道段落",
  "Exposed Intersecting Ethereal Pipe Segment": "暴露的交叉虚灵管道段落",
  "Reinforced Corner Ethereal Pipe Segment": "加固的拐角虚灵管道段落",
  "Exposed Angled Ethereal Pipe Segment": "暴露的斜角虚灵管道段落",
  "Brawler's Guild Punching Bag": "搏击俱乐部沙袋",
  "Rolled Razorwind Leathers": "卷起的烈风皮革",
  "Low-Hanging Razorwind Ropes": "低垂的烈风垂挂绳索",
  "Knotted Hanging Razorwind Ropes": "打结的烈风垂挂绳索",
  "Tusked Hanging Razorwind Ropes": "獠牙烈风垂挂绳索",
  "Plain Hanging Razorwind Ropes": "朴素烈风垂挂绳索",
  "Adorned Hanging Razorwind Ropes": "装饰的烈风垂挂绳索",
  "Lightly Adorned Hanging Razorwind Ropes": "稍加装饰的烈风垂挂绳索",
  "Visage of Akil'zon": "Visage of Akil'zon",
  "Valdrakken Bookcase": "瓦德拉肯书柜",
  "Large Razorwind Farmer's Hay Pile": "大型烈风农夫干草堆",
  "Razorwind Farmer's Hay Pile": "烈风农夫干草堆",
  "Small Razorwind Farmer's Hay Pile": "小型烈风农夫干草堆",
  "Visage of Nalorakk": "Visage of Nalorakk",
  "Visage of Halazzi": "Visage of Halazzi",
  "Visage of Jan'alai": "Visage of Jan'alai",
  "Brazier of Elune": "艾露恩的火盆",
  "Cartel Collector's Cage": "财团收藏家的笼子",
  "Arathi Bartender's Shelves": "阿拉希酒保的架子",
  "Replica Libram of the Dead": "仿制的死亡圣契",
  "Kobold Trassure Pile": "狗头人“宝物”堆",
  "Maldraxxian Runic Tablet": "Maldraxxian Runic Tablet",
  "Gob-chanical Trash Heap": "地精机械垃圾堆",
  "Red Razorwind Paintbrush": "Red Razorwind Paintbrush",
  "Dry Razorwind Grass Patch": "Dry Razorwind Grass Patch",
  "Alliance Doormat": "Alliance Doormat",
  "Horde Doormat": "Horde Doormat",
  "Uncrowned Market Stall": "Uncrowned Market Stall",
  "The Dark Portal": "The Dark Portal",
  "Draenei Crystal Chandelier": "德莱尼水晶吊灯",
  "Lush Telogrus Carpet": "Lush Telogrus Carpet",
  "Riftstone": "Riftstone",
  "Entropic Illuminant": "Entropic Illuminant",
  "Haranir Preserving Agents": "Haranir Preserving Agents",
  "Embossed Sin'dorei Fur Rug": "Embossed Sin'dorei Fur Rug",
  "Ensorcelled Broom": "Ensorcelled Broom",
  "Gilded Silvermoon Anvil": "Gilded Silvermoon Anvil",
  "Masterwork Crafting Hammer": "Masterwork Crafting Hammer",
  "Gilded Thalassian Armillary": "Gilded Thalassian Armillary",
  "Shining Sin'dorei Hourglass": "Shining Sin'dorei Hourglass",
  "Font of Gleaming Water": "Font of Gleaming Water",
  "Ornamental Silvermoon Hanger": "Ornamental Silvermoon Hanger",
  "Gilded Silvermoon Hanger": "Gilded Silvermoon Hanger",
  "Animated Sin'dorei Pick": "Animated Sin'dorei Pick",
  "Animated Sin'dorei Hammer": "Animated Sin'dorei Hammer",
  "Ren'dorei Anvil": "Ren'dorei Anvil",
  "Dark Void Inkwell": "Dark Void Inkwell",
  "Cosmic Void Ashwell": "Cosmic Void Ashwell",
  "Floating Void-Touched Tome": "Floating Void-Touched Tome",
  "Ren'dorei Stargazer": "Ren'dorei Stargazer",
  "Void Elf Table": "Void Elf Table",
  "Void Elf Round Table": "Void Elf Round Table",
  "Ren'dorei Postal Repository": "Ren'dorei Postal Repository",
  "Brilliant Phoenix Harp": "Brilliant Phoenix Harp",
  "Spellbound Tome of Thalassian Magics": "Spellbound Tome of Thalassian Magics",
  "Bejeweled Sin'dorei Lyre": "Bejeweled Sin'dorei Lyre",
  "Simple Haranir Table": "朴素哈籁尼尔桌子",
  "Rootflame Campfire": "Rootflame Campfire",
  "Luxurious Silvermoon Lounge Cushion": "Luxurious Silvermoon Lounge Cushion",
  "Plush Silvermoon Bed": "Plush Silvermoon Bed",
  "Chic Silvermoon Pillow": "Chic Silvermoon Pillow",
  "Homely Sin'dorei Shelf": "Homely Sin'dorei Shelf",
  "Homely Wall Shelves": "Homely Wall Shelves",
  "Gilded Eversong Book": "Gilded Eversong Book",
  "Opened Sin'dorei Scroll": "Opened Sin'dorei Scroll",
  "Silvermoon Curtains": "Silvermoon Curtains",
  "Stitched Haranir Rug": "Stitched Haranir Rug",
  "Wild Hanging Scroll": "Wild Hanging Scroll",
  "Ren'dorei Warp Orb": "Ren'dorei Warp Orb",
  "Void Elf Throne": "Void Elf Throne",
  "Void Elf Stool": "Void Elf Stool",
  "Void Elf Floating Lantern": "Void Elf Floating Lantern",
  "Voidstrider Saddlebag": "Voidstrider Saddlebag",
  "Sturdy Ren'dorei Cask": "Sturdy Ren'dorei Cask",
  "Replica Haranir Mural": "Replica Haranir Mural",
  "Harandar Runestone": "Harandar Runestone",
  "Sin'dorei Phoenix Quill": "Sin'dorei Phoenix Quill",
  "Lively Songwriter's Quill": "Lively Songwriter's Quill",
  "Ren'dorei Crafting Framework": "Ren'dorei Crafting Framework",
  "Ren'dorei Void Projector": "Ren'dorei Void Projector",
  "Replica Forge of the Roaring Mountain": "仿制的啸山熔炉",
  "Kyrian Floating Lamp": "格里恩漂浮灯盏",
  "Complete Guide to K'areshi Wrappings, Vol. 11": "Complete Guide to K'areshi Wrappings, Vol. 11",
  "K'areshi Holo-Crystal Projector": "K'areshi Holo-Crystal Projector",
  "K'areshi Incense Burner": "K'areshi Incense Burner",
  "Oath Scale": "Oath Scale",
  "Small Telogrus Lamp": "小型泰洛古斯灯具",
  "Restful Bronze Bench": "宁静的青铜长椅",
  "Consortium Glowpost": "Consortium Glowpost",
  "Harandar Anvil": "Harandar Anvil",
  "Tazaveshi Hookah ": "Tazaveshi Hookah ",
  "Tattered Vanguard Banner": "Tattered Vanguard Banner",
  "Haranir Pennant": "Haranir Pennant",
  "Ward of the Shul'ka": "Ward of the Shul'ka",
  "Brumewood Hollow Grassy Patch": "霾林谷草丛",
  "Brumewood Hollow Grassy Spread": "霾林谷草簇",
  "Founder's Point Grassy Patch": "创始者之角草丛",
  "Founder's Point Grassy Spread": "创始者之角草簇",
  "Sturdy Wine Press": "牢固的榨酒桶",
  "Brawler's Barricade": "拳手的路障",
  "Darkmaster's Mystical Brazier": "黑暗院长的玄秘火盆",
  "Magnificent Towering Bookcase": "Magnificent Towering Bookcase",
  "Hanging Dawnflower": "Hanging Dawnflower",
  "Replica Wey'nan's Ward": "Replica Wey'nan's Ward",
  "Haranir Canopy Bed": "Haranir Canopy Bed",
  "Harandar Flowering Lamp": "Harandar Flowering Lamp",
  "Replica Root of the World": "Replica Root of the World",
  "Rootlight Lamppost": "Rootlight Lamppost",
  "Consortium Energy Barrel": "Consortium Energy Barrel",
  "Empty Consortium Energy Barrel": "Empty Consortium Energy Barrel",
  "Consortium Energy Collector": "Consortium Energy Collector",
  "Consortium Energy Crate": "Consortium Energy Crate",
  "Empty Consortium Energy Crate": "Empty Consortium Energy Crate",
  "Consortium Energy Banner": "Consortium Energy Banner",
  "Ren'dorei Lightpost": "Ren'dorei Lightpost",
  "Harandar Glowvine Sconce": "Harandar Glowvine Sconce",
  "Harandar Glowvine Lamppost": "Harandar Glowvine Lamppost",
  "Harandar Glowvine Lantern": "Harandar Glowvine Lantern",
  "Rack of Silvermoon Arms": "Rack of Silvermoon Arms",
  "Crimson Silvermoon Runner": "Crimson Silvermoon Runner",
  "Plum Eversong Rug": "Plum Eversong Rug",
  "Farstrider's Comfy Cushion": "Farstrider's Comfy Cushion",
  "Gilded Lightwood Wardrobe": "Gilded Lightwood Wardrobe",
  "Gilded Sky-Blue Drapery": "Gilded Sky-Blue Drapery",
  "Gentle Floating Planter": "Gentle Floating Planter",
  "Sunlit Glass Mirror": "Sunlit Glass Mirror",
  "Grand Lightwood Table": "Grand Lightwood Table",
  "Ornate Lightwood Table": "Ornate Lightwood Table",
  "Floating Spire Shelf": "Floating Spire Shelf",
  "Sin'dorei Spinning Library": "Sin'dorei Spinning Library",
  "Turning Silvermoon Archives": "Turning Silvermoon Archives",
  "Cuddly  Tan Grrgle": "Cuddly  Tan Grrgle",
  "Cuddly Seafoam Grrgle": "Cuddly Seafoam Grrgle",
  "Cuddly Saffron Grrgle": "Cuddly Saffron Grrgle",
  "Cuddly Sage Grrgle": "Cuddly Sage Grrgle",
  "Cuddly Lavender Grrgle": "Cuddly Lavender Grrgle",
  "Cuddly Pink Grrgle": "Cuddly Pink Grrgle",
  "Cuddly Gold-Colored Grrgle": "Cuddly Gold-Colored Grrgle",
  "Cuddly Lime Grrgle": "Cuddly Lime Grrgle",
  "Cuddly Orange Grrgle": "Cuddly Orange Grrgle",
  "Cuddly Cerulean Grrgle": "Cuddly Cerulean Grrgle",
  "Cuddly Alliance Blue Grrgle": "Cuddly Alliance Blue Grrgle",
  "Cuddly Horde Red Grrgle": "Cuddly Horde Red Grrgle",
  "Cuddly Purple Grrgle": "Cuddly Purple Grrgle",
  "Cuddly Green Grrgle": "Cuddly Green Grrgle",
  "Cuddly Red Grrgle": "Cuddly Red Grrgle",
  "Cuddly Blue Grrgle": "Cuddly Blue Grrgle",
  "Simple Amani Basket": "Simple Amani Basket",
  "Rope-Bound Amani Basket": "Rope-Bound Amani Basket",
  "Razorwind Roofer's Shingle": "烈风盖瓦工的瓦片",
  "Razorwind Roofer's Shingle Pile": "烈风盖瓦工的瓦片堆",
  "Tiny Clump of Hay": "小簇干草",
  "Razorwind Construction Crane": "烈风起重机",
  "Fungal Chest": "Fungal Chest",
  "Delver's Bountiful Coffer": "Delver's Bountiful Coffer",
  "Twilight Tabernacle": "Twilight Tabernacle",
  "Corewarden's Spoils": "Corewarden's Spoils",
  "Root-Wrapped Reliquary": "Root-Wrapped Reliquary",
  "Cenarion Round Rug": "塞纳里奥圆形毯子",
  "Homestone Doormat": "镇宅门毯",
  "Ancient Kaldorei Coffer": "Ancient Kaldorei Coffer",
  "Amani Strongbox": "Amani Strongbox",
  "Harandar Charcuterie Board": "Harandar Charcuterie Board",
  "Blessed Phoenix Egg": "Blessed Phoenix Egg",
  "Dreadscar Battle Planning Map": "恐痕作战规划地图",
  "Lush Haranir Pillow": "Lush Haranir Pillow",
  "Plush Haranir Leather Pillow": "Plush Haranir Leather Pillow",
  "Plush Haranir Blanket": "Plush Haranir Blanket",
  "Eerie Irisdescent Riftshroom": "Eerie Irisdescent Riftshroom",
  "Galactic Void-Scarred Barricade": "Galactic Void-Scarred Barricade",
  "Blossoming Forge": "Blossoming Forge",
  "On'ohia's Call": "On'ohia's Call",
  "Haranir Whistling Arrow": "Haranir Whistling Arrow",
  "Gilded Vigil Post": "Gilded Vigil Post",
  "Sanctified Flame Lantern": "Sanctified Flame Lantern",
  "Rutaani Birdfeeder": "Rutaani Birdfeeder",
  "Rutaani Birdbath": "Rutaani Birdbath",
  "Rutaani Bird Perch": "Rutaani Bird Perch",
  "Amani Dining Table": "Amani Dining Table",
  "Amani Hanging Brazier": "Amani Hanging Brazier",
  "Amani Incense Burner": "Amani Incense Burner",
  "Cosmic Void Training Dummy": "Cosmic Void Training Dummy",
  "Cosmic Void Summoning Crystal": "Cosmic Void Summoning Crystal",
  "Cosmic Void Crate": "Cosmic Void Crate",
  "Cosmic Void Cache": "Cosmic Void Cache",
  "Cosmic Void Gravitational Orb": "Cosmic Void Gravitational Orb",
  "Cosmic Void Orb": "Cosmic Void Orb",
  "Galactic Commander's Orb": "Galactic Commander's Orb",
  "Kun-Lai Lacquered Rickshaw": "昆莱喷漆人力车",
  "Carved Idol of Akil'zon": "Carved Idol of Akil'zon",
  "Golden Pandaren Privacy Screen": "金色熊猫人私密屏风",
  "Thunder Totem Mailbox": "Thunder Totem Mailbox",
  "Void Elf Torch": "Void Elf Torch",
  "Cosmic Void Campfire": "Cosmic Void Campfire",
  "Voidbound Holding Cell": "Voidbound Holding Cell",
  "Devouring Host Ritual Portal": "Devouring Host Ritual Portal",
  "Banded Domanaar Storage Crate": "Banded Domanaar Storage Crate",
  "Imperator's Torment Crystal": "Imperator's Torment Crystal",
  "Voltaic Trigore Egg": "Voltaic Trigore Egg",
  "Devouring Host Ritual Engine": "Devouring Host Ritual Engine",
  "Void Elf Barrel": "Void Elf Barrel",
  "Dalaran Sewer Gate": "达拉然下水道大门",
  "Rolled Scarab Rug": "卷起来的甲虫之毯",
  "Aspirant's Ringed Banner": "候选者的环饰旗帜",
  "Valdrakken Wall Shelf": "瓦德拉肯壁挂架子",
  "Cuddly Seagreen Grrgle": "Cuddly Seagreen Grrgle",
  "Cuddly Brown Grrgle": "Cuddly Brown Grrgle",
  "Cuddly Flaxen Grrgle": "Cuddly Flaxen Grrgle",
  "Cuddly Sanguine Grrgle": "Cuddly Sanguine Grrgle",
  "Cuddly Gumball Grrgle": "Cuddly Gumball Grrgle",
  "Cuddly Violet Grrgle": "Cuddly Violet Grrgle",
  "Cuddly Olive Grrgle": "Cuddly Olive Grrgle",
  "Cuddly Plum Grrgle": "Cuddly Plum Grrgle",
  "Cuddly Tangerine Grrgle": "Cuddly Tangerine Grrgle",
  "Cuddly Sapphire Grrgle": "Cuddly Sapphire Grrgle",
  "Cuddly Clover Grrgle": "Cuddly Clover Grrgle",
  "Cuddly Peach Grrgle": "Cuddly Peach Grrgle",
  "Glazed Sin'dorei Vial": "上釉的辛多雷瓶子",
  "Shadow Council Torch": "暗影议会火把",
  "Resizable All-Purpose Gear": "可变尺寸的全能齿轮",
  "Home Defense Gadget": "家园防御装置",
  "Stranglekelp Sack": "荆棘藻包",
  "Dalaran Sun Sconce": "达拉然太阳灯台",
  "Joybuzz's Joyful Wall of Trains": "乔巴斯的欢乐火车墙",
  "Gilnean Spare Saddle": "吉尔尼斯闲置鞍座",
  "Heart of the Forest Banner": "森林之心旗帜",
  "Arakkoan Alchemist's Bottle": "鸦人炼金师的瓶子",
  "Decorated Underground Table": "Decorated Underground Table",
  "Loamm Bartering Stall": "Loamm Bartering Stall",
  "Ceramic Loamm Bowl": "Ceramic Loamm Bowl",
  "Zaralek Candles": "Zaralek Candles",
  "Loamm Archway": "Loamm Archway",
  "Gooey Niffen Jar": "Gooey Niffen Jar",
  "Zaralek Snail Cart": "Zaralek Snail Cart",
  "Strong Sniffin' Incense": "Strong Sniffin' Incense",
  "Underdecorated Underground Table": "Underdecorated Underground Table",
  "Loamm Wheelpot": "Loamm Wheelpot",
  "Kilnmaster's Bucket": "Kilnmaster's Bucket",
  "Consortium Translocation Portal": "Consortium Translocation Portal",
  "Hearty Niffen Grub": "Hearty Niffen Grub",
  "Loammy Soil": "Loammy Soil",
  "Preyseeker's Magister Trophy": "Preyseeker's Magister Trophy",
  "Preyseeker's Tinker Trophy": "Preyseeker's Tinker Trophy",
  "Preyseeker's Ethereal Trophy": "Preyseeker's Ethereal Trophy",
  "Preyseeker's Breaker Trophy": "Preyseeker's Breaker Trophy",
  "Preyseeker's Amani Trophy": "Preyseeker's Amani Trophy",
  "Preyseeker's Rutaani Trophy": "Preyseeker's Rutaani Trophy",
  "Preyseeker's Vindicator Trophy": "Preyseeker's Vindicator Trophy",
  "Preyseeker's Consul Trophy": "Preyseeker's Consul Trophy",
  "Preyseeker's Executor Trophy": "Preyseeker's Executor Trophy",
  "Preyseeker's Knight-Errant Trophy": "Preyseeker's Knight-Errant Trophy",
  "Preyseeker's Wretched Trophy": "Preyseeker's Wretched Trophy",
  "Preyseeker's Thornspeaker Trophy": "Preyseeker's Thornspeaker Trophy",
  "Preyseeker's Twilight Trophy": "Preyseeker's Twilight Trophy",
  "Preyseeker's Magister Bust": "Preyseeker's Magister Bust",
  "Preyseeker's Tinker Bust": "Preyseeker's Tinker Bust",
  "Preyseeker's Ethereal Bust": "Preyseeker's Ethereal Bust",
  "Preyseeker's Breaker Bust": "Preyseeker's Breaker Bust",
  "Preyseeker's Amani Bust": "Preyseeker's Amani Bust",
  "Preyseeker's Rutaani Bust": "Preyseeker's Rutaani Bust",
  "Preyseeker's Vindicator Bust": "Preyseeker's Vindicator Bust",
  "Preyseeker's Consul Bust": "Preyseeker's Consul Bust",
  "Preyseeker's Executor Bust": "Preyseeker's Executor Bust",
  "Preyseeker's Knight-Errant Bust": "Preyseeker's Knight-Errant Bust",
  "Preyseeker's Wretched Bust": "Preyseeker's Wretched Bust",
  "Preyseeker's Thornspeaker Bust": "Preyseeker's Thornspeaker Bust",
  "Preyseeker's Twilight Bust": "Preyseeker's Twilight Bust",
  "Luxurious Haranir Canopy Bed": "Luxurious Haranir Canopy Bed",
  "Preyseeker's Plinth": "Preyseeker's Plinth",
  "Preyseeker's Ornate Plinth": "Preyseeker's Ornate Plinth",
  "Preyseeker's Ren'dorei Trophy": "Preyseeker's Ren'dorei Trophy",
  "Preyseeker's Farstrider Trophy": "Preyseeker's Farstrider Trophy",
  "Preyseeker's Ren'dorei Bust": "Preyseeker's Ren'dorei Bust",
  "Preyseeker's Farstrider Bust": "Preyseeker's Farstrider Bust",
  "Gleaming March on Quel'Danas Vanquisher's Trophy": "Gleaming March on Quel'Danas Vanquisher's Trophy",
  "Gleaming Dreamrift Vanquisher's Trophy": "Gleaming Dreamrift Vanquisher's Trophy",
  "Gleaming Voidspire Vanquisher's Trophy": "Gleaming Voidspire Vanquisher's Trophy",
  
  "All Subcategories": "所有子分类",
  "Floor": "地板",
  "Food and Drink": "食品和饮料",
  "Misc Accents": "装饰杂项",
  "Ornamental": "装饰品",
  "Wall Hangings": "壁挂装饰",
  "Utility": "效能",
  "Beds": "床铺",
  "Misc Furnishings": "家具杂项",
  "Seating": "座椅",
  "Storage": "储物",
  "Tables and Desks": "桌台",
  "Ambient Lighting": "环境照明",
  "Large Lights": "大型灯具",
  "Misc Lighting": "灯具杂项",
  "Small Lights": "小型灯具",
  "Wall Lights": "壁灯",
  "Miscellaneous - All": "全部杂项",
  "Bushes": "灌木",
  "Large Foliage": "大型植物",
  "Small Foliage": "小型植物",
  "Ground Cover": "地被植物",
  "Doors": "门",
  "Large Structures": "大型结构",
  "Misc Structural": "结构杂项",
  "Walls and Columns": "墙壁和柱子",
  "Windows": "窗户",

  "All Categories": "所有分类",
  "Accents": "点缀",
  "Functional": "功能",
  "Furnishing": "家具",
  "Furnishings": "家具",
  "Lighting": "照明",
  "Miscellaneous": "杂项",
  "Nature": "植被",
  "Structural": "构造",

  "Game Object Proxy": "游戏对象代理",
  "Deprecated": "已弃用",
  "Exterior": "室外",
  "HiddenInCatalog": "在目录中隐藏",
  "Interior": "室内",
  "Can't Remove from Chest": "不可自柜中移除",

  "Colors": "颜色",

  "Budget Cost": "点数",
  "Low": "低",
  "Medium": "中",
  "High": "高",
  "No Budget Cost": "无需点数",

  "Quality": "品质",
  "Epic": "史诗",
  "Rare": "精良",
  "Uncommon": "优秀",
  "QualCommonity": "普通",

  "Dyeable": "染色",
  "Dyeable Items Only": "仅可染色物品",

  "Reagent": "材料",

  "Achievement": "成就",
  "Crafting": "专业制造",
  "Quest": "任务",
  "Filter by Profession": "按专业过滤",
  "Alchemy": "炼金",
  "Blacksmithing": "锻造",
  "Cooking": "烹饪",
  "Enchanting": "附魔",
  "Engineering": "工程学",
  "Inscription": "铭文",
  "Jewelcrafting": "珠宝加工",
  "Leatherworking": "制皮",
  "Tailoring": "裁缝",
  "Encounter": "战斗",
  "Vendor": "商人出售",

  "Blood Elf": "血精灵",
  "Zandalari Troll": "赞达拉巨魔",
  "Bronzebeard Dwarf": "铜须部族",
  "Ironforge": "铁炉堡",
  "Dark Iron Dwarf": "黑铁矮人",
  "Dracthyr": "龙希尔",
  "Draenei": "德莱尼",
  "Dwarven": "矮人",
  "Earthen": "土灵",
  "Dornish": "多恩",
  "Elven": "精灵",
  "Gilnean / Worgen": "吉尔尼斯人/狼人",
  "Gnomish": "侏儒",
  "Goblin": "地精",
  "Haranir": "哈籁尼尔",
  "Human": "人类",
  "Kul Tiran": "库尔提拉斯人",
  "Nightborne": "夜之子",
  "Night Elf": "暗夜精灵",
  "Orcish": "兽人",
  "Pandaren": "熊猫人",
  "Tauren": "牛头人",
  "Troll": "巨魔",
  "Undead": "亡灵",
  "Void Elf": "虚空精灵",
  "Wildhammer Dwarf": "蛮锤部族",

  "Currency": "货币",
  "All Currencies": "全部货币",
  "Money": "钱币",
  "Order Resources": "职业大厅资源",
  "War Resources": "战争物资",
  "Resonance Crystals": "共鸣水晶",
  "Garrison Resources": "要塞物资",
  "Dragon Isles Supplies": "巨龙群岛补给",
  "Apexis Crystal": "埃匹希斯水晶",
  "Honorbound Service Medal": "荣耀战团服役勋章",
  "Energy Cell": "能量电池",
  "S.P.A.R.E. Crate": "S.P.A.R.E.零件箱",
  "Ancient Mana": "远古魔力",
  "Apexis Crystals": "埃匹希斯水晶",
  "Chain Ignitercoil": "连锁点火线圈",
  "Galvanic Oscillator": "电流振荡器",
  "Honor": "荣誉点数",
  "Spare Parts": "备用零件",
  "\"Gold\" Fish": "“金”鱼",
  "Community Coupons": "社区礼券	",
  "Dreamsurge Coalescence": "梦涌凝珠",
  "Elemental Overflow": "元素涌流",
  "Ignitercoil": "点火线圈",
  "Iron Horde Scraps": "钢铁部落碎片",
  "Mysterious Fragment": "迷之碎片",
  "Reservoir Anima": "贮藏心能",
  "Seafarer's Dubloon": "海员达布隆币",
  "Sizzling Cinderpollen": "酷热燧烬花粉",
  "Stygia": "冥殇",
  
  "Faction": "阵营",
  "All Factions": "全部阵营",
  "Arakkoa Outcasts": "鸦人流亡者",
  "Argussian Reach": "阿古斯防卫军",
  "Azerothian Archives": "艾泽拉斯档案馆",
  "Bilgewater Cartel": "锈水财阀",
  "Black Harvest": "黑暗收割议会",
  "Blackwater Cartel": "黑水财阀",
  "Council of Dornogal": "多恩诺嘉尔议会",
  "Council of Exarchs": "主教议会",
  "Darkfuse Solutions": "暗索处理服务",
  "Darnassus": "达纳苏斯",
  "Dragonscale Expedition": "龙鳞探险队",
  "Dreamweavers": "织梦者",
  "Earthen Ring": "大地之环",
  "Ella": "艾拉",
  "Farmer Fung": "农夫老方",
  "Flame's Radiance": "圣焰之耀",
  "Gilneas": "吉尔尼斯",
  "Highmountain Tribe": "高岭部族",
  "Ironforge": "铁炉堡",
  "Jogu the Drunk": "醉鬼贾古",
  "Knights of the Ebon Blade": "黑锋骑士团",
  "Laughing Skulls": "嘲颅兽人",
  "Order of the Cloud Serpent": "云端翔龙骑士团",
  "Orgrimmar": "奥格瑞玛",
  "Proodmoore Admiralty": "普罗德摩尔海军部",
  "Rustbolt Resistance": "锈栓抵抗军",
  "Steamwheedle Cartel": "热砂财阀",
  "Stormwind": "暴风城",
  "Talanji's Expedition": "塔兰吉远征队",
  "The Assembly of the Deeps": "邃渊协盟",
  "The August Celestials": "至尊天神",
  "The Cartels of Undermine": "安德麦财阀",
  "The Golten Lotus": "金莲教",
  "The Honorbound": "荣耀战团",
  "The Lorewalkers": "游学者",
  "The Nightfallen": "堕夜精灵",
  "The Tillers": "阡陌客",
  "Thunder Bluff": "雷霆崖",
  "Tina Mudclaw": "迪娜·泥爪",
  "Undercity": "幽暗城",
  "Valdrakken Accord": "瓦德拉肯联军",
  "Venthyr Covenant": "温西尔盟约",
  "Venture Company": "风险投资公司",
  "Wildhammer Clan": "蛮锤部族",
  "Zandalari Empire": "赞达拉帝国",

  "Expansion": "资料片",
  "All Expansions": "全部资料片",
  "Battle for Azeroth": "争霸艾泽拉斯",
  "Burning Crusade": "燃烧的远征",
  "Cataclysm": "大地的裂变",
  "Classic": "旧世经典",
  "Dragonflight": "巨龙时代",
  "Legion": "军团再临",
  "Midnight": "至暗之夜",
  "Mists of Pandaria": "熊猫人之谜",
  "Shadowlands": "暗影国度",
  "The War Within": "地心之战",
  "Warlords of Draenor": "德拉诺之王",
  "Wrath of the Lich King": "巫妖王之怒",

  "Brewfest": "美酒节",
  "Feast of Winter Veil": "冬幕节",
  "Hallow's End": "万圣节",
  
  "Stormwind": "暴风城",
  "craft crafting crafted profession": "制造/专业",
  
  "Huge": "巨大",
  "Large": "大",
  "Medium": "中",
  "Small": "小",
  "Tiny": "微小",

  "Alliance": "联盟",
  "Bold": "粗犷",
  "Casual": "休闲",
  "Cute": "可爱",
  "Elegant": "优雅",
  "Fae": "精灵",
  "Fall": "秋季",
  "Fel": "邪能",
  "Horde": "部落",
  "Lavish": "奢华",
  "Light": "圣光",
  "Magical": "魔法",
  "Mechanical": "机械",
  "Nature": "自然",
  "Pirate": "海盗",
  "Simple": "简约",
  "Spooky": "阴森",
  "Spring": "春季",
  "Void": "虚空",
  "Whimsical": "怪诞",

  "art artwork painting canvas": "艺术、艺术品、画作、画布",
  "book books tome tomes": "书、书籍、大部头",
  "cabinet cabinets": "橱柜、柜子",
  "chair chairs": "椅子",
  "column columns pillar pillars post": "柱子、柱、立柱",
  "cook cooking oven stove range grill": "烹饪、烤箱、炉子、炉具、烤架",
  "couch couches sofa sofas": "长沙发、沙发",
  "counter counters countertop countertops": "柜台、台面、操作台",
  "cup cups mug mugs tankard stein": "杯、杯子、马克杯、啤酒杯",
  "desk desks": "书桌、桌子",
  "drink drinks beverage beverages": "饮料",
  "fence fences fencing": "栅栏、围栏",
  "food meal feast snack": "食物、餐、大餐、点心",
  "kitchen": "厨房",
  "partition partitions wall walls": "分隔、隔断、墙",
  "rug rugs": "地毯",
  "shelf shelves shelving": "架子、搁板",
  "table tables": "桌子",
  "vases vase": "花瓶",
  "water pond": "水、池塘",

  "Folk": "民间",
  "Holiday/Event": "节日/活动",
  "Opulent": "奢华",
  "Rugged": "粗犷",
  
  "Build Version": "构建版本",
  "Added In Build": "新增于构建版本",
  "All Builds": "全部构建版本",
  
  "Category": "分类",
  "Categories": "分类",
  "Subcategory": "子分类",
  "Flags": "标记",
  "Sources": "来源",
  "Tags": "标签",
  "Culture": "文化",
  "Holiday": "节日",
  "Other": "其他",
  "Size": "尺寸",
  "Style": "风格",
  "Tertiary_Categories": "三级分类",
  "Theme": "主题",

  "art artwork painting canvas": "艺术、艺术品、画作、画布",
  "book books tome tomes": "书、书籍、大部头",
  "cabinet cabinets": "橱柜、柜子",
  "chair chairs": "椅子",
  "column columns pillar pillars post": "柱子、柱、立柱",
  "cook cooking oven stove range grill": "烹饪、烤箱、炉子、炉具、烤架",
  "couch couches sofa sofas": "长沙发、沙发",
  "counter counters countertop countertops": "柜台、台面、操作台",
  "cup cups mug mugs tankard stein": "杯、杯子、马克杯、大啤酒杯",
  "desk desks": "书桌、桌子",
  "drink drinks beverage beverages": "饮料",
  "fence fences fencing": "栅栏、围栏",
  "food meal feast snack": "食物、餐、大餐、点心",
  "kitchen": "厨房",
  "partition partitions wall walls": "分隔、隔断、墙",
  "rug rugs": "地毯",
  "shelf shelves shelving": "架子、搁板",
  "table tables": "桌子",
  "vases vase": "花瓶",
  "water pond": "水、池塘",

  "Home": "主页",
  "Tools": "工具",
  "Item Information": "物品信息",
  "Quick Actions": "快速跳转",
  "View 3D Model": "查看3D模型",
  "Browse Decor": "浏览装饰",
  "Neighborhoods": "住宅区",
  "Neighborhood": "住宅区",
  "Founder's Point": "创始者之角",
  "Razorwind Shores": "烈风海岸",
  "Flight Masters": "飞行管理员",
  "Portals": "传送门",
  "View All": "查看所有",
  "World map": "世界地图",
  "Minimap tiles": "小地图区块",
  "Plots": "地块",
  "Transports": "交通",
  "Back to Browse": "返回浏览页",
  "Feedback": "反馈",
  "Login": "登录",
  "Changelog": "更新日志",
  "Search": "搜索",
  "Apply Filters": "应用过滤器",
  "Clear All": "清除全部",
  "Thumbnail": "缩略图",
  "Name": "名字",
  "Source": "来源",
  "Grid": "网格",
  "Table": "列表",
  "Embed": "嵌入",
  
  "Added": "添加",
  "Updated": "更新",
  "Updates": "更新",
  "Related": "相关",
  "Items": "物品",
  "items": "物品",
  "Misc": "杂项",
  "Recently": "最近",
  "Housing": "家宅",
  "Latest": "最新",
  "Browse": "浏览",
  "Search Items": "搜索物品",
  "Model Viewer": "模型查看器",
  "double-click to fullscreen": "双击以全屏查看",

  "new asset coming": "即将更新",
  "DO NOT USE": "请勿使用",
  "DNT": "勿用",
  "AUTOGEN": "自动生成"
};
